# spellchecker:ignore musleabihf, msvc, darwin

[graph]
targets = [
    # Linux
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "arm-unknown-linux-musleabihf" },
    { triple = "aarch64-unknown-linux-musl" },
    # Windows
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "aarch64-pc-windows-msvc" },
    # MacOS
    { triple = "x86_64-apple-darwin" },
    { triple = "aarch64-apple-darwin" }
]
all-features = true
no-default-features = false

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = [
    # The `paste` crate is no longer maintained. It is merely a build-time dependency for
    # generating code through macros. As it does not interact at all with runtime data,
    # we do not need to worry about security vulnerabilities in it. We will migrate to
    # something else, when we have time or there a need for it.
    "RUSTSEC-2024-0436",
]

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
]
confidence-threshold = 0.96

[bans]
multiple-versions = "allow"
