use std::collections::BTreeSet;

use nexigon_api::with_actions;

pub fn main() {
    // Collect all referenced modules from both input and output types.
    let mut modules = BTreeSet::new();
    macro_rules! collect_modules {
        ($(($name:literal, $variant:ident, $input:path, $output:path),)*) => {
            $(
                let input_module = stringify!($input)
                    .split("::")
                    .map(|p| p.trim())
                    .next()
                    .unwrap();
                let output_module = stringify!($output)
                    .split("::")
                    .map(|p| p.trim())
                    .next()
                    .unwrap();
                modules.insert(input_module);
                modules.insert(output_module);
            )*
        };
    }
    with_actions!(collect_modules);

    println!("# DO NOT EDIT! This file is autogenerated.");
    println!();
    println!("from __future__ import annotations");
    println!();
    println!("from typing import overload");
    println!();
    println!("import pydantic");
    println!();
    for module in &modules {
        println!("from .api_types import {module}");
    }

    // Generate _ACTION_REGISTRY.
    println!();
    println!();
    println!(
        "_ACTION_REGISTRY: dict[type, tuple[str, pydantic.TypeAdapter]] = {{  # type: ignore[type-arg]"
    );
    macro_rules! print_registry {
        ($(($name:literal, $variant:ident, $input:path, $output:path),)*) => {
            $(
                let input_parts = stringify!($input)
                    .split("::")
                    .map(|p| p.trim())
                    .collect::<Vec<_>>();
                let output_parts = stringify!($output)
                    .split("::")
                    .map(|p| p.trim())
                    .collect::<Vec<_>>();
                let input_type = input_parts.join(".");
                let output_type = output_parts.join(".");
                println!(
                    "    {input_type}: ({:?}, pydantic.TypeAdapter({output_type})),",
                    $name,
                );
            )*
        };
    }
    with_actions!(print_registry);
    println!("}}");

    // Generate _SyncExecuteMixin with @overload signatures.
    println!();
    println!();
    println!("class _SyncExecuteMixin:");
    println!("    \"\"\"Type overloads for the synchronous client.\"\"\"");
    macro_rules! print_sync_overloads {
        ($(($name:literal, $variant:ident, $input:path, $output:path),)*) => {
            $(
                let input_parts = stringify!($input)
                    .split("::")
                    .map(|p| p.trim())
                    .collect::<Vec<_>>();
                let output_parts = stringify!($output)
                    .split("::")
                    .map(|p| p.trim())
                    .collect::<Vec<_>>();
                let input_type = input_parts.join(".");
                let output_type = output_parts.join(".");
                println!();
                println!("    @overload");
                println!("    def execute(self, action: {input_type}) -> {output_type}: ...");
            )*
        };
    }
    with_actions!(print_sync_overloads);
    println!();
    println!();
    println!("    def execute(self, action: pydantic.BaseModel) -> pydantic.BaseModel:");
    println!("        return self._execute_action(action)");
    println!();
    println!("    def _execute_action(self, action: pydantic.BaseModel) -> pydantic.BaseModel:");
    println!("        raise NotImplementedError");

    // Generate _AsyncExecuteMixin with @overload signatures.
    println!();
    println!();
    println!("class _AsyncExecuteMixin:");
    println!("    \"\"\"Type overloads for the asynchronous client.\"\"\"");
    macro_rules! print_async_overloads {
        ($(($name:literal, $variant:ident, $input:path, $output:path),)*) => {
            $(
                let input_parts = stringify!($input)
                    .split("::")
                    .map(|p| p.trim())
                    .collect::<Vec<_>>();
                let output_parts = stringify!($output)
                    .split("::")
                    .map(|p| p.trim())
                    .collect::<Vec<_>>();
                let input_type = input_parts.join(".");
                let output_type = output_parts.join(".");
                println!();
                println!("    @overload");
                println!("    async def execute(self, action: {input_type}) -> {output_type}: ...");
            )*
        };
    }
    with_actions!(print_async_overloads);
    println!();
    println!();
    println!("    async def execute(self, action: pydantic.BaseModel) -> pydantic.BaseModel:");
    println!("        return await self._execute_action(action)");
    println!();
    println!(
        "    async def _execute_action(self, action: pydantic.BaseModel) -> pydantic.BaseModel:"
    );
    println!("        raise NotImplementedError");
}
