[package]
name = "nexigon-agent-protocol-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
nexigon-agent-protocol = { path = ".." }
serde_json = "1"
tokio = { version = "1", features = ["io-util", "rt"] }

[[bin]]
name = "application_frames"
path = "fuzz_targets/application_frames.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
