use nexigon_api::with_actions;

pub fn main() {
    println!("// This file is automatically generated.");
    println!("// Do not edit this file manually.");
    println!("\nimport * as actions from './actions/index.js'");
    println!("\nexport type Actions = {{");
    macro_rules! print_action_type {
        ($(($name:literal, $variant:ident, $input:path, $output:path),)*) => {
            $(
                let input_parts = stringify!($input)
                    .split("::")
                    .map(|p| p.trim())
                    .collect::<Vec<_>>();
                let output_parts = stringify!($output)
                    .split("::")
                    .map(|p| p.trim())
                    .collect::<Vec<_>>();
                let input_type = input_parts.join(".");
                let output_type = output_parts.join(".");
                println!(
                    "  {}: {{ input: actions.{input_type}; output: actions.{output_type} }};",
                    stringify!($name)
                );
            )*
        };
    }
    with_actions!(print_action_type);
    println!("}};")
}
