[package]
name = "nexigon-agent"
edition = "2024"
version = "0.5.0"
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "nexigon-agent"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
futures.workspace = true
jiff.workspace = true
jsonschema.workspace = true
nexigon-agent-api.workspace = true
nexigon-agent-protocol.workspace = true
nexigon-api.workspace = true
nexigon-cert.workspace = true
nexigon-client.workspace = true
nexigon-common.workspace = true
nexigon-ids.workspace = true
nexigon-multiplex.workspace = true
nexigon-rpc.workspace = true
nexigon-version.workspace = true
regex.workspace = true
reportify.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
si-observability.workspace = true
sidex.workspace = true
sidex-serde.workspace = true
sysinfo.workspace = true
tempfile = "3"
tokio.workspace = true
tokio-util.workspace = true
toml.workspace = true
tracing.workspace = true

[build-dependencies]
sidex-build-rs.workspace = true

[dev-dependencies]
bytes.workspace = true
tokio = { workspace = true, features = ["test-util"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(unix)'.dependencies.nix]
version = "0.29"
features = ["dir", "fs", "term", "user", "process", "signal"]
