# DO NOT EDIT! This file is autogenerated.

import pydantic

from . import actor  # noqa: F401
from . import audit  # noqa: F401
from . import cluster  # noqa: F401
from . import datetime  # noqa: F401
from . import devices  # noqa: F401
from . import digest  # noqa: F401
from . import errors  # noqa: F401
from . import fleet  # noqa: F401
from . import instance  # noqa: F401
from . import jobs  # noqa: F401
from . import json  # noqa: F401
from . import jwt  # noqa: F401
from . import organizations  # noqa: F401
from . import outputs  # noqa: F401
from . import projects  # noqa: F401
from . import properties  # noqa: F401
from . import repositories  # noqa: F401
from . import users  # noqa: F401
from . import vulnerabilities  # noqa: F401

_schemas = {
    "actor": actor,
    "audit": audit,
    "cluster": cluster,
    "datetime": datetime,
    "devices": devices,
    "digest": digest,
    "errors": errors,
    "fleet": fleet,
    "instance": instance,
    "jobs": jobs,
    "json": json,
    "jwt": jwt,
    "organizations": organizations,
    "outputs": outputs,
    "projects": projects,
    "properties": properties,
    "repositories": repositories,
    "users": users,
    "vulnerabilities": vulnerabilities,
}
for _m in _schemas.values():
    for _name, _other in _schemas.items():
        _alias = f"_schema_{_name}"
        if not hasattr(_m, _alias):
            setattr(_m, _alias, _other)
for _m in _schemas.values():
    for _attr in dir(_m):
        _obj = getattr(_m, _attr)
        if (
            isinstance(_obj, type)
            and issubclass(_obj, pydantic.BaseModel)
            and not _obj.__pydantic_complete__
        ):
            _obj.model_rebuild()
