# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import Annotated, Literal, TYPE_CHECKING, Union  # noqa: F401

import pydantic  # noqa: F401
import pydantic_core  # noqa: F401

if TYPE_CHECKING:
    from . import cluster as _schema_cluster  # noqa: F401
    from . import devices as _schema_devices  # noqa: F401
    from . import organizations as _schema_organizations  # noqa: F401
    from . import projects as _schema_projects  # noqa: F401
    from . import users as _schema_users  # noqa: F401


class AnonymousActor(pydantic.BaseModel):
    """Anonymous actor, typically used for unauthenticated actions."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)


class SystemActor(pydantic.BaseModel):
    """System actor, typically used for internal actions."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)


class DeviceActor(pydantic.BaseModel):
    """Device authenticated via a specific deployment token."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: _schema_devices.DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )
    token_id: _schema_projects.DeploymentTokenId = pydantic.Field(
        description="ID of the deployment token used for authentication.",
        validation_alias="tokenId",
        serialization_alias="tokenId",
    )


class UserActor(pydantic.BaseModel):
    """User authenticated via a user session."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    user_id: _schema_users.UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )


class UserTokenActor(pydantic.BaseModel):
    """User authenticated via a specific token."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    user_id: _schema_users.UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )
    token_id: _schema_users.UserTokenId = pydantic.Field(
        description="ID of the user token used for authentication.",
        validation_alias="tokenId",
        serialization_alias="tokenId",
    )


class ClusterNodeActor(pydantic.BaseModel):
    """Cluster node."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    node_id: _schema_cluster.ClusterNodeId = pydantic.Field(
        description="ID of the cluster node.",
        validation_alias="nodeId",
        serialization_alias="nodeId",
    )


class OrganizationApiTokenActor(pydantic.BaseModel):
    """Organization API token actor."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: _schema_organizations.OrganizationId = pydantic.Field(
        description="ID of the organization.",
        validation_alias="organizationId",
        serialization_alias="organizationId",
    )
    token_id: _schema_organizations.OrganizationApiTokenId = pydantic.Field(
        description="ID of the API token.",
        validation_alias="tokenId",
        serialization_alias="tokenId",
    )


class GetActorAction(pydantic.BaseModel):
    """Get the actor.

    This action is used to get the actor that is used to invoke the action."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)


class GetActorOutput(pydantic.BaseModel):
    """Output of getting the actor."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    actor: Actor = pydantic.Field(description="The actor.")


class Actor_Anonymous(AnonymousActor):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    actor: Literal["Anonymous"] = "Anonymous"


class Actor_System(SystemActor):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    actor: Literal["System"] = "System"


class Actor_Device(DeviceActor):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    actor: Literal["Device"] = "Device"


class Actor_User(UserActor):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    actor: Literal["User"] = "User"


class Actor_UserToken(UserTokenActor):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    actor: Literal["UserToken"] = "UserToken"


class Actor_ClusterNode(ClusterNodeActor):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    actor: Literal["ClusterNode"] = "ClusterNode"


class Actor_OrganizationApiToken(OrganizationApiTokenActor):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    actor: Literal["OrganizationApiToken"] = "OrganizationApiToken"


# Actor that may invoke actions in the system.
type Actor = Annotated[
    Actor_Anonymous
    | Actor_System
    | Actor_Device
    | Actor_User
    | Actor_UserToken
    | Actor_ClusterNode
    | Actor_OrganizationApiToken,
    pydantic.Discriminator("actor"),
]
