# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import Annotated, Literal, TYPE_CHECKING, Union  # noqa: F401

import pydantic  # noqa: F401
import pydantic_core  # noqa: F401

if TYPE_CHECKING:
    from . import actor as _schema_actor  # noqa: F401
    from . import datetime as _schema_datetime  # noqa: F401
    from . import jobs as _schema_jobs  # noqa: F401
    from . import json as _schema_json  # noqa: F401


class AuditLogActionId(str):
    """Unique ID of an audit log action."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class AuditLogEventId(str):
    """Unique ID of an audit log event."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class AuditLogEvent(pydantic.BaseModel):
    """Event recorded in the audit log.

    Audit data is guaranteed to not contain any secret information."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    event_id: AuditLogEventId = pydantic.Field(
        description="ID of the audit log event.",
        validation_alias="eventId",
        serialization_alias="eventId",
    )
    actor: _schema_actor.Actor = pydantic.Field(description="Actor causing the event.")
    event: str = pydantic.Field(description="Type of the event that was recorded.")
    data: _schema_json.JsonValue = pydantic.Field(
        description="Additional audit data associated with the event."
    )
    created_at: _schema_datetime.Timestamp = pydantic.Field(
        description="Timestamp indicating when the audit log event was recorded.",
        validation_alias="createdAt",
        serialization_alias="createdAt",
    )
    action: AuditLogEventAction | None = pydantic.Field(
        default=None, description="Action the event has been caused by (if any)."
    )
    job: AuditLogEventJob | None = pydantic.Field(
        default=None, description="Job the event has been caused by (if any)."
    )


class AuditLogEventAction(pydantic.BaseModel):
    """Action that caused an event."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    action_id: AuditLogActionId = pydantic.Field(
        description="ID of the action.",
        validation_alias="actionId",
        serialization_alias="actionId",
    )


class AuditLogEventJob(pydantic.BaseModel):
    """Job that caused an event."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    job_id: _schema_jobs.JobId = pydantic.Field(
        description="ID of the job.",
        validation_alias="jobId",
        serialization_alias="jobId",
    )


class AuditLogAction(pydantic.BaseModel):
    """Action recorded in the audit log.

    Audit data is guaranteed to not contain any secret information."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    action_id: AuditLogActionId = pydantic.Field(
        description="ID of the audit log action.",
        validation_alias="actionId",
        serialization_alias="actionId",
    )
    actor: _schema_actor.Actor = pydantic.Field(
        description="Actor that performed the action."
    )
    action: str = pydantic.Field(description="Type of the action that was performed.")
    data: dict[str, _schema_json.JsonValue] = pydantic.Field(
        description="Additional audit data associated with the action."
    )
    status: AuditLogActionStatus = pydantic.Field(
        description="Status associated with the action"
    )
    created_at: _schema_datetime.Timestamp = pydantic.Field(
        description="Timestamp indicating when the audit log action was recorded.",
        validation_alias="createdAt",
        serialization_alias="createdAt",
    )


class QueryAuditLogEventsAction(pydantic.BaseModel):
    """Query the events recorded in the audit log.

    Requires administrator permissions."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)


class QueryAuditLogEventsOutput(pydantic.BaseModel):
    """Output of querying the events recorded in the audit log."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    events: list[AuditLogEvent] = pydantic.Field(description="List of audit events.")


class QueryAuditLogActionsAction(pydantic.BaseModel):
    """Query the actions recorded in the audit log.

    Requires administrator permissions."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)


class QueryAuditLogActionsOutput(pydantic.BaseModel):
    """Output of querying the actions recorded in the audit log."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    actions: list[AuditLogAction] = pydantic.Field(description="List of actions.")


class AuditLogActionStatus_Rejected(pydantic.RootModel[Literal["Rejected"]]):
    pass


class AuditLogActionStatus_Panicked(pydantic.RootModel[Literal["Panicked"]]):
    pass


class AuditLogActionStatus_Succeeded(pydantic.RootModel[Literal["Succeeded"]]):
    pass


class AuditLogActionStatus_Failed(pydantic.RootModel[Literal["Failed"]]):
    pass


class AuditLogActionStatus_Pending(pydantic.RootModel[Literal["Pending"]]):
    pass


# Status associated with an audit log action.
type AuditLogActionStatus = (
    AuditLogActionStatus_Rejected
    | AuditLogActionStatus_Panicked
    | AuditLogActionStatus_Succeeded
    | AuditLogActionStatus_Failed
    | AuditLogActionStatus_Pending
)
