# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import Annotated, Literal, TYPE_CHECKING, Union  # noqa: F401

import pydantic  # noqa: F401
import pydantic_core  # noqa: F401

if TYPE_CHECKING:
    from . import actor  # noqa: F401
    from . import datetime  # noqa: F401
    from . import jobs  # noqa: F401
    from . import json  # noqa: F401


class AuditLogActionId(str):
    """Unique ID of an audit log action."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class AuditLogEventId(str):
    """Unique ID of an audit log event."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class AuditLogEvent(pydantic.BaseModel):
    """Event recorded in the audit log.

    Audit data is guaranteed to not contain any secret information."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    event_id: AuditLogEventId = pydantic.Field(
        validation_alias="eventId", serialization_alias="eventId"
    )
    actor: actor.Actor
    event: str
    data: json.JsonValue
    created_at: datetime.Timestamp = pydantic.Field(
        validation_alias="createdAt", serialization_alias="createdAt"
    )
    action: AuditLogEventAction | None = None
    job: AuditLogEventJob | None = None


class AuditLogEventAction(pydantic.BaseModel):
    """Action that caused an event."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    action_id: AuditLogActionId = pydantic.Field(
        validation_alias="actionId", serialization_alias="actionId"
    )


class AuditLogEventJob(pydantic.BaseModel):
    """Job that caused an event."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    job_id: jobs.JobId = pydantic.Field(
        validation_alias="jobId", serialization_alias="jobId"
    )


class AuditLogAction(pydantic.BaseModel):
    """Action recorded in the audit log.

    Audit data is guaranteed to not contain any secret information."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    action_id: AuditLogActionId = pydantic.Field(
        validation_alias="actionId", serialization_alias="actionId"
    )
    actor: actor.Actor
    action: str
    data: dict[str, json.JsonValue]
    status: AuditLogActionStatus
    created_at: datetime.Timestamp = pydantic.Field(
        validation_alias="createdAt", serialization_alias="createdAt"
    )


class QueryAuditLogEventsAction(pydantic.BaseModel):
    """Query the events recorded in the audit log.

    Requires administrator permissions."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)


class QueryAuditLogEventsOutput(pydantic.BaseModel):
    """Output of querying the events recorded in the audit log."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    events: list[AuditLogEvent]


class QueryAuditLogActionsAction(pydantic.BaseModel):
    """Query the actions recorded in the audit log.

    Requires administrator permissions."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)


class QueryAuditLogActionsOutput(pydantic.BaseModel):
    """Output of querying the actions recorded in the audit log."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    actions: list[AuditLogAction]


class AuditLogActionStatus_Rejected(pydantic.RootModel[Literal["Rejected"]]):
    pass


class AuditLogActionStatus_Panicked(pydantic.RootModel[Literal["Panicked"]]):
    pass


class AuditLogActionStatus_Succeeded(pydantic.RootModel[Literal["Succeeded"]]):
    pass


class AuditLogActionStatus_Failed(pydantic.RootModel[Literal["Failed"]]):
    pass


class AuditLogActionStatus_Pending(pydantic.RootModel[Literal["Pending"]]):
    pass


# Status associated with an audit log action.
type AuditLogActionStatus = (
    AuditLogActionStatus_Rejected
    | AuditLogActionStatus_Panicked
    | AuditLogActionStatus_Succeeded
    | AuditLogActionStatus_Failed
    | AuditLogActionStatus_Pending
)
