# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import Annotated, Literal, TYPE_CHECKING, Union  # noqa: F401

import pydantic  # noqa: F401
import pydantic_core  # noqa: F401

if TYPE_CHECKING:
    from . import datetime as _schema_datetime  # noqa: F401


class ClusterNodeId(str):
    """Unique ID of a cluster node."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class GetClusterDetailsAction(pydantic.BaseModel):
    """Get information about the cluster."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    include_terminated: bool | None = pydantic.Field(
        default=None,
        description="Include terminated nodes in the response.",
        validation_alias="includeTerminated",
        serialization_alias="includeTerminated",
    )


class GetClusterDetailsOutput(pydantic.BaseModel):
    """Information about the cluster."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    nodes: list[ClusterNode] = pydantic.Field(description="Nodes of the cluster.")


class ClusterNode(pydantic.BaseModel):
    """Cluster node."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    node_id: ClusterNodeId = pydantic.Field(
        description="ID of the cluster node.",
        validation_alias="nodeId",
        serialization_alias="nodeId",
    )
    name: str | None = pydantic.Field(
        default=None, description="Name of the cluster node."
    )
    status: ClusterNodeStatus = pydantic.Field(
        description="Status of the cluster node."
    )
    joined_at: _schema_datetime.Timestamp = pydantic.Field(
        description="Timestamp when the node joined the cluster.",
        validation_alias="joinedAt",
        serialization_alias="joinedAt",
    )
    uptime_secs: int = pydantic.Field(
        description="Uptime of the node in seconds.",
        validation_alias="uptimeSecs",
        serialization_alias="uptimeSecs",
    )
    last_heartbeat: _schema_datetime.Timestamp = pydantic.Field(
        description="Timestamp when the node last reported a heartbeat.",
        validation_alias="lastHeartbeat",
        serialization_alias="lastHeartbeat",
    )
    terminated_at: _schema_datetime.Timestamp | None = pydantic.Field(
        default=None,
        description="Timestamp when the node was terminated.",
        validation_alias="terminatedAt",
        serialization_alias="terminatedAt",
    )
    termination_reason: ClusterNodeTerminationReason | None = pydantic.Field(
        default=None,
        description="Reason why the node was terminated.",
        validation_alias="terminationReason",
        serialization_alias="terminationReason",
    )


class RegisterClusterNodeAction(pydantic.BaseModel):
    """Register a new cluster node."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    name: str | None = pydantic.Field(
        default=None, description="Name of the cluster node."
    )


class RegisterClusterNodeOutput(pydantic.BaseModel):
    """Output of registering a new cluster node."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    node_id: ClusterNodeId = pydantic.Field(
        description="ID of the cluster node.",
        validation_alias="nodeId",
        serialization_alias="nodeId",
    )


class ReportClusterNodeHeartbeatAction(pydantic.BaseModel):
    """Report the heartbeat of a cluster node."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)


class CleanupInactiveClusterNodesAction(pydantic.BaseModel):
    """Cleanup inactive cluster nodes."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)


class ClusterNodeStatus_Active(pydantic.RootModel[Literal["Active"]]):
    pass


class ClusterNodeStatus_Terminated(pydantic.RootModel[Literal["Terminated"]]):
    pass


# Status of a cluster node.
type ClusterNodeStatus = ClusterNodeStatus_Active | ClusterNodeStatus_Terminated


class ClusterNodeTerminationReason_Unknown(pydantic.RootModel[Literal["Unknown"]]):
    pass


class ClusterNodeTerminationReason_HeartbeatTimeout(
    pydantic.RootModel[Literal["HeartbeatTimeout"]]
):
    pass


class ClusterNodeTerminationReason_Shutdown(pydantic.RootModel[Literal["Shutdown"]]):
    pass


# Reason why a cluster node was terminated.
type ClusterNodeTerminationReason = (
    ClusterNodeTerminationReason_Unknown
    | ClusterNodeTerminationReason_HeartbeatTimeout
    | ClusterNodeTerminationReason_Shutdown
)
