# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import Annotated, Literal, TYPE_CHECKING, Union  # noqa: F401

import pydantic  # noqa: F401
import pydantic_core  # noqa: F401


class Timestamp(str):
    """ISO 8601 formatted date and time string."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class Date(str):
    """Date string without time zone."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class DateSpan(pydantic.BaseModel):
    """Date span with start and end dates.

    **The end date itself is not included in the span.**"""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    start: Date = pydantic.Field(description="Start date of the span.")
    end: Date = pydantic.Field(
        description="End date of the span.\n\n**The end date itself is not included in the span.**"
    )
