# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import Annotated, Literal, TYPE_CHECKING, Union  # noqa: F401

import pydantic  # noqa: F401
import pydantic_core  # noqa: F401

if TYPE_CHECKING:
    from . import actor  # noqa: F401
    from . import audit  # noqa: F401
    from . import cluster  # noqa: F401
    from . import datetime  # noqa: F401
    from . import json  # noqa: F401
    from . import jwt  # noqa: F401
    from . import projects  # noqa: F401
    from . import properties  # noqa: F401


class DeviceId(str):
    """Unique ID of a device."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class DeviceFingerprint(str):
    """Device fingerprint."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class DeviceFingerprintId(str):
    """Device fingerprint ID."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class DeviceCertificateId(str):
    """Unique ID of a device certificate."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class DeviceConnectionId(str):
    """Unique ID of a device connection."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class CertificateFingerprint(str):
    """Fingerprint of a device certificate."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class DeviceEventId(str):
    """ID of a device event (unique per device)."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class QueryDevicesAction(pydantic.BaseModel):
    """Query the devices of the instance."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)


class QueryDevicesOutput(pydantic.BaseModel):
    """Output of querying the devices of the instance."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    devices: list[QueryDevicesItem]


class QueryDevicesItem(pydantic.BaseModel):
    """Device item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: DeviceId = pydantic.Field(
        validation_alias="deviceId", serialization_alias="deviceId"
    )
    project_id: projects.ProjectId = pydantic.Field(
        validation_alias="projectId", serialization_alias="projectId"
    )
    is_connected: bool = pydantic.Field(
        validation_alias="isConnected", serialization_alias="isConnected"
    )
    last_connected_at: datetime.Timestamp | None = pydantic.Field(
        default=None,
        validation_alias="lastConnectedAt",
        serialization_alias="lastConnectedAt",
    )
    current_connection_duration_secs: int | None = pydantic.Field(
        default=None,
        validation_alias="currentConnectionDurationSecs",
        serialization_alias="currentConnectionDurationSecs",
    )


class GetDeviceDetailsAction(pydantic.BaseModel):
    """Get information about a device."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: DeviceId = pydantic.Field(
        validation_alias="deviceId", serialization_alias="deviceId"
    )


class GetDeviceDetailsOutput(pydantic.BaseModel):
    """Output of getting information about a device."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: DeviceId = pydantic.Field(
        validation_alias="deviceId", serialization_alias="deviceId"
    )
    project_id: projects.ProjectId = pydantic.Field(
        validation_alias="projectId", serialization_alias="projectId"
    )
    fingerprint_id: DeviceFingerprintId = pydantic.Field(
        validation_alias="fingerprintId", serialization_alias="fingerprintId"
    )
    name: str | None = None
    is_connected: bool = pydantic.Field(
        validation_alias="isConnected", serialization_alias="isConnected"
    )
    certificates: list[DeviceCertificate]
    connections: list[DeviceConnection]


class DeviceCertificate(pydantic.BaseModel):
    """Device certificate."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    certificate_id: DeviceCertificateId = pydantic.Field(
        validation_alias="certificateId", serialization_alias="certificateId"
    )
    status: DeviceCertificateStatus
    fingerprint: CertificateFingerprint
    first_seen: datetime.Timestamp = pydantic.Field(
        validation_alias="firstSeen", serialization_alias="firstSeen"
    )


class DeviceConnection(pydantic.BaseModel):
    """Device connection."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    connection_id: DeviceConnectionId = pydantic.Field(
        validation_alias="connectionId", serialization_alias="connectionId"
    )
    node_id: cluster.ClusterNodeId = pydantic.Field(
        validation_alias="nodeId", serialization_alias="nodeId"
    )
    connected_at: datetime.Timestamp = pydantic.Field(
        validation_alias="connectedAt", serialization_alias="connectedAt"
    )
    connected_for_secs: int = pydantic.Field(
        validation_alias="connectedForSecs", serialization_alias="connectedForSecs"
    )


class DeviceConnectionLog(pydantic.BaseModel):
    """Device connection log entry (for connection history)."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    connection_id: DeviceConnectionId = pydantic.Field(
        validation_alias="connectionId", serialization_alias="connectionId"
    )
    node_id: cluster.ClusterNodeId = pydantic.Field(
        validation_alias="nodeId", serialization_alias="nodeId"
    )
    connected_at: datetime.Timestamp = pydantic.Field(
        validation_alias="connectedAt", serialization_alias="connectedAt"
    )
    ended_at: datetime.Timestamp | None = pydantic.Field(
        default=None, validation_alias="endedAt", serialization_alias="endedAt"
    )
    end_reason: ConnectionEndReason | None = pydantic.Field(
        default=None, validation_alias="endReason", serialization_alias="endReason"
    )
    duration_secs: int = pydantic.Field(
        validation_alias="durationSecs", serialization_alias="durationSecs"
    )


class CreateDeviceAction(pydantic.BaseModel):
    """Create a new device."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: projects.ProjectId = pydantic.Field(
        validation_alias="projectId", serialization_alias="projectId"
    )
    fingerprint: DeviceFingerprint


class CreateDeviceOutput(pydantic.BaseModel):
    """Output of creating a new device."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: DeviceId = pydantic.Field(
        validation_alias="deviceId", serialization_alias="deviceId"
    )


class DeleteDeviceAction(pydantic.BaseModel):
    """Delete a device."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: DeviceId = pydantic.Field(
        validation_alias="deviceId", serialization_alias="deviceId"
    )


class SetDeviceNameAction(pydantic.BaseModel):
    """Set the name of a device."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: DeviceId = pydantic.Field(
        validation_alias="deviceId", serialization_alias="deviceId"
    )
    name: str | None = None


class IssueDeviceTokenAction(pydantic.BaseModel):
    """Issue a JWT for a device with user-defined claims.

    **Note: Only use this action for integration with external systems.**"""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: DeviceId = pydantic.Field(
        validation_alias="deviceId", serialization_alias="deviceId"
    )
    valid_for_secs: int | None = pydantic.Field(
        default=None,
        validation_alias="validForSecs",
        serialization_alias="validForSecs",
    )
    claims: json.JsonValue | None = None


class IssueDeviceTokenOutput(pydantic.BaseModel):
    """Output of issuing a JWT for a device."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    jwt: jwt.Jwt


class ValidateDeviceTokenAction(pydantic.BaseModel):
    """Validate a device JWT.

    **Note: Only use this action for integration with external systems.**"""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    jwt: jwt.Jwt


class ValidateDeviceTokenSuccess(pydantic.BaseModel):
    """Successful validation of a device JWT."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: DeviceId = pydantic.Field(
        validation_alias="deviceId", serialization_alias="deviceId"
    )
    claims: json.JsonValue


class AuthenticateDeviceAction(pydantic.BaseModel):
    """Authenticate a device.

    **Note: The certificate fingerprint must be externally verified (mutual TLS).**"""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    fingerprint: DeviceFingerprint
    token: projects.DeploymentToken
    certificate: CertificateFingerprint


class AuthenticateDeviceOutput(pydantic.BaseModel):
    """Output of authenticating a device."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: DeviceId = pydantic.Field(
        validation_alias="deviceId", serialization_alias="deviceId"
    )
    token_id: projects.DeploymentTokenId = pydantic.Field(
        validation_alias="tokenId", serialization_alias="tokenId"
    )
    fingerprint_id: DeviceFingerprintId = pydantic.Field(
        validation_alias="fingerprintId", serialization_alias="fingerprintId"
    )
    certificate_id: DeviceCertificateId = pydantic.Field(
        validation_alias="certificateId", serialization_alias="certificateId"
    )
    actor: actor.Actor


class AddDeviceCertificateAction(pydantic.BaseModel):
    """Add a device certificate."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: DeviceId = pydantic.Field(
        validation_alias="deviceId", serialization_alias="deviceId"
    )
    fingerprint: CertificateFingerprint
    status: DeviceCertificateStatus | None = None


class AddDeviceCertificateOutput(pydantic.BaseModel):
    """Output of adding a device certificate."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    certificate_id: DeviceCertificateId = pydantic.Field(
        validation_alias="certificateId", serialization_alias="certificateId"
    )


class DeleteDeviceCertificateAction(pydantic.BaseModel):
    """Delete a device certificate."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    certificate_id: DeviceCertificateId = pydantic.Field(
        validation_alias="certificateId", serialization_alias="certificateId"
    )


class SetDeviceCertificateStatusAction(pydantic.BaseModel):
    """Set the status of a device certificate."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    certificate_id: DeviceCertificateId = pydantic.Field(
        validation_alias="certificateId", serialization_alias="certificateId"
    )
    status: DeviceCertificateStatus


class RegisterDeviceConnectionAction(pydantic.BaseModel):
    """Register a connection of a device to a cluster node."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: DeviceId = pydantic.Field(
        validation_alias="deviceId", serialization_alias="deviceId"
    )
    node_id: cluster.ClusterNodeId = pydantic.Field(
        validation_alias="nodeId", serialization_alias="nodeId"
    )
    connection_id: DeviceConnectionId = pydantic.Field(
        validation_alias="connectionId", serialization_alias="connectionId"
    )


class RegisterDeviceConnectionOutput(pydantic.BaseModel):
    """Output of registering a connection of a device to a cluster node."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    connection_id: DeviceConnectionId = pydantic.Field(
        validation_alias="connectionId", serialization_alias="connectionId"
    )


class UnregisterDeviceConnectionAction(pydantic.BaseModel):
    """Unregister a connection of a device to a cluster node."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    connection_id: DeviceConnectionId = pydantic.Field(
        validation_alias="connectionId", serialization_alias="connectionId"
    )
    end_reason: ConnectionEndReason = pydantic.Field(
        validation_alias="endReason", serialization_alias="endReason"
    )


class QueryDeviceConnectionsAction(pydantic.BaseModel):
    """Query the connection history of a device."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: DeviceId = pydantic.Field(
        validation_alias="deviceId", serialization_alias="deviceId"
    )
    limit: int | None = None
    active_only: bool | None = pydantic.Field(
        default=None, validation_alias="activeOnly", serialization_alias="activeOnly"
    )


class QueryDeviceConnectionsOutput(pydantic.BaseModel):
    """Output of querying device connections."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    connections: list[DeviceConnectionLog]


class IssueDeviceHttpProxyTokenAction(pydantic.BaseModel):
    """Issue a HTTP proxy JWT."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: DeviceId = pydantic.Field(
        alias="deviceId", serialization_alias="deviceId"
    )
    valid_for_secs: int | None = pydantic.Field(
        default=None,
        validation_alias="validForSecs",
        serialization_alias="validForSecs",
    )
    hostname: str | None = None
    port: int | None = None
    redirect: str | None = None


class IssueDeviceHttpProxyTokenOutput(pydantic.BaseModel):
    """Output of issuing a HTTP proxy JWT."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    jwt: jwt.Jwt
    url: str


class ValidateDeviceHttpProxyTokenAction(pydantic.BaseModel):
    """Validate a HTTP proxy JWT."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    jwt: jwt.Jwt


class ValidateDeviceHttpProxyTokenInvalid(pydantic.BaseModel):
    """Validation of a HTTP proxy JWT failed."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    redirect: str | None = None


class ValidateDeviceHttpProxyTokenSuccess(pydantic.BaseModel):
    """Successful validation of a HTTP proxy JWT."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: DeviceId = pydantic.Field(
        validation_alias="deviceId", serialization_alias="deviceId"
    )
    hostname: str | None = None
    port: int | None = None


class PublishDeviceEventsAction(pydantic.BaseModel):
    """Publish device events."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: DeviceId = pydantic.Field(
        validation_alias="deviceId", serialization_alias="deviceId"
    )
    events: list[DeviceEvent]


class QueryDeviceEventsAction(pydantic.BaseModel):
    """Query device events."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: DeviceId = pydantic.Field(
        validation_alias="deviceId", serialization_alias="deviceId"
    )
    limit: int | None = None


class QueryDeviceEventsOutput(pydantic.BaseModel):
    """Output of querying device events."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    events: list[DeviceEvent]


class DeviceEvent(pydantic.BaseModel):
    """Event emitted by a device."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    event_id: DeviceEventId = pydantic.Field(
        validation_alias="eventId", serialization_alias="eventId"
    )
    category: str | None = None
    severity: DeviceEventSeverity
    body: json.JsonValue
    attributes: dict[str, json.JsonValue]
    emitted_at: datetime.Timestamp = pydantic.Field(
        validation_alias="emittedAt", serialization_alias="emittedAt"
    )
    received_at: datetime.Timestamp | None = pydantic.Field(
        default=None, validation_alias="receivedAt", serialization_alias="receivedAt"
    )


class SetDevicePropertyAction(pydantic.BaseModel):
    """Set a property of a device."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: DeviceId = pydantic.Field(
        validation_alias="deviceId", serialization_alias="deviceId"
    )
    name: str
    value: json.JsonValue
    protected: bool | None = None
    expected_version: int | None = pydantic.Field(
        default=None,
        validation_alias="expectedVersion",
        serialization_alias="expectedVersion",
    )


class SetDevicePropertyVersionConflict(pydantic.BaseModel):
    """Details of a version conflict when setting a device property."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    current_version: int = pydantic.Field(
        validation_alias="currentVersion", serialization_alias="currentVersion"
    )


class GetDevicePropertyAction(pydantic.BaseModel):
    """Get a property of a device."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: DeviceId = pydantic.Field(
        validation_alias="deviceId", serialization_alias="deviceId"
    )
    name: str


class RemoveDevicePropertyAction(pydantic.BaseModel):
    """Remove a property from a device."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: DeviceId = pydantic.Field(
        validation_alias="deviceId", serialization_alias="deviceId"
    )
    name: str


class QueryDevicePropertiesAction(pydantic.BaseModel):
    """Query the properties of a device."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: DeviceId = pydantic.Field(
        validation_alias="deviceId", serialization_alias="deviceId"
    )


class QueryDevicePropertiesOutput(pydantic.BaseModel):
    """Output of querying the properties of a device."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    properties: dict[str, DeviceProperty]


class DeviceProperty(pydantic.BaseModel):
    """Device property."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    name: str
    value: json.JsonValue
    protected: bool
    version: int
    last_updated: datetime.Timestamp = pydantic.Field(
        validation_alias="lastUpdated", serialization_alias="lastUpdated"
    )


class QueryDeviceAuditLogAction(pydantic.BaseModel):
    """Query the audit log of a device."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: DeviceId = pydantic.Field(
        validation_alias="deviceId", serialization_alias="deviceId"
    )


class QueryDeviceAuditLogOutput(pydantic.BaseModel):
    """Output of querying the audit log of a device."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    events: list[audit.AuditLogEvent]


class QueryDeviceCommandsAction(pydantic.BaseModel):
    """Query the on-demand commands supported by a device."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: DeviceId = pydantic.Field(
        validation_alias="deviceId", serialization_alias="deviceId"
    )


class QueryDeviceCommandsOutput(pydantic.BaseModel):
    """Output of querying device commands."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    manifest: properties.DeviceCommandManifest


class DeviceCommandInvokeData(pydantic.BaseModel):
    """Command invocation parameters."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    command: str
    input: json.JsonValue
    stream_log: bool | None = pydantic.Field(
        default=None, validation_alias="streamLog", serialization_alias="streamLog"
    )
    timeout_secs: int | None = pydantic.Field(
        default=None, validation_alias="timeoutSecs", serialization_alias="timeoutSecs"
    )


class DeviceCommandLogData(pydantic.BaseModel):
    """Log data."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    lines: list[str]


class DeviceCommandDoneData(pydantic.BaseModel):
    """Command completion."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    status: DeviceCommandStatus
    output: json.JsonValue | None = None
    error: str | None = None
    log_tail: list[str] = pydantic.Field(
        validation_alias="logTail", serialization_alias="logTail"
    )
    duration_ms: int = pydantic.Field(
        validation_alias="durationMs", serialization_alias="durationMs"
    )


class DeviceStatus_Healthy(pydantic.RootModel[Literal["healthy"]]):
    pass


class DeviceStatus_Warning(pydantic.RootModel[Literal["warning"]]):
    pass


class DeviceStatus_Error(pydantic.RootModel[Literal["error"]]):
    pass


class DeviceStatus_Offline(pydantic.RootModel[Literal["offline"]]):
    pass


# Combined device status (connection + health).
type DeviceStatus = (
    DeviceStatus_Healthy
    | DeviceStatus_Warning
    | DeviceStatus_Error
    | DeviceStatus_Offline
)


class DeviceCertificateStatus_Pending(pydantic.RootModel[Literal["Pending"]]):
    pass


class DeviceCertificateStatus_Active(pydantic.RootModel[Literal["Active"]]):
    pass


class DeviceCertificateStatus_Rejected(pydantic.RootModel[Literal["Rejected"]]):
    pass


class DeviceCertificateStatus_Revoked(pydantic.RootModel[Literal["Revoked"]]):
    pass


# Status of a device certificate.
type DeviceCertificateStatus = (
    DeviceCertificateStatus_Pending
    | DeviceCertificateStatus_Active
    | DeviceCertificateStatus_Rejected
    | DeviceCertificateStatus_Revoked
)


class ConnectionEndReason_Unknown(pydantic.RootModel[Literal["Unknown"]]):
    pass


class ConnectionEndReason_Disconnected(pydantic.RootModel[Literal["Disconnected"]]):
    pass


class ConnectionEndReason_NodeCrashed(pydantic.RootModel[Literal["NodeCrashed"]]):
    pass


class ConnectionEndReason_ServerShutdown(pydantic.RootModel[Literal["ServerShutdown"]]):
    pass


# Reason why a device connection ended.
type ConnectionEndReason = (
    ConnectionEndReason_Unknown
    | ConnectionEndReason_Disconnected
    | ConnectionEndReason_NodeCrashed
    | ConnectionEndReason_ServerShutdown
)


class ValidateDeviceTokenOutput_Invalid(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Invalid"] = "Invalid"


class ValidateDeviceTokenOutput_Valid(ValidateDeviceTokenSuccess):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Valid"] = "Valid"


# Output of validating a device JWT.
type ValidateDeviceTokenOutput = Annotated[
    ValidateDeviceTokenOutput_Invalid | ValidateDeviceTokenOutput_Valid,
    pydantic.Discriminator("result"),
]


class ValidateDeviceHttpProxyTokenOutput_Invalid(ValidateDeviceHttpProxyTokenInvalid):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Invalid"] = "Invalid"


class ValidateDeviceHttpProxyTokenOutput_Valid(ValidateDeviceHttpProxyTokenSuccess):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Valid"] = "Valid"


# Output of validating a HTTP proxy JWT.
type ValidateDeviceHttpProxyTokenOutput = Annotated[
    ValidateDeviceHttpProxyTokenOutput_Invalid
    | ValidateDeviceHttpProxyTokenOutput_Valid,
    pydantic.Discriminator("result"),
]


class DeviceEventSeverity_Trace(pydantic.RootModel[Literal["Trace"]]):
    pass


class DeviceEventSeverity_Debug(pydantic.RootModel[Literal["Debug"]]):
    pass


class DeviceEventSeverity_Info(pydantic.RootModel[Literal["Info"]]):
    pass


class DeviceEventSeverity_Warning(pydantic.RootModel[Literal["Warning"]]):
    pass


class DeviceEventSeverity_Error(pydantic.RootModel[Literal["Error"]]):
    pass


class DeviceEventSeverity_Critical(pydantic.RootModel[Literal["Critical"]]):
    pass


# Severity of a device event.
type DeviceEventSeverity = (
    DeviceEventSeverity_Trace
    | DeviceEventSeverity_Debug
    | DeviceEventSeverity_Info
    | DeviceEventSeverity_Warning
    | DeviceEventSeverity_Error
    | DeviceEventSeverity_Critical
)


class SetDevicePropertyOutput_Set(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Set"] = "Set"


class SetDevicePropertyOutput_VersionConflict(SetDevicePropertyVersionConflict):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["VersionConflict"] = "VersionConflict"


class SetDevicePropertyOutput_Deleted(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Deleted"] = "Deleted"


# Output of setting a device property.
type SetDevicePropertyOutput = Annotated[
    SetDevicePropertyOutput_Set
    | SetDevicePropertyOutput_VersionConflict
    | SetDevicePropertyOutput_Deleted,
    pydantic.Discriminator("result"),
]


class GetDevicePropertyOutput_NotFound(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["NotFound"] = "NotFound"


class GetDevicePropertyOutput_Found(DeviceProperty):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Found"] = "Found"


# Output of getting a property of a device.
type GetDevicePropertyOutput = Annotated[
    GetDevicePropertyOutput_NotFound | GetDevicePropertyOutput_Found,
    pydantic.Discriminator("result"),
]


class RemoveDevicePropertyOutput_NotFound(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["NotFound"] = "NotFound"


class RemoveDevicePropertyOutput_Removed(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Removed"] = "Removed"


# Output of removing a property from a device.
type RemoveDevicePropertyOutput = Annotated[
    RemoveDevicePropertyOutput_NotFound | RemoveDevicePropertyOutput_Removed,
    pydantic.Discriminator("result"),
]


class DeviceCommandStatus_Ok(pydantic.RootModel[Literal["Ok"]]):
    pass


class DeviceCommandStatus_Error(pydantic.RootModel[Literal["Error"]]):
    pass


# Status of a device command invocation.
type DeviceCommandStatus = DeviceCommandStatus_Ok | DeviceCommandStatus_Error


class DeviceCommandHubFrame_Invoke(DeviceCommandInvokeData):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    type: Literal["Invoke"] = "Invoke"


# Hub-to-device frame.
type DeviceCommandHubFrame = DeviceCommandHubFrame_Invoke


class DeviceCommandDeviceFrame_Log(DeviceCommandLogData):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    type: Literal["Log"] = "Log"


class DeviceCommandDeviceFrame_Done(DeviceCommandDoneData):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    type: Literal["Done"] = "Done"


# Device-to-hub frame.
type DeviceCommandDeviceFrame = Annotated[
    DeviceCommandDeviceFrame_Log | DeviceCommandDeviceFrame_Done,
    pydantic.Discriminator("type"),
]
