# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import Annotated, Literal, TYPE_CHECKING, Union  # noqa: F401

import pydantic  # noqa: F401
import pydantic_core  # noqa: F401

if TYPE_CHECKING:
    from . import audit as _schema_audit  # noqa: F401
    from . import cluster as _schema_cluster  # noqa: F401
    from . import datetime as _schema_datetime  # noqa: F401
    from . import json as _schema_json  # noqa: F401
    from . import jwt as _schema_jwt  # noqa: F401
    from . import projects as _schema_projects  # noqa: F401
    from . import properties as _schema_properties  # noqa: F401


class DeviceId(str):
    """Unique ID of a device."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class DeviceFingerprint(str):
    """Device fingerprint."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class DeviceFingerprintId(str):
    """Device fingerprint ID."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class DeviceCertificateId(str):
    """Unique ID of a device certificate."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class DeviceConnectionId(str):
    """Unique ID of a device connection."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class CertificateFingerprint(str):
    """Fingerprint of a device certificate."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class DeviceEventId(str):
    """ID of a device event (unique per device)."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class QueryDevicesAction(pydantic.BaseModel):
    """Query the devices of the instance."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )


class QueryDevicesOutput(pydantic.BaseModel):
    """Output of querying the devices of the instance."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    devices: list[QueryDevicesItem] = pydantic.Field(description="List of devices.")


class QueryDevicesItem(pydantic.BaseModel):
    """Device item."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    device_id: DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )
    project_id: _schema_projects.ProjectId = pydantic.Field(
        description="Project ID of the device.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )
    is_connected: bool = pydantic.Field(
        description="Indicates whether the device is currently connected.",
        validation_alias="isConnected",
        serialization_alias="isConnected",
    )
    last_connected_at: _schema_datetime.Timestamp | None = pydantic.Field(
        default=None,
        description="Timestamp when the device was last connected (current or most recent connection).",
        validation_alias="lastConnectedAt",
        serialization_alias="lastConnectedAt",
    )
    current_connection_duration_secs: int | None = pydantic.Field(
        default=None,
        description="Duration of the current connection in seconds (null if not connected).",
        validation_alias="currentConnectionDurationSecs",
        serialization_alias="currentConnectionDurationSecs",
    )


class GetDeviceDetailsAction(pydantic.BaseModel):
    """Get information about a device."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    device_id: DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )


class GetDeviceDetailsOutput(pydantic.BaseModel):
    """Output of getting information about a device."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    device_id: DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )
    project_id: _schema_projects.ProjectId = pydantic.Field(
        description="Project ID of the device.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )
    fingerprint_id: DeviceFingerprintId = pydantic.Field(
        description="Fingerprint ID the device.",
        validation_alias="fingerprintId",
        serialization_alias="fingerprintId",
    )
    name: str | None = pydantic.Field(default=None, description="Name of the device.")
    is_connected: bool = pydantic.Field(
        description="Indicates whether the device is online.",
        validation_alias="isConnected",
        serialization_alias="isConnected",
    )
    certificates: list[DeviceCertificate] = pydantic.Field(
        description="Certificates of the device."
    )
    connections: list[DeviceConnection] = pydantic.Field(
        description="Connections of the device."
    )


class DeviceCertificate(pydantic.BaseModel):
    """Device certificate."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    certificate_id: DeviceCertificateId = pydantic.Field(
        description="ID of the certificate.",
        validation_alias="certificateId",
        serialization_alias="certificateId",
    )
    status: DeviceCertificateStatus = pydantic.Field(
        description="Status of the certificate."
    )
    fingerprint: CertificateFingerprint = pydantic.Field(
        description="Fingerprint of the certificate."
    )
    first_seen: _schema_datetime.Timestamp = pydantic.Field(
        description="Timestamp when the certificate was first seen.",
        validation_alias="firstSeen",
        serialization_alias="firstSeen",
    )


class DeviceConnection(pydantic.BaseModel):
    """Device connection."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    connection_id: DeviceConnectionId = pydantic.Field(
        description="ID of the connection.",
        validation_alias="connectionId",
        serialization_alias="connectionId",
    )
    node_id: _schema_cluster.ClusterNodeId = pydantic.Field(
        description="ID of the cluster node.",
        validation_alias="nodeId",
        serialization_alias="nodeId",
    )
    connected_at: _schema_datetime.Timestamp = pydantic.Field(
        description="Timestamp when the connection was established.",
        validation_alias="connectedAt",
        serialization_alias="connectedAt",
    )
    connected_for_secs: int = pydantic.Field(
        description="Duration of the connection in seconds.",
        validation_alias="connectedForSecs",
        serialization_alias="connectedForSecs",
    )


class DeviceConnectionLog(pydantic.BaseModel):
    """Device connection log entry (for connection history)."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    connection_id: DeviceConnectionId = pydantic.Field(
        description="ID of the connection.",
        validation_alias="connectionId",
        serialization_alias="connectionId",
    )
    node_id: _schema_cluster.ClusterNodeId = pydantic.Field(
        description="ID of the cluster node.",
        validation_alias="nodeId",
        serialization_alias="nodeId",
    )
    connected_at: _schema_datetime.Timestamp = pydantic.Field(
        description="Timestamp when the connection was established.",
        validation_alias="connectedAt",
        serialization_alias="connectedAt",
    )
    ended_at: _schema_datetime.Timestamp | None = pydantic.Field(
        default=None,
        description="Timestamp when the connection ended (null if still connected).",
        validation_alias="endedAt",
        serialization_alias="endedAt",
    )
    end_reason: ConnectionEndReason | None = pydantic.Field(
        default=None,
        description="Reason why the connection ended (null if still connected).",
        validation_alias="endReason",
        serialization_alias="endReason",
    )
    duration_secs: int = pydantic.Field(
        description="Duration of the connection in seconds.",
        validation_alias="durationSecs",
        serialization_alias="durationSecs",
    )


class CreateDeviceAction(pydantic.BaseModel):
    """Create a new device."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    project_id: _schema_projects.ProjectId = pydantic.Field(
        description="ID of the project.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )
    fingerprint: DeviceFingerprint = pydantic.Field(
        description="Fingerprint of the device."
    )


class CreateDeviceOutput(pydantic.BaseModel):
    """Output of creating a new device."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    device_id: DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )


class DeleteDeviceAction(pydantic.BaseModel):
    """Delete a device."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    device_id: DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )


class SetDeviceNameAction(pydantic.BaseModel):
    """Set the name of a device."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    device_id: DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )
    name: str | None = pydantic.Field(
        default=None, description="New name of the device."
    )


class IssueDeviceTokenAction(pydantic.BaseModel):
    """Issue a JWT for a device with user-defined claims.

    **Note: Only use this action for integration with external systems.**"""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    device_id: DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )
    valid_for_secs: int | None = pydantic.Field(
        default=None,
        description="Token validity duration in seconds.",
        validation_alias="validForSecs",
        serialization_alias="validForSecs",
    )
    claims: _schema_json.JsonValue | None = pydantic.Field(
        default=None, description="Additional user-defined claims."
    )


class IssueDeviceTokenOutput(pydantic.BaseModel):
    """Output of issuing a JWT for a device."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    jwt: _schema_jwt.Jwt = pydantic.Field(description="Issued JWT.")


class ValidateDeviceTokenAction(pydantic.BaseModel):
    """Validate a device JWT.

    **Note: Only use this action for integration with external systems.**"""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    jwt: _schema_jwt.Jwt = pydantic.Field(description="JWT to validate.")


class ValidateDeviceTokenSuccess(pydantic.BaseModel):
    """Successful validation of a device JWT."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    device_id: DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )
    claims: _schema_json.JsonValue = pydantic.Field(description="User-defined claims.")


class AddDeviceCertificateAction(pydantic.BaseModel):
    """Add a device certificate."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    device_id: DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )
    fingerprint: CertificateFingerprint = pydantic.Field(
        description="Fingerprint of the certificate."
    )
    status: DeviceCertificateStatus | None = pydantic.Field(
        default=None,
        description="Initial status of the certificate.\n\nDefaults to `Pending`.",
    )


class AddDeviceCertificateOutput(pydantic.BaseModel):
    """Output of adding a device certificate."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    certificate_id: DeviceCertificateId = pydantic.Field(
        description="ID of the certificate.",
        validation_alias="certificateId",
        serialization_alias="certificateId",
    )


class DeleteDeviceCertificateAction(pydantic.BaseModel):
    """Delete a device certificate."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    certificate_id: DeviceCertificateId = pydantic.Field(
        description="ID of the certificate.",
        validation_alias="certificateId",
        serialization_alias="certificateId",
    )


class SetDeviceCertificateStatusAction(pydantic.BaseModel):
    """Set the status of a device certificate."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    certificate_id: DeviceCertificateId = pydantic.Field(
        description="ID of the certificate.",
        validation_alias="certificateId",
        serialization_alias="certificateId",
    )
    status: DeviceCertificateStatus = pydantic.Field(
        description="New status of the certificate."
    )


class RegisterDeviceConnectionAction(pydantic.BaseModel):
    """Register a connection of a device to a cluster node."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    device_id: DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )
    node_id: _schema_cluster.ClusterNodeId = pydantic.Field(
        description="ID of the cluster node.",
        validation_alias="nodeId",
        serialization_alias="nodeId",
    )
    connection_id: DeviceConnectionId = pydantic.Field(
        description="Pre-generated ID of the connection.",
        validation_alias="connectionId",
        serialization_alias="connectionId",
    )


class RegisterDeviceConnectionOutput(pydantic.BaseModel):
    """Output of registering a connection of a device to a cluster node."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    connection_id: DeviceConnectionId = pydantic.Field(
        description="ID of the connection.",
        validation_alias="connectionId",
        serialization_alias="connectionId",
    )


class UnregisterDeviceConnectionAction(pydantic.BaseModel):
    """Unregister a connection of a device to a cluster node."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    connection_id: DeviceConnectionId = pydantic.Field(
        description="ID of the connection.",
        validation_alias="connectionId",
        serialization_alias="connectionId",
    )
    end_reason: ConnectionEndReason = pydantic.Field(
        description="Reason for ending the connection.",
        validation_alias="endReason",
        serialization_alias="endReason",
    )


class QueryDeviceConnectionsAction(pydantic.BaseModel):
    """Query the connection history of a device."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    device_id: DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )
    limit: int | None = pydantic.Field(
        default=None, description="Limit results (default 100)."
    )
    active_only: bool | None = pydantic.Field(
        default=None,
        description="Include only active connections.",
        validation_alias="activeOnly",
        serialization_alias="activeOnly",
    )


class QueryDeviceConnectionsOutput(pydantic.BaseModel):
    """Output of querying device connections."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    connections: list[DeviceConnectionLog] = pydantic.Field(
        description="List of connections."
    )


class IssueDeviceHttpProxyTokenAction(pydantic.BaseModel):
    """Issue a HTTP proxy JWT."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    device_id: DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )
    valid_for_secs: int | None = pydantic.Field(
        default=None,
        description="Token validity duration in seconds.",
        validation_alias="validForSecs",
        serialization_alias="validForSecs",
    )
    hostname: str | None = pydantic.Field(
        default=None,
        description="Hostname to accept requests for.\n\nDefaults to a device-specific pseudo-random subdomain of the instance domain.",
    )
    port: int | None = pydantic.Field(
        default=None, description="Device port to proxy to.\n\nDefaults to `80`."
    )
    redirect: str | None = pydantic.Field(
        default=None,
        description="Redirect URL in case the token is expired or invalid.",
    )


class IssueDeviceHttpProxyTokenOutput(pydantic.BaseModel):
    """Output of issuing a HTTP proxy JWT."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    jwt: _schema_jwt.Jwt = pydantic.Field(description="JWT proxy token.")
    url: str = pydantic.Field(description="Proxy URL.")


class ValidateDeviceHttpProxyTokenAction(pydantic.BaseModel):
    """Validate a HTTP proxy JWT."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    jwt: _schema_jwt.Jwt = pydantic.Field(description="JWT to validate.")


class ValidateDeviceHttpProxyTokenInvalid(pydantic.BaseModel):
    """Validation of a HTTP proxy JWT failed."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    redirect: str | None = pydantic.Field(
        default=None, description="URL to redirect to."
    )


class ValidateDeviceHttpProxyTokenSuccess(pydantic.BaseModel):
    """Successful validation of a HTTP proxy JWT."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    device_id: DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )
    hostname: str | None = pydantic.Field(
        default=None, description="Hostname to accept requests for."
    )
    port: int | None = pydantic.Field(
        default=None, description="Device port to proxy to."
    )


class PublishDeviceEventsAction(pydantic.BaseModel):
    """Publish device events."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    device_id: DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )
    events: list[DeviceEvent] = pydantic.Field(description="Events to push.")


class QueryDeviceEventsAction(pydantic.BaseModel):
    """Query device events."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    device_id: DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )
    limit: int | None = pydantic.Field(
        default=None,
        description="Limit the number of events to return.\n\nDefault to `100`.",
    )


class QueryDeviceEventsOutput(pydantic.BaseModel):
    """Output of querying device events."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    events: list[DeviceEvent] = pydantic.Field(description="List of events.")


class DeviceEvent(pydantic.BaseModel):
    """Event emitted by a device."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    event_id: DeviceEventId = pydantic.Field(
        description="ID of the event.",
        validation_alias="eventId",
        serialization_alias="eventId",
    )
    category: str | None = pydantic.Field(
        default=None,
        description="Event category (optional, low-cardinality category of the event).",
    )
    severity: DeviceEventSeverity = pydantic.Field(description="Severity of the event.")
    body: _schema_json.JsonValue = pydantic.Field(description="Event body.")
    attributes: dict[str, _schema_json.JsonValue] = pydantic.Field(
        description="Event attributes."
    )
    emitted_at: _schema_datetime.Timestamp = pydantic.Field(
        description="Timestamp when the event was emitted.",
        validation_alias="emittedAt",
        serialization_alias="emittedAt",
    )
    received_at: _schema_datetime.Timestamp | None = pydantic.Field(
        default=None,
        description="Timestamp when the event was received.",
        validation_alias="receivedAt",
        serialization_alias="receivedAt",
    )


class SetDevicePropertyAction(pydantic.BaseModel):
    """Set a property of a device."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    device_id: DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )
    name: str = pydantic.Field(description="Name of the property.")
    value: _schema_json.JsonValue = pydantic.Field(description="Value of the property.")
    protected: bool | None = pydantic.Field(
        default=None, description="Indicates whether the property should be protected."
    )
    expected_version: int | None = pydantic.Field(
        default=None,
        description="If set, the property is only updated when its current version matches\nthis value (compare-and-swap). Returns `VersionConflict` when the\nversion does not match, or `Deleted` when the property no longer exists.",
        validation_alias="expectedVersion",
        serialization_alias="expectedVersion",
    )


class SetDevicePropertyVersionConflict(pydantic.BaseModel):
    """Details of a version conflict when setting a device property."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    current_version: int = pydantic.Field(
        description="The current version of the property.",
        validation_alias="currentVersion",
        serialization_alias="currentVersion",
    )


class GetDevicePropertyAction(pydantic.BaseModel):
    """Get a property of a device."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    device_id: DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )
    name: str = pydantic.Field(description="Name of the property.")


class RemoveDevicePropertyAction(pydantic.BaseModel):
    """Remove a property from a device."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    device_id: DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )
    name: str = pydantic.Field(description="Name of the property.")


class QueryDevicePropertiesAction(pydantic.BaseModel):
    """Query the properties of a device."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    device_id: DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )


class QueryDevicePropertiesOutput(pydantic.BaseModel):
    """Output of querying the properties of a device."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    properties: dict[str, DeviceProperty] = pydantic.Field(
        description="List of properties."
    )


class DeviceProperty(pydantic.BaseModel):
    """Device property."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    name: str = pydantic.Field(description="Name of the property.")
    value: _schema_json.JsonValue = pydantic.Field(description="Value of the property.")
    protected: bool = pydantic.Field(
        description="Indicates whether the property is protected."
    )
    version: int = pydantic.Field(
        description="Incremental version number, incremented on each update."
    )
    last_updated: _schema_datetime.Timestamp = pydantic.Field(
        description="Last time the property was updated.",
        validation_alias="lastUpdated",
        serialization_alias="lastUpdated",
    )


class QueryDeviceAuditLogAction(pydantic.BaseModel):
    """Query the audit log of a device."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    device_id: DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )


class QueryDeviceAuditLogOutput(pydantic.BaseModel):
    """Output of querying the audit log of a device."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    events: list[_schema_audit.AuditLogEvent] = pydantic.Field(
        description="List of audit log events."
    )


class QueryDeviceCommandsAction(pydantic.BaseModel):
    """Query the on-demand commands supported by a device."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    device_id: DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )


class QueryDeviceCommandsOutput(pydantic.BaseModel):
    """Output of querying device commands."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    manifest: _schema_properties.DeviceCommandManifest = pydantic.Field(
        description="Command manifest."
    )


class DeviceCommandInvokeData(pydantic.BaseModel):
    """Command invocation parameters."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    command: str = pydantic.Field(description="Command name.")
    input: _schema_json.JsonValue = pydantic.Field(description="Command input.")
    stream_log: bool | None = pydantic.Field(
        default=None,
        description="Stream log output back to the hub during execution (defaults to false).",
        validation_alias="streamLog",
        serialization_alias="streamLog",
    )
    timeout_secs: int | None = pydantic.Field(
        default=None,
        description="Timeout in seconds.",
        validation_alias="timeoutSecs",
        serialization_alias="timeoutSecs",
    )


class DeviceCommandLogData(pydantic.BaseModel):
    """Log data."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    lines: list[str] = pydantic.Field(
        description="Lines of diagnostic output from the command."
    )


class DeviceCommandDoneData(pydantic.BaseModel):
    """Command completion."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    status: DeviceCommandStatus = pydantic.Field(description="Completion status.")
    output: _schema_json.JsonValue | None = pydantic.Field(
        default=None, description="Command output."
    )
    error: str | None = pydantic.Field(
        default=None, description="Error message (present on failure)."
    )
    log_tail: list[str] = pydantic.Field(
        description="Last lines of the command's diagnostic log output.",
        validation_alias="logTail",
        serialization_alias="logTail",
    )
    duration_ms: int = pydantic.Field(
        description="Execution duration in milliseconds.",
        validation_alias="durationMs",
        serialization_alias="durationMs",
    )


class DeviceStatus_Healthy(pydantic.RootModel[Literal["healthy"]]):
    pass


class DeviceStatus_Warning(pydantic.RootModel[Literal["warning"]]):
    pass


class DeviceStatus_Error(pydantic.RootModel[Literal["error"]]):
    pass


class DeviceStatus_Offline(pydantic.RootModel[Literal["offline"]]):
    pass


# Combined device status (connection + health).
type DeviceStatus = (
    DeviceStatus_Healthy
    | DeviceStatus_Warning
    | DeviceStatus_Error
    | DeviceStatus_Offline
)


class DeviceCertificateStatus_Pending(pydantic.RootModel[Literal["Pending"]]):
    pass


class DeviceCertificateStatus_Active(pydantic.RootModel[Literal["Active"]]):
    pass


class DeviceCertificateStatus_Rejected(pydantic.RootModel[Literal["Rejected"]]):
    pass


class DeviceCertificateStatus_Revoked(pydantic.RootModel[Literal["Revoked"]]):
    pass


class DeviceCertificateStatus_Conflict(pydantic.RootModel[Literal["Conflict"]]):
    pass


# Status of a device certificate.
type DeviceCertificateStatus = (
    DeviceCertificateStatus_Pending
    | DeviceCertificateStatus_Active
    | DeviceCertificateStatus_Rejected
    | DeviceCertificateStatus_Revoked
    | DeviceCertificateStatus_Conflict
)


class ConnectionEndReason_Unknown(pydantic.RootModel[Literal["Unknown"]]):
    pass


class ConnectionEndReason_Disconnected(pydantic.RootModel[Literal["Disconnected"]]):
    pass


class ConnectionEndReason_NodeCrashed(pydantic.RootModel[Literal["NodeCrashed"]]):
    pass


class ConnectionEndReason_ServerShutdown(pydantic.RootModel[Literal["ServerShutdown"]]):
    pass


# Reason why a device connection ended.
type ConnectionEndReason = (
    ConnectionEndReason_Unknown
    | ConnectionEndReason_Disconnected
    | ConnectionEndReason_NodeCrashed
    | ConnectionEndReason_ServerShutdown
)


class ValidateDeviceTokenOutput_Invalid(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    result: Literal["Invalid"] = "Invalid"


class ValidateDeviceTokenOutput_Valid(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    result: Literal["Valid"] = "Valid"
    device_id: DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )
    claims: _schema_json.JsonValue = pydantic.Field(description="User-defined claims.")

    def payload(self) -> "ValidateDeviceTokenSuccess":
        return ValidateDeviceTokenSuccess(device_id=self.device_id, claims=self.claims)


# Output of validating a device JWT.
type ValidateDeviceTokenOutput = Annotated[
    ValidateDeviceTokenOutput_Invalid | ValidateDeviceTokenOutput_Valid,
    pydantic.Discriminator("result"),
]


class ValidateDeviceHttpProxyTokenOutput_Invalid(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    result: Literal["Invalid"] = "Invalid"
    redirect: str | None = pydantic.Field(
        default=None, description="URL to redirect to."
    )

    def payload(self) -> "ValidateDeviceHttpProxyTokenInvalid":
        return ValidateDeviceHttpProxyTokenInvalid(redirect=self.redirect)


class ValidateDeviceHttpProxyTokenOutput_Valid(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    result: Literal["Valid"] = "Valid"
    device_id: DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )
    hostname: str | None = pydantic.Field(
        default=None, description="Hostname to accept requests for."
    )
    port: int | None = pydantic.Field(
        default=None, description="Device port to proxy to."
    )

    def payload(self) -> "ValidateDeviceHttpProxyTokenSuccess":
        return ValidateDeviceHttpProxyTokenSuccess(
            device_id=self.device_id, hostname=self.hostname, port=self.port
        )


# Output of validating a HTTP proxy JWT.
type ValidateDeviceHttpProxyTokenOutput = Annotated[
    ValidateDeviceHttpProxyTokenOutput_Invalid
    | ValidateDeviceHttpProxyTokenOutput_Valid,
    pydantic.Discriminator("result"),
]


class DeviceEventSeverity_Trace(pydantic.RootModel[Literal["Trace"]]):
    pass


class DeviceEventSeverity_Debug(pydantic.RootModel[Literal["Debug"]]):
    pass


class DeviceEventSeverity_Info(pydantic.RootModel[Literal["Info"]]):
    pass


class DeviceEventSeverity_Warning(pydantic.RootModel[Literal["Warning"]]):
    pass


class DeviceEventSeverity_Error(pydantic.RootModel[Literal["Error"]]):
    pass


class DeviceEventSeverity_Critical(pydantic.RootModel[Literal["Critical"]]):
    pass


# Severity of a device event.
type DeviceEventSeverity = (
    DeviceEventSeverity_Trace
    | DeviceEventSeverity_Debug
    | DeviceEventSeverity_Info
    | DeviceEventSeverity_Warning
    | DeviceEventSeverity_Error
    | DeviceEventSeverity_Critical
)


class SetDevicePropertyOutput_Set(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    result: Literal["Set"] = "Set"


class SetDevicePropertyOutput_VersionConflict(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    result: Literal["VersionConflict"] = "VersionConflict"
    current_version: int = pydantic.Field(
        description="The current version of the property.",
        validation_alias="currentVersion",
        serialization_alias="currentVersion",
    )

    def payload(self) -> "SetDevicePropertyVersionConflict":
        return SetDevicePropertyVersionConflict(current_version=self.current_version)


class SetDevicePropertyOutput_Deleted(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    result: Literal["Deleted"] = "Deleted"


# Output of setting a device property.
type SetDevicePropertyOutput = Annotated[
    SetDevicePropertyOutput_Set
    | SetDevicePropertyOutput_VersionConflict
    | SetDevicePropertyOutput_Deleted,
    pydantic.Discriminator("result"),
]


class GetDevicePropertyOutput_NotFound(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    result: Literal["NotFound"] = "NotFound"


class GetDevicePropertyOutput_Found(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    result: Literal["Found"] = "Found"
    name: str = pydantic.Field(description="Name of the property.")
    value: _schema_json.JsonValue = pydantic.Field(description="Value of the property.")
    protected: bool = pydantic.Field(
        description="Indicates whether the property is protected."
    )
    version: int = pydantic.Field(
        description="Incremental version number, incremented on each update."
    )
    last_updated: _schema_datetime.Timestamp = pydantic.Field(
        description="Last time the property was updated.",
        validation_alias="lastUpdated",
        serialization_alias="lastUpdated",
    )

    def payload(self) -> "DeviceProperty":
        return DeviceProperty(
            name=self.name,
            value=self.value,
            protected=self.protected,
            version=self.version,
            last_updated=self.last_updated,
        )


# Output of getting a property of a device.
type GetDevicePropertyOutput = Annotated[
    GetDevicePropertyOutput_NotFound | GetDevicePropertyOutput_Found,
    pydantic.Discriminator("result"),
]


class RemoveDevicePropertyOutput_NotFound(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    result: Literal["NotFound"] = "NotFound"


class RemoveDevicePropertyOutput_Removed(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    result: Literal["Removed"] = "Removed"


# Output of removing a property from a device.
type RemoveDevicePropertyOutput = Annotated[
    RemoveDevicePropertyOutput_NotFound | RemoveDevicePropertyOutput_Removed,
    pydantic.Discriminator("result"),
]


class DeviceCommandStatus_Ok(pydantic.RootModel[Literal["Ok"]]):
    pass


class DeviceCommandStatus_Error(pydantic.RootModel[Literal["Error"]]):
    pass


# Status of a device command invocation.
type DeviceCommandStatus = DeviceCommandStatus_Ok | DeviceCommandStatus_Error


class DeviceCommandHubFrame_Invoke(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    type: Literal["Invoke"] = "Invoke"
    command: str = pydantic.Field(description="Command name.")
    input: _schema_json.JsonValue = pydantic.Field(description="Command input.")
    stream_log: bool | None = pydantic.Field(
        default=None,
        description="Stream log output back to the hub during execution (defaults to false).",
        validation_alias="streamLog",
        serialization_alias="streamLog",
    )
    timeout_secs: int | None = pydantic.Field(
        default=None,
        description="Timeout in seconds.",
        validation_alias="timeoutSecs",
        serialization_alias="timeoutSecs",
    )

    def payload(self) -> "DeviceCommandInvokeData":
        return DeviceCommandInvokeData(
            command=self.command,
            input=self.input,
            stream_log=self.stream_log,
            timeout_secs=self.timeout_secs,
        )


# Hub-to-device frame.
type DeviceCommandHubFrame = DeviceCommandHubFrame_Invoke


class DeviceCommandDeviceFrame_Log(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    type: Literal["Log"] = "Log"
    lines: list[str] = pydantic.Field(
        description="Lines of diagnostic output from the command."
    )

    def payload(self) -> "DeviceCommandLogData":
        return DeviceCommandLogData(lines=self.lines)


class DeviceCommandDeviceFrame_Done(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    type: Literal["Done"] = "Done"
    status: DeviceCommandStatus = pydantic.Field(description="Completion status.")
    output: _schema_json.JsonValue | None = pydantic.Field(
        default=None, description="Command output."
    )
    error: str | None = pydantic.Field(
        default=None, description="Error message (present on failure)."
    )
    log_tail: list[str] = pydantic.Field(
        description="Last lines of the command's diagnostic log output.",
        validation_alias="logTail",
        serialization_alias="logTail",
    )
    duration_ms: int = pydantic.Field(
        description="Execution duration in milliseconds.",
        validation_alias="durationMs",
        serialization_alias="durationMs",
    )

    def payload(self) -> "DeviceCommandDoneData":
        return DeviceCommandDoneData(
            status=self.status,
            output=self.output,
            error=self.error,
            log_tail=self.log_tail,
            duration_ms=self.duration_ms,
        )


# Device-to-hub frame.
type DeviceCommandDeviceFrame = Annotated[
    DeviceCommandDeviceFrame_Log | DeviceCommandDeviceFrame_Done,
    pydantic.Discriminator("type"),
]
