# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import Annotated, Literal, TYPE_CHECKING, Union  # noqa: F401

import pydantic  # noqa: F401
import pydantic_core  # noqa: F401


class Digest(str):
    """A hash digest."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)
