# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import Annotated, Generic, Literal, TYPE_CHECKING, TypeVar, Union  # noqa: F401

import pydantic  # noqa: F401
import pydantic_core  # noqa: F401

T = TypeVar("T")


class ActionError(pydantic.BaseModel):
    """Action error."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    kind: ActionErrorKind
    message: str


class ActionErrorKind_Invalid(pydantic.RootModel[Literal["Invalid"]]):
    pass


class ActionErrorKind_Forbidden(pydantic.RootModel[Literal["Forbidden"]]):
    pass


class ActionErrorKind_Internal(pydantic.RootModel[Literal["Internal"]]):
    pass


class ActionErrorKind_RateLimited(pydantic.RootModel[Literal["RateLimited"]]):
    pass


# Kind of an action error.
type ActionErrorKind = (
    ActionErrorKind_Invalid
    | ActionErrorKind_Forbidden
    | ActionErrorKind_Internal
    | ActionErrorKind_RateLimited
)


class ActionResult_Ok(pydantic.BaseModel, Generic[T]):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Ok"] = "Ok"
    value: T


class ActionResult_Error(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Error"] = "Error"
    error: ActionError


# Action result.
type ActionResult[T] = Annotated[
    ActionResult_Ok[T] | ActionResult_Error, pydantic.Discriminator("result")
]
