# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import Annotated, Literal, TYPE_CHECKING, Union  # noqa: F401

import pydantic  # noqa: F401
import pydantic_core  # noqa: F401

if TYPE_CHECKING:
    from . import datetime as _schema_datetime  # noqa: F401
    from . import json as _schema_json  # noqa: F401
    from . import projects as _schema_projects  # noqa: F401


class SetFleetPropertyAction(pydantic.BaseModel):
    """Set a fleet property manually."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: _schema_projects.ProjectId = pydantic.Field(
        description="ID of the project.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )
    name: str = pydantic.Field(description="Name of the property.")
    value: _schema_json.JsonValue = pydantic.Field(description="Value of the property.")


class GetFleetPropertyAction(pydantic.BaseModel):
    """Get a fleet property by name."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: _schema_projects.ProjectId = pydantic.Field(
        description="ID of the project.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )
    name: str = pydantic.Field(description="Name of the property.")


class RemoveFleetPropertyAction(pydantic.BaseModel):
    """Remove a fleet property.

    Handles both manual and computed properties. For computed properties, the
    associated definition is removed as well."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: _schema_projects.ProjectId = pydantic.Field(
        description="ID of the project.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )
    name: str = pydantic.Field(description="Name of the property.")


class QueryFleetPropertiesAction(pydantic.BaseModel):
    """Query all fleet properties of a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: _schema_projects.ProjectId = pydantic.Field(
        description="ID of the project.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )


class QueryFleetPropertiesOutput(pydantic.BaseModel):
    """Output of querying fleet properties."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    properties: dict[str, FleetProperty] = pydantic.Field(
        description="Properties keyed by name."
    )


class FleetProperty(pydantic.BaseModel):
    """A fleet property."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    name: str = pydantic.Field(description="Name of the property.")
    value: _schema_json.JsonValue = pydantic.Field(description="Current value.")
    kind: FleetPropertyKind = pydantic.Field(
        description="How this property is managed."
    )
    version: int = pydantic.Field(
        description="Incremental version number, bumped on each update."
    )
    error: str | None = pydantic.Field(
        default=None, description="Error from the last computation attempt, if any."
    )
    last_updated: _schema_datetime.Timestamp = pydantic.Field(
        description="When the value was last updated.",
        validation_alias="lastUpdated",
        serialization_alias="lastUpdated",
    )


class DefineComputedFleetPropertyAction(pydantic.BaseModel):
    """Define a computed fleet property."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: _schema_projects.ProjectId = pydantic.Field(
        description="ID of the project.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )
    name: str = pydantic.Field(description="Name of the property.")
    input_properties: list[str] = pydantic.Field(
        description="Device property names fed into the strategy's map function.",
        validation_alias="inputProperties",
        serialization_alias="inputProperties",
    )
    strategy: str = pydantic.Field(description="Name of the computation strategy.")
    config: _schema_json.JsonValue | None = pydantic.Field(
        default=None, description="Strategy-specific configuration."
    )


class QueryComputedFleetPropertyDefinitionsAction(pydantic.BaseModel):
    """Query computed fleet property definitions for a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: _schema_projects.ProjectId = pydantic.Field(
        description="ID of the project.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )


class QueryComputedFleetPropertyDefinitionsOutput(pydantic.BaseModel):
    """Output of querying computed fleet property definitions."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    definitions: list[ComputedFleetPropertyDefinition] = pydantic.Field(
        description="List of definitions."
    )


class ComputedFleetPropertyDefinition(pydantic.BaseModel):
    """A computed fleet property definition."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    name: str = pydantic.Field(description="Name of the property.")
    input_properties: list[str] = pydantic.Field(
        description="Device property names fed into the strategy's map function.",
        validation_alias="inputProperties",
        serialization_alias="inputProperties",
    )
    strategy: str = pydantic.Field(description="Name of the computation strategy.")
    config: _schema_json.JsonValue = pydantic.Field(
        description="Strategy-specific configuration."
    )
    created_at: _schema_datetime.Timestamp = pydantic.Field(
        description="When the definition was created.",
        validation_alias="createdAt",
        serialization_alias="createdAt",
    )


class GetFleetPropertyOutput_NotFound(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["NotFound"] = "NotFound"


class GetFleetPropertyOutput_Found(FleetProperty):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Found"] = "Found"


# Output of getting a fleet property.
type GetFleetPropertyOutput = Annotated[
    GetFleetPropertyOutput_NotFound | GetFleetPropertyOutput_Found,
    pydantic.Discriminator("result"),
]


class RemoveFleetPropertyOutput_NotFound(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["NotFound"] = "NotFound"


class RemoveFleetPropertyOutput_Removed(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Removed"] = "Removed"


# Output of removing a fleet property.
type RemoveFleetPropertyOutput = Annotated[
    RemoveFleetPropertyOutput_NotFound | RemoveFleetPropertyOutput_Removed,
    pydantic.Discriminator("result"),
]


class FleetPropertyKind_Manual(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    kind: Literal["Manual"] = "Manual"


class FleetPropertyKind_Computed(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    kind: Literal["Computed"] = "Computed"


class FleetPropertyKind_Builtin(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    kind: Literal["Builtin"] = "Builtin"


# How a fleet property is managed.
type FleetPropertyKind = Annotated[
    FleetPropertyKind_Manual | FleetPropertyKind_Computed | FleetPropertyKind_Builtin,
    pydantic.Discriminator("kind"),
]
