# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import Annotated, Literal, TYPE_CHECKING, Union  # noqa: F401

import pydantic  # noqa: F401
import pydantic_core  # noqa: F401

if TYPE_CHECKING:
    from . import json  # noqa: F401


class GetInstanceStatisticsAction(pydantic.BaseModel):
    """Get instance statistics."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)


class GetInstanceStatisticsOutput(pydantic.BaseModel):
    """Instance statistics."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    users: int = pydantic.Field(description="Number of users.")
    projects: int = pydantic.Field(description="Number of projects.")
    devices: int = pydantic.Field(description="Number of devices.")


class GetInstanceSettingsRawAction(pydantic.BaseModel):
    """Get the settings of the instance."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)


class GetInstanceSettingsRawOutput(pydantic.BaseModel):
    """Settings of the instance."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    settings: dict[str, json.JsonValue] = pydantic.Field(
        description="Settings of the instance."
    )


class SetInstanceSettingRawAction(pydantic.BaseModel):
    """Set a setting of the instance."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    key: str = pydantic.Field(description="Name of the setting.")
    value: json.JsonValue = pydantic.Field(description="Value of the setting.")
