# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import Annotated, Literal, TYPE_CHECKING, Union  # noqa: F401

import pydantic  # noqa: F401
import pydantic_core  # noqa: F401

if TYPE_CHECKING:
    from . import datetime  # noqa: F401


class JobId(str):
    """Unique ID of a job."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class Job(pydantic.BaseModel):
    """Job."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    job_id: JobId = pydantic.Field(
        validation_alias="jobId", serialization_alias="jobId"
    )
    status: JobStatus
    job: str
    queued: bool
    attempts: int
    retry_limit: int | None = pydantic.Field(
        default=None, validation_alias="retryLimit", serialization_alias="retryLimit"
    )
    retry_delay: int = pydantic.Field(
        validation_alias="retryDelay", serialization_alias="retryDelay"
    )
    timeout: int
    created_at: datetime.Timestamp = pydantic.Field(
        validation_alias="createdAt", serialization_alias="createdAt"
    )
    finished_at: datetime.Timestamp | None = pydantic.Field(
        default=None, validation_alias="finishedAt", serialization_alias="finishedAt"
    )


class QueryJobsAction(pydantic.BaseModel):
    """Query the jobs of the instance."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)


class QueryJobsOutput(pydantic.BaseModel):
    """Output of querying the jobs of the instance."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    jobs: list[Job]


class JobStatus_Pending(pydantic.RootModel[Literal["Pending"]]):
    pass


class JobStatus_Completed(pydantic.RootModel[Literal["Completed"]]):
    pass


class JobStatus_Failed(pydantic.RootModel[Literal["Failed"]]):
    pass


class JobStatus_Expired(pydantic.RootModel[Literal["Expired"]]):
    pass


class JobStatus_Cancelled(pydantic.RootModel[Literal["Cancelled"]]):
    pass


# Execution status of a job.
type JobStatus = (
    JobStatus_Pending
    | JobStatus_Completed
    | JobStatus_Failed
    | JobStatus_Expired
    | JobStatus_Cancelled
)
