# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import Annotated, Literal, TYPE_CHECKING, Union  # noqa: F401

import pydantic  # noqa: F401
import pydantic_core  # noqa: F401

if TYPE_CHECKING:
    from . import audit as _schema_audit  # noqa: F401
    from . import projects as _schema_projects  # noqa: F401
    from . import repositories as _schema_repositories  # noqa: F401
    from . import users as _schema_users  # noqa: F401


class OrganizationId(str):
    """Unique ID of an organization"""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class OrganizationInvitationId(str):
    """Unique ID of an invitation to an organization."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class OrganizationApiTokenId(str):
    """Unique ID of an organization API token."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class QueryOrganizationsAction(pydantic.BaseModel):
    """Query the organizations of the instance."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)


class QueryOrganizationsOutput(pydantic.BaseModel):
    """Output of querying the organizations of the instance."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organizations: list[QueryOrganizationsItem] = pydantic.Field(
        description="List of organizations."
    )


class QueryOrganizationsItem(pydantic.BaseModel):
    """Organization item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: OrganizationId = pydantic.Field(
        description="ID of the organization.",
        validation_alias="organizationId",
        serialization_alias="organizationId",
    )
    name: str = pydantic.Field(description="Name of the organization.")


class QueryOrganizationMembersAction(pydantic.BaseModel):
    """Query the members of an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: OrganizationId = pydantic.Field(
        description="ID of the organization.",
        validation_alias="organizationId",
        serialization_alias="organizationId",
    )


class QueryOrganizationMembersOutput(pydantic.BaseModel):
    """Output of querying the members of an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    members: list[QueryOrganizationMembersItem] = pydantic.Field(
        description="List of members."
    )


class QueryOrganizationMembersItem(pydantic.BaseModel):
    """Member item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    user_id: _schema_users.UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )
    display_name: str | None = pydantic.Field(
        default=None,
        description="Name of the user.",
        validation_alias="displayName",
        serialization_alias="displayName",
    )
    email: str = pydantic.Field(description="Email of the user.")
    is_admin: bool = pydantic.Field(
        description="Whether the user is an administrator of the organization.",
        validation_alias="isAdmin",
        serialization_alias="isAdmin",
    )


class QueryOrganizationProjectsAction(pydantic.BaseModel):
    """Query the projects of an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: OrganizationId = pydantic.Field(
        description="ID of the organization.",
        validation_alias="organizationId",
        serialization_alias="organizationId",
    )


class QueryOrganizationProjectsOutput(pydantic.BaseModel):
    """Output of querying the projects of an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    projects: list[QueryOrganizationProjectsItem] = pydantic.Field(
        description="List of projects."
    )


class QueryOrganizationProjectsItem(pydantic.BaseModel):
    """Project item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: _schema_projects.ProjectId = pydantic.Field(
        description="ID of the project.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )
    name: str = pydantic.Field(description="Name of the project.")


class QueryOrganizationRepositoriesAction(pydantic.BaseModel):
    """Query the repositories of an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: OrganizationId = pydantic.Field(
        description="ID of the organization.",
        validation_alias="organizationId",
        serialization_alias="organizationId",
    )


class QueryOrganizationRepositoriesOutput(pydantic.BaseModel):
    """Output of querying the repositories of an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repositories: list[QueryOrganizationRepositoriesItem] = pydantic.Field(
        description="List of repositories."
    )


class QueryOrganizationRepositoriesItem(pydantic.BaseModel):
    """Repository item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository_id: _schema_repositories.RepositoryId = pydantic.Field(
        description="ID of the repository.",
        validation_alias="repositoryId",
        serialization_alias="repositoryId",
    )
    public_name: str = pydantic.Field(
        description="Public name of the repository.",
        validation_alias="publicName",
        serialization_alias="publicName",
    )
    display_name: str | None = pydantic.Field(
        default=None,
        description="Display name of the repository (if any).",
        validation_alias="displayName",
        serialization_alias="displayName",
    )


class QueryOrganizationInvitationsAction(pydantic.BaseModel):
    """Query the invitations of an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: OrganizationId = pydantic.Field(
        description="ID of the organization.",
        validation_alias="organizationId",
        serialization_alias="organizationId",
    )


class QueryOrganizationInvitationsOutput(pydantic.BaseModel):
    """Output of querying the invitations of an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    invitations: list[QueryOrganizationInvitationsItem] = pydantic.Field(
        description="List of outstanding invitations."
    )


class QueryOrganizationInvitationsItem(pydantic.BaseModel):
    """Organization invitation item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    invitation_id: OrganizationInvitationId = pydantic.Field(
        description="ID of the invitation.",
        validation_alias="invitationId",
        serialization_alias="invitationId",
    )
    email: str = pydantic.Field(description="Email address of the invited user.")
    inviting_user_id: _schema_users.UserId | None = pydantic.Field(
        default=None,
        description="ID of the inviting user.",
        validation_alias="invitingUserId",
        serialization_alias="invitingUserId",
    )


class CreateOrganizationAction(pydantic.BaseModel):
    """Create an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    name: str = pydantic.Field(description="Name of the organization.")
    admins: list[_schema_users.UserId] | None = pydantic.Field(
        default=None, description="Admins of the organization."
    )
    requires_subscription: bool = pydantic.Field(
        description="Whether the organization requires a subscription.",
        validation_alias="requiresSubscription",
        serialization_alias="requiresSubscription",
    )


class CreateOrganizationOutput(pydantic.BaseModel):
    """Output of creating an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: OrganizationId = pydantic.Field(
        description="ID of the organization.",
        validation_alias="organizationId",
        serialization_alias="organizationId",
    )


class DeleteOrganizationAction(pydantic.BaseModel):
    """Delete an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: OrganizationId = pydantic.Field(
        description="ID of the organization.",
        validation_alias="organizationId",
        serialization_alias="organizationId",
    )


class AddOrganizationMemberAction(pydantic.BaseModel):
    """Add a user to an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: OrganizationId = pydantic.Field(
        description="ID of the organization.",
        validation_alias="organizationId",
        serialization_alias="organizationId",
    )
    user_id: _schema_users.UserId = pydantic.Field(
        description="ID of the user to add.",
        validation_alias="userId",
        serialization_alias="userId",
    )
    is_admin: bool | None = pydantic.Field(
        default=None,
        description="Whether the user should be an administrator of the organization.",
        validation_alias="isAdmin",
        serialization_alias="isAdmin",
    )


class RemoveOrganizationMemberAction(pydantic.BaseModel):
    """Remove a user from an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: OrganizationId = pydantic.Field(
        description="ID of the organization.",
        validation_alias="organizationId",
        serialization_alias="organizationId",
    )
    user_id: _schema_users.UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )


class SetOrganizationMemberIsAdminAction(pydantic.BaseModel):
    """Set whether the user is an administrator of the organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: OrganizationId = pydantic.Field(
        description="ID of the organization.",
        validation_alias="organizationId",
        serialization_alias="organizationId",
    )
    user_id: _schema_users.UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )
    is_admin: bool = pydantic.Field(
        description="Whether the user should be an administrator of the organization.",
        validation_alias="isAdmin",
        serialization_alias="isAdmin",
    )


class InviteOrganizationMemberAction(pydantic.BaseModel):
    """Invite a user to an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: OrganizationId = pydantic.Field(
        description="ID of the organization.",
        validation_alias="organizationId",
        serialization_alias="organizationId",
    )
    email: str = pydantic.Field(description="Email address of the user to invite.")


class InviteOrganizationMemberOutput(pydantic.BaseModel):
    """Output of inviting a user to an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    invitation_id: OrganizationInvitationId = pydantic.Field(
        description="ID of the invitation.",
        validation_alias="invitationId",
        serialization_alias="invitationId",
    )


class DeleteOrganizationInvitationAction(pydantic.BaseModel):
    """Delete an invitation to an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    invitation_id: OrganizationInvitationId = pydantic.Field(
        description="ID of the invitation.",
        validation_alias="invitationId",
        serialization_alias="invitationId",
    )


class QueryOrganizationAuditLogAction(pydantic.BaseModel):
    """Query the audit log of an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: OrganizationId = pydantic.Field(
        description="ID of the organization.",
        validation_alias="organizationId",
        serialization_alias="organizationId",
    )


class QueryOrganizationAuditLogOutput(pydantic.BaseModel):
    """Output of querying the audit log of an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    events: list[_schema_audit.AuditLogEvent] = pydantic.Field(
        description="List of audit log events."
    )
