# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import Annotated, Literal, TYPE_CHECKING, Union  # noqa: F401

import pydantic  # noqa: F401
import pydantic_core  # noqa: F401

if TYPE_CHECKING:
    from . import audit  # noqa: F401
    from . import projects  # noqa: F401
    from . import repositories  # noqa: F401
    from . import users  # noqa: F401


class OrganizationId(str):
    """Unique ID of an organization"""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class OrganizationInvitationId(str):
    """Unique ID of an invitation to an organization."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class OrganizationApiTokenId(str):
    """Unique ID of an organization API token."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class QueryOrganizationsAction(pydantic.BaseModel):
    """Query the organizations of the instance."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)


class QueryOrganizationsOutput(pydantic.BaseModel):
    """Output of querying the organizations of the instance."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organizations: list[QueryOrganizationsItem]


class QueryOrganizationsItem(pydantic.BaseModel):
    """Organization item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: OrganizationId = pydantic.Field(
        validation_alias="organizationId", serialization_alias="organizationId"
    )
    name: str


class QueryOrganizationMembersAction(pydantic.BaseModel):
    """Query the members of an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: OrganizationId = pydantic.Field(
        validation_alias="organizationId", serialization_alias="organizationId"
    )


class QueryOrganizationMembersOutput(pydantic.BaseModel):
    """Output of querying the members of an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    members: list[QueryOrganizationMembersItem]


class QueryOrganizationMembersItem(pydantic.BaseModel):
    """Member item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    user_id: users.UserId = pydantic.Field(
        validation_alias="userId", serialization_alias="userId"
    )
    display_name: str | None = pydantic.Field(
        default=None, validation_alias="displayName", serialization_alias="displayName"
    )
    email: str
    is_admin: bool = pydantic.Field(
        validation_alias="isAdmin", serialization_alias="isAdmin"
    )


class QueryOrganizationProjectsAction(pydantic.BaseModel):
    """Query the projects of an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: OrganizationId = pydantic.Field(
        validation_alias="organizationId", serialization_alias="organizationId"
    )


class QueryOrganizationProjectsOutput(pydantic.BaseModel):
    """Output of querying the projects of an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    projects: list[QueryOrganizationProjectsItem]


class QueryOrganizationProjectsItem(pydantic.BaseModel):
    """Project item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: projects.ProjectId = pydantic.Field(
        validation_alias="projectId", serialization_alias="projectId"
    )
    name: str


class QueryOrganizationRepositoriesAction(pydantic.BaseModel):
    """Query the repositories of an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: OrganizationId = pydantic.Field(
        validation_alias="organizationId", serialization_alias="organizationId"
    )


class QueryOrganizationRepositoriesOutput(pydantic.BaseModel):
    """Output of querying the repositories of an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repositories: list[QueryOrganizationRepositoriesItem]


class QueryOrganizationRepositoriesItem(pydantic.BaseModel):
    """Repository item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository_id: repositories.RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )
    public_name: str = pydantic.Field(
        validation_alias="publicName", serialization_alias="publicName"
    )
    display_name: str | None = pydantic.Field(
        default=None, validation_alias="displayName", serialization_alias="displayName"
    )


class QueryOrganizationInvitationsAction(pydantic.BaseModel):
    """Query the invitations of an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: OrganizationId = pydantic.Field(
        validation_alias="organizationId", serialization_alias="organizationId"
    )


class QueryOrganizationInvitationsOutput(pydantic.BaseModel):
    """Output of querying the invitations of an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    invitations: list[QueryOrganizationInvitationsItem]


class QueryOrganizationInvitationsItem(pydantic.BaseModel):
    """Organization invitation item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    invitation_id: OrganizationInvitationId = pydantic.Field(
        validation_alias="invitationId", serialization_alias="invitationId"
    )
    email: str
    inviting_user_id: users.UserId | None = pydantic.Field(
        default=None,
        validation_alias="invitingUserId",
        serialization_alias="invitingUserId",
    )


class CreateOrganizationAction(pydantic.BaseModel):
    """Create an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    name: str
    admins: list[users.UserId] | None = None
    requires_subscription: bool = pydantic.Field(
        validation_alias="requiresSubscription",
        serialization_alias="requiresSubscription",
    )


class CreateOrganizationOutput(pydantic.BaseModel):
    """Output of creating an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: OrganizationId = pydantic.Field(
        validation_alias="organizationId", serialization_alias="organizationId"
    )


class DeleteOrganizationAction(pydantic.BaseModel):
    """Delete an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: OrganizationId = pydantic.Field(
        validation_alias="organizationId", serialization_alias="organizationId"
    )


class AddOrganizationMemberAction(pydantic.BaseModel):
    """Add a user to an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: OrganizationId = pydantic.Field(
        validation_alias="organizationId", serialization_alias="organizationId"
    )
    user_id: users.UserId = pydantic.Field(
        validation_alias="userId", serialization_alias="userId"
    )
    is_admin: bool | None = pydantic.Field(
        default=None, validation_alias="isAdmin", serialization_alias="isAdmin"
    )


class RemoveOrganizationMemberAction(pydantic.BaseModel):
    """Remove a user from an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: OrganizationId = pydantic.Field(
        validation_alias="organizationId", serialization_alias="organizationId"
    )
    user_id: users.UserId = pydantic.Field(
        validation_alias="userId", serialization_alias="userId"
    )


class SetOrganizationMemberIsAdminAction(pydantic.BaseModel):
    """Set whether the user is an administrator of the organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: OrganizationId = pydantic.Field(
        validation_alias="organizationId", serialization_alias="organizationId"
    )
    user_id: users.UserId = pydantic.Field(
        validation_alias="userId", serialization_alias="userId"
    )
    is_admin: bool = pydantic.Field(
        validation_alias="isAdmin", serialization_alias="isAdmin"
    )


class InviteOrganizationMemberAction(pydantic.BaseModel):
    """Invite a user to an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: OrganizationId = pydantic.Field(
        validation_alias="organizationId", serialization_alias="organizationId"
    )
    email: str


class InviteOrganizationMemberOutput(pydantic.BaseModel):
    """Output of inviting a user to an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    invitation_id: OrganizationInvitationId = pydantic.Field(
        validation_alias="invitationId", serialization_alias="invitationId"
    )


class DeleteOrganizationInvitationAction(pydantic.BaseModel):
    """Delete an invitation to an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    invitation_id: OrganizationInvitationId = pydantic.Field(
        validation_alias="invitationId", serialization_alias="invitationId"
    )


class QueryOrganizationAuditLogAction(pydantic.BaseModel):
    """Query the audit log of an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: OrganizationId = pydantic.Field(
        validation_alias="organizationId", serialization_alias="organizationId"
    )


class QueryOrganizationAuditLogOutput(pydantic.BaseModel):
    """Output of querying the audit log of an organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    events: list[audit.AuditLogEvent]
