# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import Annotated, Literal, TYPE_CHECKING, Union  # noqa: F401

import pydantic  # noqa: F401
import pydantic_core  # noqa: F401


class Empty(pydantic.BaseModel):
    """Empty output."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)
