# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import Annotated, Literal, TYPE_CHECKING, Union  # noqa: F401

import pydantic  # noqa: F401
import pydantic_core  # noqa: F401

if TYPE_CHECKING:
    from . import audit  # noqa: F401
    from . import datetime  # noqa: F401
    from . import devices  # noqa: F401
    from . import organizations  # noqa: F401
    from . import repositories  # noqa: F401


class ProjectId(str):
    """Unique ID of a project."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class DeploymentTokenId(str):
    """Unique ID of a deployment token."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class DeploymentToken(str):
    """Deployment token."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class QueryProjectsAction(pydantic.BaseModel):
    """Query the projects of the instance."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)


class QueryProjectsOutput(pydantic.BaseModel):
    """Output of querying the projects of the instance."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    projects: list[QueryProjectsItem]


class QueryProjectsItem(pydantic.BaseModel):
    """Project item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        validation_alias="projectId", serialization_alias="projectId"
    )
    name: str


class GetProjectDetailsAction(pydantic.BaseModel):
    """Get information about a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        validation_alias="projectId", serialization_alias="projectId"
    )


class GetProjectDetailsOutput(pydantic.BaseModel):
    """Information about a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        validation_alias="projectId", serialization_alias="projectId"
    )
    name: str
    device_count: int = pydantic.Field(
        validation_alias="deviceCount", serialization_alias="deviceCount"
    )


class SetProjectNameAction(pydantic.BaseModel):
    """Set the name of a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        validation_alias="projectId", serialization_alias="projectId"
    )
    name: str


class CreateProjectAction(pydantic.BaseModel):
    """Create a new project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: organizations.OrganizationId = pydantic.Field(
        validation_alias="organizationId", serialization_alias="organizationId"
    )
    name: str


class CreateProjectSuccess(pydantic.BaseModel):
    """Project creation has been successful."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        validation_alias="projectId", serialization_alias="projectId"
    )


class DeleteProjectAction(pydantic.BaseModel):
    """Delete a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        validation_alias="projectId", serialization_alias="projectId"
    )


class QueryProjectDevicesAction(pydantic.BaseModel):
    """Query the devices of a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        validation_alias="projectId", serialization_alias="projectId"
    )


class QueryProjectDevicesOutput(pydantic.BaseModel):
    """Output of querying the devices of a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    devices: list[QueryProjectDevicesItem]


class QueryProjectDevicesItem(pydantic.BaseModel):
    """Device item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: devices.DeviceId = pydantic.Field(
        validation_alias="deviceId", serialization_alias="deviceId"
    )
    name: str | None = None
    first_seen: datetime.Timestamp = pydantic.Field(
        validation_alias="firstSeen", serialization_alias="firstSeen"
    )
    status: devices.DeviceStatus
    is_connected: bool = pydantic.Field(
        validation_alias="isConnected", serialization_alias="isConnected"
    )
    pending_certificates_count: int = pydantic.Field(
        validation_alias="pendingCertificatesCount",
        serialization_alias="pendingCertificatesCount",
    )
    last_connected_at: datetime.Timestamp | None = pydantic.Field(
        default=None,
        validation_alias="lastConnectedAt",
        serialization_alias="lastConnectedAt",
    )
    current_connection_duration_secs: int | None = pydantic.Field(
        default=None,
        validation_alias="currentConnectionDurationSecs",
        serialization_alias="currentConnectionDurationSecs",
    )


class QueryProjectDeploymentTokensAction(pydantic.BaseModel):
    """Query the deployment tokens of a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        validation_alias="projectId", serialization_alias="projectId"
    )


class QueryProjectDeploymentTokensOutput(pydantic.BaseModel):
    """Output of querying the deployment tokens of a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    tokens: list[QueryProjectDeploymentTokensItem]


class QueryProjectDeploymentTokensItem(pydantic.BaseModel):
    """Deployment token item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    token_id: DeploymentTokenId = pydantic.Field(
        validation_alias="tokenId", serialization_alias="tokenId"
    )
    created_at: datetime.Timestamp = pydantic.Field(
        validation_alias="createdAt", serialization_alias="createdAt"
    )
    name: str | None = None
    flags: DeploymentTokenFlags


class QueryProjectRepositoriesAction(pydantic.BaseModel):
    """Query repositories of a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        validation_alias="projectId", serialization_alias="projectId"
    )


class QueryProjectRepositoriesOutput(pydantic.BaseModel):
    """Output of querying the repositories of a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repositories: list[QueryProjectRepositoriesItem]


class QueryProjectRepositoriesItem(pydantic.BaseModel):
    """Repository item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository_id: repositories.RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )
    public_name: str = pydantic.Field(
        validation_alias="publicName", serialization_alias="publicName"
    )
    display_name: str | None = pydantic.Field(
        default=None, validation_alias="displayName", serialization_alias="displayName"
    )


class DeploymentTokenFlags(pydantic.BaseModel):
    """Flags for deployment tokens."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    auto_accept: bool | None = pydantic.Field(
        default=None, validation_alias="autoAccept", serialization_alias="autoAccept"
    )


class CreateDeploymentTokenAction(pydantic.BaseModel):
    """Create a deployment token."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        validation_alias="projectId", serialization_alias="projectId"
    )
    name: str
    flags: DeploymentTokenFlags | None = None


class CreateDeploymentTokenOutput(pydantic.BaseModel):
    """Output of creating a deployment token."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    token_id: DeploymentTokenId = pydantic.Field(
        validation_alias="tokenId", serialization_alias="tokenId"
    )
    token: DeploymentToken


class DeleteDeploymentTokenAction(pydantic.BaseModel):
    """Delete a deployment token."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    token_id: DeploymentTokenId = pydantic.Field(
        validation_alias="tokenId", serialization_alias="tokenId"
    )


class SetDeploymentTokenFlagsAction(pydantic.BaseModel):
    """Set the flags of a deployment token."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    token_id: DeploymentTokenId = pydantic.Field(
        validation_alias="tokenId", serialization_alias="tokenId"
    )
    flags: DeploymentTokenFlags


class QueryAuditLogEventsAction(pydantic.BaseModel):
    """Query the audit log of the project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        validation_alias="projectId", serialization_alias="projectId"
    )


class QueryAuditLogEventsOutput(pydantic.BaseModel):
    """Output of querying the audit log of the project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    events: list[audit.AuditLogEvent]


class AddProjectRepositoryAction(pydantic.BaseModel):
    """Add a repository to the project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        validation_alias="projectId", serialization_alias="projectId"
    )
    repository_id: repositories.RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )


class RemoveProjectRepositoryAction(pydantic.BaseModel):
    """Remove a repository from the project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        validation_alias="projectId", serialization_alias="projectId"
    )
    repository_id: repositories.RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )


class ProjectOtlpConfig(pydantic.BaseModel):
    """OTLP event forwarding configuration for a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    enabled: bool
    endpoint: str | None = None
    headers: dict[str, str]


class GetProjectOtlpConfigAction(pydantic.BaseModel):
    """Get the OTLP event forwarding configuration for a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        validation_alias="projectId", serialization_alias="projectId"
    )


class GetProjectOtlpConfigOutput(pydantic.BaseModel):
    """Output of getting the OTLP configuration for a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    config: ProjectOtlpConfig


class SetProjectOtlpConfigAction(pydantic.BaseModel):
    """Set the OTLP event forwarding configuration for a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        validation_alias="projectId", serialization_alias="projectId"
    )
    config: ProjectOtlpConfig


class CreateProjectOutput_Created(CreateProjectSuccess):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Created"] = "Created"


# Output of creating a project.
type CreateProjectOutput = CreateProjectOutput_Created
