# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import Annotated, Literal, TYPE_CHECKING, Union  # noqa: F401

import pydantic  # noqa: F401
import pydantic_core  # noqa: F401

if TYPE_CHECKING:
    from . import audit as _schema_audit  # noqa: F401
    from . import datetime as _schema_datetime  # noqa: F401
    from . import devices as _schema_devices  # noqa: F401
    from . import organizations as _schema_organizations  # noqa: F401
    from . import repositories as _schema_repositories  # noqa: F401


class ProjectId(str):
    """Unique ID of a project."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class DeploymentTokenId(str):
    """Unique ID of a deployment token."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class DeploymentToken(str):
    """Deployment token."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class QueryProjectsAction(pydantic.BaseModel):
    """Query the projects of the instance."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)


class QueryProjectsOutput(pydantic.BaseModel):
    """Output of querying the projects of the instance."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    projects: list[QueryProjectsItem] = pydantic.Field(description="List of projects.")


class QueryProjectsItem(pydantic.BaseModel):
    """Project item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        description="ID of the project.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )
    name: str = pydantic.Field(description="Name of the project.")


class GetProjectDetailsAction(pydantic.BaseModel):
    """Get information about a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        description="ID of the project.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )


class GetProjectDetailsOutput(pydantic.BaseModel):
    """Information about a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        description="ID of the project.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )
    name: str = pydantic.Field(description="Name of the project.")
    device_count: int = pydantic.Field(
        description="Number of devices in the project.",
        validation_alias="deviceCount",
        serialization_alias="deviceCount",
    )


class SetProjectNameAction(pydantic.BaseModel):
    """Set the name of a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        description="ID of the project.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )
    name: str = pydantic.Field(description="New name of the project.")


class CreateProjectAction(pydantic.BaseModel):
    """Create a new project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: _schema_organizations.OrganizationId = pydantic.Field(
        description="Organization to create the project in.",
        validation_alias="organizationId",
        serialization_alias="organizationId",
    )
    name: str = pydantic.Field(description="Name of the project.")


class CreateProjectSuccess(pydantic.BaseModel):
    """Project creation has been successful."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        description="ID of the project.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )


class DeleteProjectAction(pydantic.BaseModel):
    """Delete a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        description="ID of the project.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )


class QueryProjectDevicesAction(pydantic.BaseModel):
    """Query the devices of a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        description="ID of the project.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )


class QueryProjectDevicesOutput(pydantic.BaseModel):
    """Output of querying the devices of a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    devices: list[QueryProjectDevicesItem] = pydantic.Field(
        description="List of devices."
    )


class QueryProjectDevicesItem(pydantic.BaseModel):
    """Device item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    device_id: _schema_devices.DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )
    name: str | None = pydantic.Field(default=None, description="Name of the device.")
    first_seen: _schema_datetime.Timestamp = pydantic.Field(
        description="Timestamp when the device was first seen.",
        validation_alias="firstSeen",
        serialization_alias="firstSeen",
    )
    status: _schema_devices.DeviceStatus = pydantic.Field(
        description="Combined device status (connection + health)."
    )
    is_connected: bool = pydantic.Field(
        description="Indicates whether the device is online.",
        validation_alias="isConnected",
        serialization_alias="isConnected",
    )
    pending_certificates_count: int = pydantic.Field(
        description="Pending device certificates.",
        validation_alias="pendingCertificatesCount",
        serialization_alias="pendingCertificatesCount",
    )
    last_connected_at: _schema_datetime.Timestamp | None = pydantic.Field(
        default=None,
        description="Timestamp when the device was last connected (current or most recent connection).",
        validation_alias="lastConnectedAt",
        serialization_alias="lastConnectedAt",
    )
    current_connection_duration_secs: int | None = pydantic.Field(
        default=None,
        description="Duration of the current connection in seconds (null if not connected).",
        validation_alias="currentConnectionDurationSecs",
        serialization_alias="currentConnectionDurationSecs",
    )


class QueryProjectDeploymentTokensAction(pydantic.BaseModel):
    """Query the deployment tokens of a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        description="ID of the project.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )


class QueryProjectDeploymentTokensOutput(pydantic.BaseModel):
    """Output of querying the deployment tokens of a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    tokens: list[QueryProjectDeploymentTokensItem] = pydantic.Field(
        description="List of deployment tokens."
    )


class QueryProjectDeploymentTokensItem(pydantic.BaseModel):
    """Deployment token item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    token_id: DeploymentTokenId = pydantic.Field(
        description="ID of the token.",
        validation_alias="tokenId",
        serialization_alias="tokenId",
    )
    created_at: _schema_datetime.Timestamp = pydantic.Field(
        description="Creation date of the token.",
        validation_alias="createdAt",
        serialization_alias="createdAt",
    )
    name: str | None = pydantic.Field(default=None, description="Name of the token.")
    flags: DeploymentTokenFlags = pydantic.Field(description="Flags.")


class QueryProjectRepositoriesAction(pydantic.BaseModel):
    """Query repositories of a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        description="ID of the project.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )


class QueryProjectRepositoriesOutput(pydantic.BaseModel):
    """Output of querying the repositories of a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repositories: list[QueryProjectRepositoriesItem] = pydantic.Field(
        description="List of repositories."
    )


class QueryProjectRepositoriesItem(pydantic.BaseModel):
    """Repository item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository_id: _schema_repositories.RepositoryId = pydantic.Field(
        description="ID of the repository.",
        validation_alias="repositoryId",
        serialization_alias="repositoryId",
    )
    public_name: str = pydantic.Field(
        description="Public name of the repository.",
        validation_alias="publicName",
        serialization_alias="publicName",
    )
    display_name: str | None = pydantic.Field(
        default=None,
        description="Display name of the repository (if any).",
        validation_alias="displayName",
        serialization_alias="displayName",
    )


class DeploymentTokenFlags(pydantic.BaseModel):
    """Flags for deployment tokens."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    auto_accept: bool | None = pydantic.Field(
        default=None,
        description="Whether to automatically accept new devices.",
        validation_alias="autoAccept",
        serialization_alias="autoAccept",
    )


class CreateDeploymentTokenAction(pydantic.BaseModel):
    """Create a deployment token."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        description="ID of the project.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )
    name: str = pydantic.Field(description="Name of the token.")
    flags: DeploymentTokenFlags | None = pydantic.Field(
        default=None, description="Flags."
    )


class CreateDeploymentTokenOutput(pydantic.BaseModel):
    """Output of creating a deployment token."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    token_id: DeploymentTokenId = pydantic.Field(
        description="ID of the token.",
        validation_alias="tokenId",
        serialization_alias="tokenId",
    )
    token: DeploymentToken = pydantic.Field(description="Token.")


class DeleteDeploymentTokenAction(pydantic.BaseModel):
    """Delete a deployment token."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    token_id: DeploymentTokenId = pydantic.Field(
        description="ID of the token.",
        validation_alias="tokenId",
        serialization_alias="tokenId",
    )


class SetDeploymentTokenFlagsAction(pydantic.BaseModel):
    """Set the flags of a deployment token."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    token_id: DeploymentTokenId = pydantic.Field(
        description="ID of the token.",
        validation_alias="tokenId",
        serialization_alias="tokenId",
    )
    flags: DeploymentTokenFlags = pydantic.Field(description="Flags.")


class QueryAuditLogEventsAction(pydantic.BaseModel):
    """Query the audit log of the project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        description="ID of the project.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )


class QueryAuditLogEventsOutput(pydantic.BaseModel):
    """Output of querying the audit log of the project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    events: list[_schema_audit.AuditLogEvent] = pydantic.Field(
        description="List of audit log events."
    )


class AddProjectRepositoryAction(pydantic.BaseModel):
    """Add a repository to the project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        description="ID of the project.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )
    repository_id: _schema_repositories.RepositoryId = pydantic.Field(
        description="ID of the repository.",
        validation_alias="repositoryId",
        serialization_alias="repositoryId",
    )


class RemoveProjectRepositoryAction(pydantic.BaseModel):
    """Remove a repository from the project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        description="ID of the project.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )
    repository_id: _schema_repositories.RepositoryId = pydantic.Field(
        description="ID of the repository.",
        validation_alias="repositoryId",
        serialization_alias="repositoryId",
    )


class ProjectOtlpConfig(pydantic.BaseModel):
    """OTLP event forwarding configuration for a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    enabled: bool = pydantic.Field(description="Whether OTLP forwarding is enabled.")
    endpoint: str | None = pydantic.Field(
        default=None,
        description="OTLP endpoint URL (e.g., https://otel-collector.example.com/v1/logs).",
    )
    headers: dict[str, str] = pydantic.Field(
        description="HTTP headers to include with OTLP requests (e.g., for authentication).\nValues are masked when read back."
    )


class GetProjectOtlpConfigAction(pydantic.BaseModel):
    """Get the OTLP event forwarding configuration for a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        description="ID of the project.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )


class GetProjectOtlpConfigOutput(pydantic.BaseModel):
    """Output of getting the OTLP configuration for a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    config: ProjectOtlpConfig = pydantic.Field(description="OTLP configuration.")


class SetProjectOtlpConfigAction(pydantic.BaseModel):
    """Set the OTLP event forwarding configuration for a project."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: ProjectId = pydantic.Field(
        description="ID of the project.",
        validation_alias="projectId",
        serialization_alias="projectId",
    )
    config: ProjectOtlpConfig = pydantic.Field(description="OTLP configuration.")


class CreateProjectOutput_Created(CreateProjectSuccess):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Created"] = "Created"


# Output of creating a project.
type CreateProjectOutput = CreateProjectOutput_Created
