# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import Annotated, Literal, TYPE_CHECKING, Union  # noqa: F401

import pydantic  # noqa: F401
import pydantic_core  # noqa: F401

if TYPE_CHECKING:
    from . import json as _schema_json  # noqa: F401


class SystemInfo(pydantic.BaseModel):
    """System information."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    name: str | None = pydantic.Field(default=None, description="System name.")
    version: str | None = pydantic.Field(default=None, description="System version.")
    kernel: str | None = pydantic.Field(default=None, description="Kernel version.")
    hostname: str | None = pydantic.Field(default=None, description="Hostname.")
    arch: str | None = pydantic.Field(default=None, description="Architecture.")
    memory: MemoryInfo = pydantic.Field(description="Memory information.")
    networks: list[NetworkInterfaceInfo] = pydantic.Field(
        description="Network information."
    )
    disks: list[DiskInfo] = pydantic.Field(description="Disk information.")
    exports: list[ExportInfo] | None = pydantic.Field(
        default=None, description="Exported services."
    )
    rugix: RugixSystemInfo | None = pydantic.Field(
        default=None, description="Rugix-specific system information."
    )
    yocto: YoctoSystemInfo | None = pydantic.Field(
        default=None, description="Yocto-specific system information."
    )


class MemoryInfo(pydantic.BaseModel):
    """Memory information."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    total: int = pydantic.Field(description="Total memory in bytes.")


class NetworkInterfaceInfo(pydantic.BaseModel):
    """Network interface information."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    name: str = pydantic.Field(description="Name of the network interface.")
    mac_address: str = pydantic.Field(
        description="MAC address of the network interface.",
        validation_alias="macAddress",
        serialization_alias="macAddress",
    )
    ip_addresses: list[str] = pydantic.Field(
        description="IP addresses of the network interface.",
        validation_alias="ipAddresses",
        serialization_alias="ipAddresses",
    )


class DiskInfo(pydantic.BaseModel):
    """Disk information."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    name: str = pydantic.Field(description="Name of the disk.")
    filesystem: str = pydantic.Field(description="Filesystem type.")
    mount_point: str = pydantic.Field(
        description="Mount point.",
        validation_alias="mountPoint",
        serialization_alias="mountPoint",
    )
    total_space: int = pydantic.Field(
        description="Total disk space in bytes.",
        validation_alias="totalSpace",
        serialization_alias="totalSpace",
    )
    available_space: int = pydantic.Field(
        description="Available disk space in bytes.",
        validation_alias="availableSpace",
        serialization_alias="availableSpace",
    )


class OtaUpdateStatus(pydantic.BaseModel):
    """OTA update status (`dev.nexigon.ota.status`).

    Published by the device agent to report the effective OTA configuration
    and the current state of the update process."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    config: OtaUpdateConfig | None = pydantic.Field(
        default=None,
        description="Effective OTA configuration (TOML defaults merged with device overrides).",
    )
    current_version: str | None = pydantic.Field(
        default=None,
        description="Currently installed version (matches a repository version tag).",
        validation_alias="currentVersion",
        serialization_alias="currentVersion",
    )
    state: OtaUpdateState | None = pydantic.Field(
        default=None, description="Current state of the update process."
    )
    target_version: str | None = pydantic.Field(
        default=None,
        description="Target version being installed, if an update is in progress.",
        validation_alias="targetVersion",
        serialization_alias="targetVersion",
    )
    failure_count: int | None = pydantic.Field(
        default=None,
        description="Number of consecutive failed update attempts for the current target.\nReset to zero when the config changes or an update succeeds.",
        validation_alias="failureCount",
        serialization_alias="failureCount",
    )
    last_error: str | None = pydantic.Field(
        default=None,
        description="Error message from the last failed attempt, if any.",
        validation_alias="lastError",
        serialization_alias="lastError",
    )


class OtaUpdateConfig(pydantic.BaseModel):
    """OTA update configuration identifying the update source.

    Used as the shape of `/etc/nexigon-rugix-ota.json` and the
    `dev.nexigon.ota.config` device property. The device property is
    merged on top of the file-based defaults."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    path: str | None = pydantic.Field(
        default=None,
        description="Repository path prefix for locating update artifacts.",
    )


class DeviceHealth(pydantic.BaseModel):
    """Device health information (`dev.nexigon.system.health`)."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    status: DeviceHealthStatus = pydantic.Field(
        description="Health status of the device."
    )


class HttpExportInfo(pydantic.BaseModel):
    """HTTP export information."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    name: str = pydantic.Field(description="Name of the export.")
    port: int = pydantic.Field(description="Port the service listens on.")
    path: str | None = pydantic.Field(default=None, description="URL path prefix.")


class RugixSystemInfo(pydantic.BaseModel):
    """Rugix-specific system information."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    slots: dict[str, RugixSlotInfo] = pydantic.Field(
        description="Information about the update slots."
    )
    boot: RugixBootInfo | None = pydantic.Field(
        default=None, description="Rugix-specific boot information."
    )
    state: RugixStateManagementInfo = pydantic.Field(
        description="Information about the state management mechanism."
    )
    build: RugixBakeryBuildInfo | None = pydantic.Field(
        default=None,
        description="Rugix Bakery build information (only when built with Rugix Bakery).",
    )


class RugixSlotInfo(pydantic.BaseModel):
    """Information about a Rugix update slot."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    active: bool | None = pydantic.Field(
        default=None, description="Indicates whether the slot is active, i.e., in use."
    )
    hashes: dict[str, str] | None = pydantic.Field(
        default=None,
        description="Hashes of the slot data according to the slot database.",
    )
    size: int | None = pydantic.Field(
        default=None,
        description="Size of the slot data according to the slot database.",
    )
    updated_at: str | None = pydantic.Field(
        default=None,
        description="Last time the slot has been updated according to the slot database.",
        validation_alias="updatedAt",
        serialization_alias="updatedAt",
    )


class RugixBootInfo(pydantic.BaseModel):
    """Rugix-specific boot information."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    boot_flow: str = pydantic.Field(
        description="Name of the boot flow.",
        validation_alias="bootFlow",
        serialization_alias="bootFlow",
    )
    active_group: str | None = pydantic.Field(
        default=None,
        description="Active boot group.",
        validation_alias="activeGroup",
        serialization_alias="activeGroup",
    )
    default_group: str | None = pydantic.Field(
        default=None,
        description="Default boot group.",
        validation_alias="defaultGroup",
        serialization_alias="defaultGroup",
    )
    groups: dict[str, RugixBootGroupInfo] = pydantic.Field(
        description="Information about the boot groups."
    )


class RugixBootGroupInfo(pydantic.BaseModel):
    """Information about a Rugix boot group."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)


class RugixActiveStateManagementInfo(pydantic.BaseModel):
    """Information about the state management mechanism, if state management is active."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    data_partition: str | None = pydantic.Field(
        default=None,
        description="Device backing the data partition, if any.",
        validation_alias="dataPartition",
        serialization_alias="dataPartition",
    )


class RugixBakeryBuildInfo(pydantic.BaseModel):
    """Rugix Bakery build information."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    name: str = pydantic.Field(description="System name.")
    release: RugixBakeryReleaseInfo = pydantic.Field(
        description="Rugix Bakery build release information."
    )


class RugixBakeryReleaseInfo(pydantic.BaseModel):
    """Rugix Bakery build release information."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    id: str = pydantic.Field(description="Release ID.")
    version: str = pydantic.Field(description="Release version.")


class YoctoSystemInfo(pydantic.BaseModel):
    """Yocto-specific system information."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    build_info: dict[str, str] = pydantic.Field(
        description="Build information key-value pairs read from `/etc/buildinfo`.",
        validation_alias="buildInfo",
        serialization_alias="buildInfo",
    )


class DeviceCommandManifest(pydantic.BaseModel):
    """Command manifest (`dev.nexigon.commands` property)."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    commands: list[DeviceCommandDescriptor] = pydantic.Field(
        description="Available commands."
    )


class DeviceCommandDescriptor(pydantic.BaseModel):
    """Descriptor for an on-demand command."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    name: str = pydantic.Field(description="Command name.")
    description: str | None = pydantic.Field(
        default=None, description="Description of what the command does."
    )
    category: str | None = pydantic.Field(
        default=None, description="Category for grouping in the UI."
    )
    input: _schema_json.JsonValue | None = pydantic.Field(
        default=None, description="JSON Schema for the command input."
    )
    output: _schema_json.JsonValue | None = pydantic.Field(
        default=None, description="JSON Schema for the command output."
    )


class OtaUpdateState_Idle(pydantic.RootModel[Literal["idle"]]):
    pass


class OtaUpdateState_Installing(pydantic.RootModel[Literal["installing"]]):
    pass


class OtaUpdateState_Rebooting(pydantic.RootModel[Literal["rebooting"]]):
    pass


class OtaUpdateState_Committing(pydantic.RootModel[Literal["committing"]]):
    pass


class OtaUpdateState_Completed(pydantic.RootModel[Literal["completed"]]):
    pass


class OtaUpdateState_Failed(pydantic.RootModel[Literal["failed"]]):
    pass


class OtaUpdateState_Blocked(pydantic.RootModel[Literal["blocked"]]):
    pass


class OtaUpdateState_Rollback(pydantic.RootModel[Literal["rollback"]]):
    pass


# OTA update state.
#
# The resting states are `idle`, `completed`, `failed`, and `blocked`.
# The agent remains in one of these until the next check cycle begins
# or the blocking condition clears. `idle` means no update has been
# attempted yet; `completed` and `failed` retain the outcome of the
# last cycle; `blocked` indicates an update is available but deferred.
type OtaUpdateState = (
    OtaUpdateState_Idle
    | OtaUpdateState_Installing
    | OtaUpdateState_Rebooting
    | OtaUpdateState_Committing
    | OtaUpdateState_Completed
    | OtaUpdateState_Failed
    | OtaUpdateState_Blocked
    | OtaUpdateState_Rollback
)


class DeviceHealthStatus_Healthy(pydantic.RootModel[Literal["healthy"]]):
    pass


class DeviceHealthStatus_Degraded(pydantic.RootModel[Literal["degraded"]]):
    pass


class DeviceHealthStatus_Error(pydantic.RootModel[Literal["error"]]):
    pass


# Device health status.
type DeviceHealthStatus = (
    DeviceHealthStatus_Healthy | DeviceHealthStatus_Degraded | DeviceHealthStatus_Error
)


class ExportInfo_Http(HttpExportInfo):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    protocol: Literal["http"] = "http"


# Service export information.
type ExportInfo = ExportInfo_Http


class RugixStateManagementInfo_Disabled(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    status: Literal["Disabled"] = "Disabled"


class RugixStateManagementInfo_Active(RugixActiveStateManagementInfo):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    status: Literal["Active"] = "Active"


class RugixStateManagementInfo_Error(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    status: Literal["Error"] = "Error"


# Information about Rugix's state management mechanism.
type RugixStateManagementInfo = Annotated[
    RugixStateManagementInfo_Disabled
    | RugixStateManagementInfo_Active
    | RugixStateManagementInfo_Error,
    pydantic.Discriminator("status"),
]
