# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import Annotated, Literal, TYPE_CHECKING, Union  # noqa: F401

import pydantic  # noqa: F401
import pydantic_core  # noqa: F401

if TYPE_CHECKING:
    from . import json  # noqa: F401


class SystemInfo(pydantic.BaseModel):
    """System information."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    name: str | None = None
    version: str | None = None
    kernel: str | None = None
    hostname: str | None = None
    arch: str | None = None
    memory: MemoryInfo
    networks: list[NetworkInterfaceInfo]
    disks: list[DiskInfo]
    exports: list[ExportInfo] | None = None
    rugix: RugixSystemInfo | None = None
    yocto: YoctoSystemInfo | None = None


class MemoryInfo(pydantic.BaseModel):
    """Memory information."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    total: int


class NetworkInterfaceInfo(pydantic.BaseModel):
    """Network interface information."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    name: str
    mac_address: str = pydantic.Field(
        validation_alias="macAddress", serialization_alias="macAddress"
    )
    ip_addresses: list[str] = pydantic.Field(
        validation_alias="ipAddresses", serialization_alias="ipAddresses"
    )


class DiskInfo(pydantic.BaseModel):
    """Disk information."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    name: str
    filesystem: str
    mount_point: str = pydantic.Field(
        validation_alias="mountPoint", serialization_alias="mountPoint"
    )
    total_space: int = pydantic.Field(
        validation_alias="totalSpace", serialization_alias="totalSpace"
    )
    available_space: int = pydantic.Field(
        validation_alias="availableSpace", serialization_alias="availableSpace"
    )


class OtaUpdateStatus(pydantic.BaseModel):
    """OTA update status (`dev.nexigon.ota.status`).

    Published by the device agent to report the effective OTA configuration
    and the current state of the update process."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    config: OtaUpdateConfig | None = None
    current_version: str | None = pydantic.Field(
        default=None,
        validation_alias="currentVersion",
        serialization_alias="currentVersion",
    )
    state: OtaUpdateState | None = None
    target_version: str | None = pydantic.Field(
        default=None,
        validation_alias="targetVersion",
        serialization_alias="targetVersion",
    )
    failure_count: int | None = pydantic.Field(
        default=None,
        validation_alias="failureCount",
        serialization_alias="failureCount",
    )
    last_error: str | None = pydantic.Field(
        default=None, validation_alias="lastError", serialization_alias="lastError"
    )


class OtaUpdateConfig(pydantic.BaseModel):
    """OTA update configuration identifying the update source.

    Used as the shape of `/etc/nexigon-rugix-ota.json` and the
    `dev.nexigon.ota.config` device property. The device property is
    merged on top of the file-based defaults."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    path: str | None = None


class DeviceHealth(pydantic.BaseModel):
    """Device health information (`dev.nexigon.system.health`)."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    status: DeviceHealthStatus


class HttpExportInfo(pydantic.BaseModel):
    """HTTP export information."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    name: str
    port: int
    path: str | None = None


class RugixSystemInfo(pydantic.BaseModel):
    """Rugix-specific system information."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    slots: dict[str, RugixSlotInfo]
    boot: RugixBootInfo | None = None
    state: RugixStateManagementInfo
    build: RugixBakeryBuildInfo | None = None


class RugixSlotInfo(pydantic.BaseModel):
    """Information about a Rugix update slot."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    active: bool | None = None
    hashes: dict[str, str] | None = None
    size: int | None = None
    updated_at: str | None = pydantic.Field(
        default=None, validation_alias="updatedAt", serialization_alias="updatedAt"
    )


class RugixBootInfo(pydantic.BaseModel):
    """Rugix-specific boot information."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    boot_flow: str = pydantic.Field(
        validation_alias="bootFlow", serialization_alias="bootFlow"
    )
    active_group: str | None = pydantic.Field(
        default=None, validation_alias="activeGroup", serialization_alias="activeGroup"
    )
    default_group: str | None = pydantic.Field(
        default=None,
        validation_alias="defaultGroup",
        serialization_alias="defaultGroup",
    )
    groups: dict[str, RugixBootGroupInfo]


class RugixBootGroupInfo(pydantic.BaseModel):
    """Information about a Rugix boot group."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)


class RugixActiveStateManagementInfo(pydantic.BaseModel):
    """Information about the state management mechanism, if state management is active."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    data_partition: str | None = pydantic.Field(
        default=None,
        validation_alias="dataPartition",
        serialization_alias="dataPartition",
    )


class RugixBakeryBuildInfo(pydantic.BaseModel):
    """Rugix Bakery build information."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    name: str
    release: RugixBakeryReleaseInfo


class RugixBakeryReleaseInfo(pydantic.BaseModel):
    """Rugix Bakery build release information."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    id: str
    version: str


class YoctoSystemInfo(pydantic.BaseModel):
    """Yocto-specific system information."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    build_info: dict[str, str] = pydantic.Field(
        validation_alias="buildInfo", serialization_alias="buildInfo"
    )


class DeviceCommandManifest(pydantic.BaseModel):
    """Command manifest (`dev.nexigon.commands` property)."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    commands: list[DeviceCommandDescriptor]


class DeviceCommandDescriptor(pydantic.BaseModel):
    """Descriptor for an on-demand command."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    name: str
    description: str | None = None
    category: str | None = None
    input: json.JsonValue | None = None
    output: json.JsonValue | None = None


class OtaUpdateState_Idle(pydantic.RootModel[Literal["idle"]]):
    pass


class OtaUpdateState_Installing(pydantic.RootModel[Literal["installing"]]):
    pass


class OtaUpdateState_Rebooting(pydantic.RootModel[Literal["rebooting"]]):
    pass


class OtaUpdateState_Committing(pydantic.RootModel[Literal["committing"]]):
    pass


class OtaUpdateState_Completed(pydantic.RootModel[Literal["completed"]]):
    pass


class OtaUpdateState_Failed(pydantic.RootModel[Literal["failed"]]):
    pass


class OtaUpdateState_Blocked(pydantic.RootModel[Literal["blocked"]]):
    pass


class OtaUpdateState_Rollback(pydantic.RootModel[Literal["rollback"]]):
    pass


# OTA update state.
#
# The resting states are `idle`, `completed`, `failed`, and `blocked`.
# The agent remains in one of these until the next check cycle begins
# or the blocking condition clears. `idle` means no update has been
# attempted yet; `completed` and `failed` retain the outcome of the
# last cycle; `blocked` indicates an update is available but deferred.
type OtaUpdateState = (
    OtaUpdateState_Idle
    | OtaUpdateState_Installing
    | OtaUpdateState_Rebooting
    | OtaUpdateState_Committing
    | OtaUpdateState_Completed
    | OtaUpdateState_Failed
    | OtaUpdateState_Blocked
    | OtaUpdateState_Rollback
)


class DeviceHealthStatus_Healthy(pydantic.RootModel[Literal["healthy"]]):
    pass


class DeviceHealthStatus_Degraded(pydantic.RootModel[Literal["degraded"]]):
    pass


class DeviceHealthStatus_Error(pydantic.RootModel[Literal["error"]]):
    pass


# Device health status.
type DeviceHealthStatus = (
    DeviceHealthStatus_Healthy | DeviceHealthStatus_Degraded | DeviceHealthStatus_Error
)


class ExportInfo_Http(HttpExportInfo):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    protocol: Literal["http"] = "http"


# Service export information.
type ExportInfo = ExportInfo_Http


class RugixStateManagementInfo_Disabled(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    status: Literal["Disabled"] = "Disabled"


class RugixStateManagementInfo_Active(RugixActiveStateManagementInfo):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    status: Literal["Active"] = "Active"


class RugixStateManagementInfo_Error(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    status: Literal["Error"] = "Error"


# Information about Rugix's state management mechanism.
type RugixStateManagementInfo = Annotated[
    RugixStateManagementInfo_Disabled
    | RugixStateManagementInfo_Active
    | RugixStateManagementInfo_Error,
    pydantic.Discriminator("status"),
]
