# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import Annotated, Literal, TYPE_CHECKING, Union  # noqa: F401

import pydantic  # noqa: F401
import pydantic_core  # noqa: F401

if TYPE_CHECKING:
    from . import audit  # noqa: F401
    from . import datetime  # noqa: F401
    from . import digest  # noqa: F401
    from . import json  # noqa: F401
    from . import organizations  # noqa: F401
    from . import projects  # noqa: F401


class RepositoryId(str):
    """Unique ID of a repository."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class RepositoryAssetId(str):
    """Unique ID of a repository asset."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class PackageId(str):
    """Unique ID of a package."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class PackageVersionId(str):
    """Unique ID of a package version."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class RepositoryS3Config(pydantic.BaseModel):
    """Repository S3 config."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    endpoint: str
    bucket: str
    region: str | None = None
    prefix: str | None = None
    access_key_id: str = pydantic.Field(
        validation_alias="accessKeyId", serialization_alias="accessKeyId"
    )
    secret_access_key: str | None = pydantic.Field(
        default=None,
        validation_alias="secretAccessKey",
        serialization_alias="secretAccessKey",
    )


class ResolveRepositoryNameAction(pydantic.BaseModel):
    """Resolve a repository by its name."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository: str


class GetRepositoryDetailsAction(pydantic.BaseModel):
    """Get information about a repository."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository_id: RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )


class GetRepositoryDetailsOutput(pydantic.BaseModel):
    """Output of getting information about a repository."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository_id: RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )
    display_name: str = pydantic.Field(
        validation_alias="displayName", serialization_alias="displayName"
    )
    public_name: str | None = pydantic.Field(
        default=None, validation_alias="publicName", serialization_alias="publicName"
    )
    visibility: RepositoryVisibility
    package_count: int = pydantic.Field(
        validation_alias="packageCount", serialization_alias="packageCount"
    )
    asset_count: int = pydantic.Field(
        validation_alias="assetCount", serialization_alias="assetCount"
    )


class CreateRepositoryAction(pydantic.BaseModel):
    """Create a new repository."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: organizations.OrganizationId = pydantic.Field(
        validation_alias="organizationId", serialization_alias="organizationId"
    )
    name: str
    visibility: RepositoryVisibility | None = None


class CreateRepositorySuccess(pydantic.BaseModel):
    """Successfully created a repository."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository_id: RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )


class DeleteRepositoryAction(pydantic.BaseModel):
    """Delete a repository."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository_id: RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )


class SetRepositoryVisibilityAction(pydantic.BaseModel):
    """Set the visibility of a repository."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository_id: RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )
    visibility: RepositoryVisibility


class SetRepositoryDisplayNameAction(pydantic.BaseModel):
    """Set the display name of a repository."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository_id: RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )
    display_name: str | None = pydantic.Field(
        default=None, validation_alias="displayName", serialization_alias="displayName"
    )


class SetRepositoryPublicNameAction(pydantic.BaseModel):
    """Set the public name of a repository.

    Note: Setting the public name requires the `public_repositories` subscription feature."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository_id: RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )
    public_name: str = pydantic.Field(
        validation_alias="publicName", serialization_alias="publicName"
    )


class QueryRepositoryPackagesAction(pydantic.BaseModel):
    """Query the packages of a repository."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository_id: RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )


class QueryRepositoryPackagesOutput(pydantic.BaseModel):
    """Output of querying the packages of a repository."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    packages: list[QueryRepositoryPackagesItem]


class QueryRepositoryPackagesItem(pydantic.BaseModel):
    """Package query item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    package_id: PackageId = pydantic.Field(
        validation_alias="packageId", serialization_alias="packageId"
    )
    name: str
    kind: str | None = None
    created_at: datetime.Timestamp = pydantic.Field(
        validation_alias="createdAt", serialization_alias="createdAt"
    )


class QueryRepositoryAssetsAction(pydantic.BaseModel):
    """Query the assets of a repository."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository_id: RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )


class QueryRepositoryAssetsOutput(pydantic.BaseModel):
    """Output of querying the assets of a repository."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    assets: list[QueryRepositoryAssetsItem]


class QueryRepositoryAssetsItem(pydantic.BaseModel):
    """Asset query item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    asset_id: RepositoryAssetId = pydantic.Field(
        validation_alias="assetId", serialization_alias="assetId"
    )
    size: int
    digest: digest.Digest


class QueryRepositoryProjectsAction(pydantic.BaseModel):
    """Query repository projects."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository_id: RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )


class QueryRepositoryProjectsOutput(pydantic.BaseModel):
    """Output of querying the projects of a repository."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    projects: list[QueryRepositoryProjectsItem]


class QueryRepositoryProjectsItem(pydantic.BaseModel):
    """Project item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    project_id: projects.ProjectId = pydantic.Field(
        validation_alias="projectId", serialization_alias="projectId"
    )
    name: str


class ResolvePackageByPathAction(pydantic.BaseModel):
    """Resolve a package by its path."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository: str
    package: str


class ResolvePackageByPathSuccess(pydantic.BaseModel):
    """Successfully resolved package by path."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository_id: RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )
    package_id: PackageId = pydantic.Field(
        validation_alias="packageId", serialization_alias="packageId"
    )


class GetPackageDetailsAction(pydantic.BaseModel):
    """Get information about a package."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    package_id: PackageId = pydantic.Field(
        validation_alias="packageId", serialization_alias="packageId"
    )


class GetPackageDetailsOutput(pydantic.BaseModel):
    """Output of getting information about a package."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    package_id: PackageId = pydantic.Field(
        validation_alias="packageId", serialization_alias="packageId"
    )
    name: str
    kind: str | None = None
    version_count: int = pydantic.Field(
        validation_alias="versionCount", serialization_alias="versionCount"
    )
    metadata: dict[str, json.JsonValue]


class CreatePackageAction(pydantic.BaseModel):
    """Create a new package."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository_id: RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )
    name: str
    kind: str | None = None
    metadata: dict[str, json.JsonValue] | None = None


class CreatePackageSuccess(pydantic.BaseModel):
    """Successfully created a package."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    package_id: PackageId = pydantic.Field(
        validation_alias="packageId", serialization_alias="packageId"
    )


class DeletePackageAction(pydantic.BaseModel):
    """Delete a package."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    package_id: PackageId = pydantic.Field(
        validation_alias="packageId", serialization_alias="packageId"
    )


class SetPackageMetadataAction(pydantic.BaseModel):
    """Set metadata on a package."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    package_id: PackageId = pydantic.Field(
        validation_alias="packageId", serialization_alias="packageId"
    )
    metadata: dict[str, json.JsonValue]


class SetPackageKindAction(pydantic.BaseModel):
    """Set the kind of a package."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    package_id: PackageId = pydantic.Field(
        validation_alias="packageId", serialization_alias="packageId"
    )
    kind: str | None = None


class SetPackageNameAction(pydantic.BaseModel):
    """Set the name of a package."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    package_id: PackageId = pydantic.Field(
        validation_alias="packageId", serialization_alias="packageId"
    )
    name: str


class QueryPackageVersionsAction(pydantic.BaseModel):
    """Query the versions of a package."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    package_id: PackageId = pydantic.Field(
        validation_alias="packageId", serialization_alias="packageId"
    )


class QueryPackageVersionsOutput(pydantic.BaseModel):
    """Output of querying the versions of a package."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    versions: list[QueryPackageVersionsItem]


class QueryPackageVersionsItem(pydantic.BaseModel):
    """Package version query item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    version_id: PackageVersionId = pydantic.Field(
        validation_alias="versionId", serialization_alias="versionId"
    )
    name: str | None = None
    created_at: datetime.Timestamp = pydantic.Field(
        validation_alias="createdAt", serialization_alias="createdAt"
    )
    tags: list[PackageVersionTag]


class PackageVersionTag(pydantic.BaseModel):
    """Package version tag."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    tag: str
    locked: bool


class AddTagItem(pydantic.BaseModel):
    """Add tag item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    tag: str
    locked: bool | None = None
    reassign: bool | None = None


class RemoveTagItem(pydantic.BaseModel):
    """Remove tag item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    tag: str


class PackageVersionAsset(pydantic.BaseModel):
    """Package version asset."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    filename: str
    asset_id: RepositoryAssetId = pydantic.Field(
        validation_alias="assetId", serialization_alias="assetId"
    )
    size: int
    digest: digest.Digest
    status: RepositoryAssetStatus
    metadata: dict[str, json.JsonValue]


class ResolvePackageVersionByPathAction(pydantic.BaseModel):
    """Resolve a package version by its path."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository: str
    package: str
    tag: str


class ResolvePackageVersionByPathSuccess(pydantic.BaseModel):
    """Successfully resolved package version by path."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository_id: RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )
    package_id: PackageId = pydantic.Field(
        validation_alias="packageId", serialization_alias="packageId"
    )
    version_id: PackageVersionId = pydantic.Field(
        validation_alias="versionId", serialization_alias="versionId"
    )


class GetPackageVersionDetailsAction(pydantic.BaseModel):
    """Get information about a package version."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    version_id: PackageVersionId = pydantic.Field(
        validation_alias="versionId", serialization_alias="versionId"
    )


class GetPackageVersionDetailsOutput(pydantic.BaseModel):
    """Output of getting information about a package version."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    version_id: PackageVersionId = pydantic.Field(
        validation_alias="versionId", serialization_alias="versionId"
    )
    repository_id: RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )
    package_id: PackageId = pydantic.Field(
        validation_alias="packageId", serialization_alias="packageId"
    )
    name: str | None = None
    assets: list[PackageVersionAsset]
    tags: list[PackageVersionTag]
    metadata: dict[str, json.JsonValue]


class CreatePackageVersionAction(pydantic.BaseModel):
    """Create a new package version."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    package_id: PackageId = pydantic.Field(
        validation_alias="packageId", serialization_alias="packageId"
    )
    name: str | None = None
    tags: list[AddTagItem] | None = None
    metadata: dict[str, json.JsonValue] | None = None


class CreatePackageVersionSuccess(pydantic.BaseModel):
    """Package version creation has been successful."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    version_id: PackageVersionId = pydantic.Field(
        validation_alias="versionId", serialization_alias="versionId"
    )


class DeletePackageVersionAction(pydantic.BaseModel):
    """Delete a package version."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    version_id: PackageVersionId = pydantic.Field(
        validation_alias="versionId", serialization_alias="versionId"
    )


class SetPackageVersionNameAction(pydantic.BaseModel):
    """Set the name of a package version."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    version_id: PackageVersionId = pydantic.Field(
        validation_alias="versionId", serialization_alias="versionId"
    )
    name: str | None = None


class SetPackageVersionMetadataAction(pydantic.BaseModel):
    """Set metadata on a package version."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    version_id: PackageVersionId = pydantic.Field(
        validation_alias="versionId", serialization_alias="versionId"
    )
    metadata: dict[str, json.JsonValue]


class AddPackageVersionAssetAction(pydantic.BaseModel):
    """Add an asset to a package version."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    version_id: PackageVersionId = pydantic.Field(
        validation_alias="versionId", serialization_alias="versionId"
    )
    asset_id: RepositoryAssetId = pydantic.Field(
        validation_alias="assetId", serialization_alias="assetId"
    )
    filename: str
    metadata: dict[str, json.JsonValue] | None = None


class RemovePackageVersionAssetAction(pydantic.BaseModel):
    """Remove an asset from a package version."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    version_id: PackageVersionId = pydantic.Field(
        validation_alias="versionId", serialization_alias="versionId"
    )
    filename: str


class SetPackageVersionAssetMetadataAction(pydantic.BaseModel):
    """Set metadata on a package version asset."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    version_id: PackageVersionId = pydantic.Field(
        validation_alias="versionId", serialization_alias="versionId"
    )
    filename: str
    metadata: dict[str, json.JsonValue]


class TagPackageVersionAction(pydantic.BaseModel):
    """Add tags to a version."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    version_id: PackageVersionId = pydantic.Field(
        validation_alias="versionId", serialization_alias="versionId"
    )
    tags: list[AddTagItem]


class UntagPackageVersionAction(pydantic.BaseModel):
    """Remove tags from a version."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    version_id: PackageVersionId = pydantic.Field(
        validation_alias="versionId", serialization_alias="versionId"
    )
    tags: list[RemoveTagItem]


class ResolvePackageVersionAssetByPathAction(pydantic.BaseModel):
    """Resolve a version asset by its path."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository: str
    package: str
    tag: str
    filename: str


class ResolvePackageVersionAssetByPathSuccess(pydantic.BaseModel):
    """Successfully resolved version asset by path."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository_id: RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )
    package_id: PackageId = pydantic.Field(
        validation_alias="packageId", serialization_alias="packageId"
    )
    version_id: PackageVersionId = pydantic.Field(
        validation_alias="versionId", serialization_alias="versionId"
    )
    asset_id: RepositoryAssetId = pydantic.Field(
        validation_alias="assetId", serialization_alias="assetId"
    )


class SetRepositoryS3ConfigAction(pydantic.BaseModel):
    """Set the S3 configuration for the repository."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository_id: RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )
    s_3_config: RepositoryS3Config = pydantic.Field(
        validation_alias="s3Config", serialization_alias="s3Config"
    )


class GetRepositoryS3ConfigAction(pydantic.BaseModel):
    """Get the S3 configuration for the repository."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository_id: RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )


class GetRepositoryS3ConfigOutput(pydantic.BaseModel):
    """Output of getting the S3 configuration for the repository.

    This intentionally does not include the secret access key."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    s_3_config: RepositoryS3Config = pydantic.Field(
        validation_alias="s3Config", serialization_alias="s3Config"
    )


class GetAssetDetailsAction(pydantic.BaseModel):
    """Get information about an asset."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    asset_id: RepositoryAssetId = pydantic.Field(
        validation_alias="assetId", serialization_alias="assetId"
    )


class GetAssetDetailsOutput(pydantic.BaseModel):
    """Output of getting information about an asset."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    asset_id: RepositoryAssetId = pydantic.Field(
        validation_alias="assetId", serialization_alias="assetId"
    )
    size: int
    digest: digest.Digest
    status: RepositoryAssetStatus
    reference_count: int = pydantic.Field(
        validation_alias="referenceCount", serialization_alias="referenceCount"
    )


class CreateAssetAction(pydantic.BaseModel):
    """Create an asset."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository_id: RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )
    size: int
    digest: digest.Digest


class DeleteAssetAction(pydantic.BaseModel):
    """Delete an asset."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    asset_id: RepositoryAssetId = pydantic.Field(
        validation_alias="assetId", serialization_alias="assetId"
    )


class IssueAssetDownloadUrlAction(pydantic.BaseModel):
    """Issue a URL for downloading an asset."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    asset_id: RepositoryAssetId = pydantic.Field(
        validation_alias="assetId", serialization_alias="assetId"
    )
    filename: str | None = None


class IssueAssetDownloadUrlOutput(pydantic.BaseModel):
    """Output of issuing a URL for downloading an asset."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    url: str


class IssueAssetUploadUrlAction(pydantic.BaseModel):
    """Issue a URL for uploading an asset."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    asset_id: RepositoryAssetId = pydantic.Field(
        validation_alias="assetId", serialization_alias="assetId"
    )


class IssueAssetUploadUrlOutput(pydantic.BaseModel):
    """Output of issuing a URL for uploading an asset."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    url: str


class QueryAuditLogEventsAction(pydantic.BaseModel):
    """Query the audit log of the repository."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    repository_id: RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )


class QueryAuditLogEventsOutput(pydantic.BaseModel):
    """Output of querying the audit log of the repository."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    events: list[audit.AuditLogEvent]


class RepositoryAssetStatus_Dangling(pydantic.RootModel[Literal["Dangling"]]):
    pass


class RepositoryAssetStatus_Available(pydantic.RootModel[Literal["Available"]]):
    pass


class RepositoryAssetStatus_Deleting(pydantic.RootModel[Literal["Deleting"]]):
    pass


# Asset status.
type RepositoryAssetStatus = (
    RepositoryAssetStatus_Dangling
    | RepositoryAssetStatus_Available
    | RepositoryAssetStatus_Deleting
)


class RepositoryVisibility_Public(pydantic.RootModel[Literal["Public"]]):
    pass


class RepositoryVisibility_Private(pydantic.RootModel[Literal["Private"]]):
    pass


# Repository visibility.
type RepositoryVisibility = RepositoryVisibility_Public | RepositoryVisibility_Private


class ResolveRepositoryNameOutput_Found(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Found"] = "Found"
    repository_id: RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )


class ResolveRepositoryNameOutput_NotFound(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["NotFound"] = "NotFound"


# Output of resolving a repository by its name.
type ResolveRepositoryNameOutput = Annotated[
    ResolveRepositoryNameOutput_Found | ResolveRepositoryNameOutput_NotFound,
    pydantic.Discriminator("result"),
]


class CreateRepositoryOutput_NameAlreadyExists(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["NameAlreadyExists"] = "NameAlreadyExists"


class CreateRepositoryOutput_Created(CreateRepositorySuccess):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Created"] = "Created"


# Output of creating a repository.
type CreateRepositoryOutput = Annotated[
    CreateRepositoryOutput_NameAlreadyExists | CreateRepositoryOutput_Created,
    pydantic.Discriminator("result"),
]


class SetRepositoryPublicNameOutput_NameAlreadyExists(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["NameAlreadyExists"] = "NameAlreadyExists"


class SetRepositoryPublicNameOutput_Success(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Success"] = "Success"


# Output of setting the public name of a repository.
type SetRepositoryPublicNameOutput = Annotated[
    SetRepositoryPublicNameOutput_NameAlreadyExists
    | SetRepositoryPublicNameOutput_Success,
    pydantic.Discriminator("result"),
]


class ResolvePackageByPathOutput_Found(ResolvePackageByPathSuccess):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Found"] = "Found"


class ResolvePackageByPathOutput_NotFound(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["NotFound"] = "NotFound"


# Output of resolving a package by its path.
type ResolvePackageByPathOutput = Annotated[
    ResolvePackageByPathOutput_Found | ResolvePackageByPathOutput_NotFound,
    pydantic.Discriminator("result"),
]


class CreatePackageOutput_NameAlreadyExists(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["NameAlreadyExists"] = "NameAlreadyExists"


class CreatePackageOutput_Created(CreatePackageSuccess):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Created"] = "Created"


# Output of creating a package.
type CreatePackageOutput = Annotated[
    CreatePackageOutput_NameAlreadyExists | CreatePackageOutput_Created,
    pydantic.Discriminator("result"),
]


class SetPackageNameOutput_NameAlreadyExists(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["NameAlreadyExists"] = "NameAlreadyExists"


class SetPackageNameOutput_Success(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Success"] = "Success"


# Output of setting the name of a package.
type SetPackageNameOutput = Annotated[
    SetPackageNameOutput_NameAlreadyExists | SetPackageNameOutput_Success,
    pydantic.Discriminator("result"),
]


class ResolvePackageVersionByPathOutput_Found(ResolvePackageVersionByPathSuccess):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Found"] = "Found"


class ResolvePackageVersionByPathOutput_NotFound(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["NotFound"] = "NotFound"


# Output of resolving a package version by its path.
type ResolvePackageVersionByPathOutput = Annotated[
    ResolvePackageVersionByPathOutput_Found
    | ResolvePackageVersionByPathOutput_NotFound,
    pydantic.Discriminator("result"),
]


class CreatePackageVersionOutput_Created(CreatePackageVersionSuccess):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Created"] = "Created"


# Output of creating a package version.
type CreatePackageVersionOutput = CreatePackageVersionOutput_Created


class AddPackageVersionAssetOutput_FilenameAlreadyExists(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["FilenameAlreadyExists"] = "FilenameAlreadyExists"


class AddPackageVersionAssetOutput_Added(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Added"] = "Added"


# Output of adding an asset to a package version.
type AddPackageVersionAssetOutput = Annotated[
    AddPackageVersionAssetOutput_FilenameAlreadyExists
    | AddPackageVersionAssetOutput_Added,
    pydantic.Discriminator("result"),
]


class ResolvePackageVersionAssetByPathOutput_Found(
    ResolvePackageVersionAssetByPathSuccess
):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Found"] = "Found"


class ResolvePackageVersionAssetByPathOutput_NotFound(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["NotFound"] = "NotFound"


# Output of resolving a version asset by its path.
type ResolvePackageVersionAssetByPathOutput = Annotated[
    ResolvePackageVersionAssetByPathOutput_Found
    | ResolvePackageVersionAssetByPathOutput_NotFound,
    pydantic.Discriminator("result"),
]


class CreateAssetOutput_AssetAlreadyExists(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["AssetAlreadyExists"] = "AssetAlreadyExists"
    asset_id: RepositoryAssetId = pydantic.Field(
        validation_alias="assetId", serialization_alias="assetId"
    )


class CreateAssetOutput_Created(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Created"] = "Created"
    asset_id: RepositoryAssetId = pydantic.Field(
        validation_alias="assetId", serialization_alias="assetId"
    )


# Output of creating an asset.
type CreateAssetOutput = Annotated[
    CreateAssetOutput_AssetAlreadyExists | CreateAssetOutput_Created,
    pydantic.Discriminator("result"),
]
