# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import Annotated, Literal, TYPE_CHECKING, Union  # noqa: F401

import pydantic  # noqa: F401
import pydantic_core  # noqa: F401

if TYPE_CHECKING:
    from . import datetime as _schema_datetime  # noqa: F401
    from . import devices as _schema_devices  # noqa: F401
    from . import jwt as _schema_jwt  # noqa: F401
    from . import organizations as _schema_organizations  # noqa: F401


class UserId(str):
    """Unique ID of a user."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class UserTokenId(str):
    """Unique ID of a user token."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class UserToken(str):
    """User token."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class UserSessionId(str):
    """User session ID."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class UserSessionToken(str):
    """User session token."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class QueryUsersAction(pydantic.BaseModel):
    """Query the users of the instance."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )


class QueryUsersOutput(pydantic.BaseModel):
    """Output of querying the users of the instance."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    users: list[QueryUsersItem] = pydantic.Field(description="List of users.")


class QueryUsersItem(pydantic.BaseModel):
    """User item."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )
    email: str = pydantic.Field(description="Email of the user.")
    display_name: str | None = pydantic.Field(
        default=None,
        description="Name of the user.",
        validation_alias="displayName",
        serialization_alias="displayName",
    )
    is_admin: bool = pydantic.Field(
        description="Whether the user is an instance admin.",
        validation_alias="isAdmin",
        serialization_alias="isAdmin",
    )
    is_active: bool = pydantic.Field(
        description="Whether the user account has been activated.\n\nNew registrations start out inactive and are activated when the\nuser confirms their email address.",
        validation_alias="isActive",
        serialization_alias="isActive",
    )
    created_at: _schema_datetime.Timestamp = pydantic.Field(
        description="Timestamp when the user was created.",
        validation_alias="createdAt",
        serialization_alias="createdAt",
    )


class GetUserDetailsAction(pydantic.BaseModel):
    """Get information about a user."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )


class GetUserDetailsOutput(pydantic.BaseModel):
    """Information about the user."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )
    email: str = pydantic.Field(description="Email of the user.")
    display_name: str | None = pydantic.Field(
        default=None,
        description="Name of the user.",
        validation_alias="displayName",
        serialization_alias="displayName",
    )
    is_admin: bool = pydantic.Field(
        description="Whether the user is an instance admin.",
        validation_alias="isAdmin",
        serialization_alias="isAdmin",
    )


class CreateUserAction(pydantic.BaseModel):
    """Create a new user."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    email: str = pydantic.Field(description="Email of the user.")
    display_name: str | None = pydantic.Field(
        default=None,
        description="Name of the user.",
        validation_alias="displayName",
        serialization_alias="displayName",
    )
    password: str | None = pydantic.Field(
        default=None, description="Password of the user."
    )
    is_admin: bool | None = pydantic.Field(
        default=None,
        description="Whether the user is an instance admin.",
        validation_alias="isAdmin",
        serialization_alias="isAdmin",
    )


class CreateUserSuccess(pydantic.BaseModel):
    """User was created successfully."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )


class DeleteUserAction(pydantic.BaseModel):
    """Delete a user."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    user_id: UserId = pydantic.Field(
        description="ID of the user to delete.",
        validation_alias="userId",
        serialization_alias="userId",
    )


class SetUserDisplayNameAction(pydantic.BaseModel):
    """Set the display name of a user."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    user_id: UserId = pydantic.Field(
        description="ID of the user to update.",
        validation_alias="userId",
        serialization_alias="userId",
    )
    display_name: str = pydantic.Field(
        description="New name of the user.",
        validation_alias="displayName",
        serialization_alias="displayName",
    )


class SetUserPasswordAction(pydantic.BaseModel):
    """Set the password of a user."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )
    password: str = pydantic.Field(description="New password of the user.")


class SetUserIsAdminAction(pydantic.BaseModel):
    """Set whether the user is an instance administrator."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )
    is_admin: bool = pydantic.Field(
        description="Whether the user is an instance administrator.",
        validation_alias="isAdmin",
        serialization_alias="isAdmin",
    )


class ResetUserPasswordAction(pydantic.BaseModel):
    """Reset the password of a user.

    This will send an email to the user with a link to reset their password."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    email: str = pydantic.Field(description="Email of the user.")


class CompleteUserPasswordResetAction(pydantic.BaseModel):
    """Complete the password reset of a user."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    reset_token: _schema_jwt.Jwt = pydantic.Field(
        description="Token to use for password reset.",
        validation_alias="resetToken",
        serialization_alias="resetToken",
    )
    password: str = pydantic.Field(description="New password of the user.")


class QueryUserTokensAction(pydantic.BaseModel):
    """Query the tokens of a user."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )


class QueryUserTokensOutput(pydantic.BaseModel):
    """Output of querying the tokens of a user."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    tokens: list[QueryUserTokensItem] = pydantic.Field(
        description="List of user tokens."
    )


class QueryUserTokensItem(pydantic.BaseModel):
    """User token item."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    token_id: UserTokenId = pydantic.Field(
        description="ID of the token.",
        validation_alias="tokenId",
        serialization_alias="tokenId",
    )
    created_at: _schema_datetime.Timestamp = pydantic.Field(
        description="Creation date of the token.",
        validation_alias="createdAt",
        serialization_alias="createdAt",
    )
    name: str | None = pydantic.Field(default=None, description="Name of the token.")


class QueryUserOrganizationsAction(pydantic.BaseModel):
    """Query the organizations of a user."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )


class QueryUserOrganizationsOutput(pydantic.BaseModel):
    """Output of querying the organizations of a user."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    organizations: list[QueryUserOrganizationsItem] = pydantic.Field(
        description="List of organizations."
    )


class QueryUserOrganizationsItem(pydantic.BaseModel):
    """Organization item."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    organization_id: _schema_organizations.OrganizationId = pydantic.Field(
        description="ID of the organization.",
        validation_alias="organizationId",
        serialization_alias="organizationId",
    )
    name: str = pydantic.Field(description="Name of the organization.")
    requires_subscription: bool = pydantic.Field(
        description="Whether the organization requires a paid subscription.",
        validation_alias="requiresSubscription",
        serialization_alias="requiresSubscription",
    )
    subscription_plan_name: str | None = pydantic.Field(
        default=None,
        description="Name of the active subscription plan, if any.",
        validation_alias="subscriptionPlanName",
        serialization_alias="subscriptionPlanName",
    )


class QueryUserOrganizationInvitationsAction(pydantic.BaseModel):
    """Query the organization invitations of a user."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )


class QueryUserOrganizationInvitationsOutput(pydantic.BaseModel):
    """Output of querying the organization invitations of a user."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    invitations: list[QueryUserOrganizationInvitationsItem] = pydantic.Field(
        description="List of organization invitations."
    )


class QueryUserOrganizationInvitationsItem(pydantic.BaseModel):
    """Organization invitation item."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    invitation_id: _schema_organizations.OrganizationInvitationId = pydantic.Field(
        description="ID of the invitation.",
        validation_alias="invitationId",
        serialization_alias="invitationId",
    )
    organization: QueryUserOrganizationInvitationsItemOrganization = pydantic.Field(
        description="Information about the organization."
    )


class QueryUserOrganizationInvitationsItemOrganization(pydantic.BaseModel):
    """Organization invitation item organization."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    organization_id: _schema_organizations.OrganizationId = pydantic.Field(
        description="ID of the organization.",
        validation_alias="organizationId",
        serialization_alias="organizationId",
    )
    name: str = pydantic.Field(description="Name of the organization.")


class QueryUserSessionsAction(pydantic.BaseModel):
    """Query the sessions of a user."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )


class QueryUserSessionsOutput(pydantic.BaseModel):
    """Output of querying the sessions of a user."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    sessions: list[UserSession] = pydantic.Field(description="List of user sessions.")


class UserSession(pydantic.BaseModel):
    """User session."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    session_id: UserSessionId = pydantic.Field(
        description="ID of the session.",
        validation_alias="sessionId",
        serialization_alias="sessionId",
    )
    created_at: _schema_datetime.Timestamp = pydantic.Field(
        description="Creation date of the session.",
        validation_alias="createdAt",
        serialization_alias="createdAt",
    )
    expires_at: _schema_datetime.Timestamp = pydantic.Field(
        description="Expiration date of the session.",
        validation_alias="expiresAt",
        serialization_alias="expiresAt",
    )
    user_agent: str = pydantic.Field(
        description="User agent of the session.",
        validation_alias="userAgent",
        serialization_alias="userAgent",
    )


class GetDevicePermissionsAction(pydantic.BaseModel):
    """Check the permissions of a user for a given device."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )
    device_id: _schema_devices.DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )


class GetDevicePermissionsOutput(pydantic.BaseModel):
    """Output of checking the permissions of a user for a given device."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    has_access: bool = pydantic.Field(
        description="Whether the user has access to the device.",
        validation_alias="hasAccess",
        serialization_alias="hasAccess",
    )


class CreateUserTokenAction(pydantic.BaseModel):
    """Create a user token."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )
    name: str | None = pydantic.Field(default=None, description="Name of the token.")


class CreateUserTokenOutput(pydantic.BaseModel):
    """Output of creating a user token."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    token_id: UserTokenId = pydantic.Field(
        description="ID of the token.",
        validation_alias="tokenId",
        serialization_alias="tokenId",
    )
    token: UserToken = pydantic.Field(description="Token.")


class DeleteUserTokenAction(pydantic.BaseModel):
    """Delete a user token."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    token_id: UserTokenId = pydantic.Field(
        description="ID of the token.",
        validation_alias="tokenId",
        serialization_alias="tokenId",
    )


class CleanupExpiredUserSessionsAction(pydantic.BaseModel):
    """Cleanup expired user sessions."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )


class RegisterUserAction(pydantic.BaseModel):
    """Register a new user with an email and password."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    display_name: str | None = pydantic.Field(
        default=None,
        description="Name of the user.",
        validation_alias="displayName",
        serialization_alias="displayName",
    )
    email: str = pydantic.Field(description="Email address of the user.")
    password: str = pydantic.Field(description="Password of the user.")
    consented_to_terms: bool = pydantic.Field(
        description="Indicates whether the user has consented to the terms and conditions.\n\nThis must be `true` to register a user.",
        validation_alias="consentedToTerms",
        serialization_alias="consentedToTerms",
    )
    consented_to_marketing: bool | None = pydantic.Field(
        default=None,
        description="Indicates whether the user has consented to marketing communications.",
        validation_alias="consentedToMarketing",
        serialization_alias="consentedToMarketing",
    )


class UserRegistration(pydantic.BaseModel):
    """User registration."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    status: UserRegistrationStatus = pydantic.Field(description="Registration status.")
    message: str | None = pydantic.Field(
        default=None, description="Optional message to show to the user."
    )
    created_at: _schema_datetime.Timestamp = pydantic.Field(
        description="Timestamp when the registration was created.",
        validation_alias="createdAt",
        serialization_alias="createdAt",
    )


class ResendRegistrationEmailAction(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    email: str = pydantic.Field(description="Email address of the user.")


class CompleteRegistrationAction(pydantic.BaseModel):
    """Complete the registration of a user."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    activation_token: _schema_jwt.Jwt = pydantic.Field(
        description="Token to use for account activation.",
        validation_alias="activationToken",
        serialization_alias="activationToken",
    )


class AcceptOrganizationInvitationAction(pydantic.BaseModel):
    """Accept a organization invitation."""

    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    invitation_id: _schema_organizations.OrganizationInvitationId = pydantic.Field(
        description="ID of the invitation.",
        validation_alias="invitationId",
        serialization_alias="invitationId",
    )


class CreateUserOutput_Created(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    result: Literal["Created"] = "Created"
    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )

    def payload(self) -> "CreateUserSuccess":
        return CreateUserSuccess(user_id=self.user_id)


class CreateUserOutput_EmailAlreadyExists(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    result: Literal["EmailAlreadyExists"] = "EmailAlreadyExists"


# Output of creating a user.
type CreateUserOutput = Annotated[
    CreateUserOutput_Created | CreateUserOutput_EmailAlreadyExists,
    pydantic.Discriminator("result"),
]


class CompleteUserPasswordResetOutput_Completed(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    result: Literal["Completed"] = "Completed"


class CompleteUserPasswordResetOutput_InvalidToken(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    result: Literal["InvalidToken"] = "InvalidToken"


# Output of completing the password reset of a user.
type CompleteUserPasswordResetOutput = Annotated[
    CompleteUserPasswordResetOutput_Completed
    | CompleteUserPasswordResetOutput_InvalidToken,
    pydantic.Discriminator("result"),
]


class RegisterUserOutput_Created(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    result: Literal["Created"] = "Created"
    status: UserRegistrationStatus = pydantic.Field(description="Registration status.")
    message: str | None = pydantic.Field(
        default=None, description="Optional message to show to the user."
    )
    created_at: _schema_datetime.Timestamp = pydantic.Field(
        description="Timestamp when the registration was created.",
        validation_alias="createdAt",
        serialization_alias="createdAt",
    )

    def payload(self) -> "UserRegistration":
        return UserRegistration(
            status=self.status, message=self.message, created_at=self.created_at
        )


class RegisterUserOutput_Pending(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    result: Literal["Pending"] = "Pending"
    status: UserRegistrationStatus = pydantic.Field(description="Registration status.")
    message: str | None = pydantic.Field(
        default=None, description="Optional message to show to the user."
    )
    created_at: _schema_datetime.Timestamp = pydantic.Field(
        description="Timestamp when the registration was created.",
        validation_alias="createdAt",
        serialization_alias="createdAt",
    )

    def payload(self) -> "UserRegistration":
        return UserRegistration(
            status=self.status, message=self.message, created_at=self.created_at
        )


class RegisterUserOutput_EmailAlreadyExists(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    result: Literal["EmailAlreadyExists"] = "EmailAlreadyExists"


# Output of registering a new user.
type RegisterUserOutput = Annotated[
    RegisterUserOutput_Created
    | RegisterUserOutput_Pending
    | RegisterUserOutput_EmailAlreadyExists,
    pydantic.Discriminator("result"),
]


class UserRegistrationStatus_Pending(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    tag: Literal["Pending"] = "Pending"


class UserRegistrationStatus_Waiting(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    tag: Literal["Waiting"] = "Waiting"


class UserRegistrationStatus_Completed(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    tag: Literal["Completed"] = "Completed"


class UserRegistrationStatus_Failed(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    tag: Literal["Failed"] = "Failed"


type UserRegistrationStatus = Annotated[
    UserRegistrationStatus_Pending
    | UserRegistrationStatus_Waiting
    | UserRegistrationStatus_Completed
    | UserRegistrationStatus_Failed,
    pydantic.Discriminator("tag"),
]


class CompleteRegistrationOutput_Completed(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    result: Literal["Completed"] = "Completed"


class CompleteRegistrationOutput_Failed(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        populate_by_name=True, serialize_by_alias=True, defer_build=True
    )

    result: Literal["Failed"] = "Failed"


# Output of completing the registration of a user.
type CompleteRegistrationOutput = Annotated[
    CompleteRegistrationOutput_Completed | CompleteRegistrationOutput_Failed,
    pydantic.Discriminator("result"),
]
