# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import Annotated, Literal, TYPE_CHECKING, Union  # noqa: F401

import pydantic  # noqa: F401
import pydantic_core  # noqa: F401

if TYPE_CHECKING:
    from . import actor  # noqa: F401
    from . import datetime  # noqa: F401
    from . import devices  # noqa: F401
    from . import jwt  # noqa: F401
    from . import organizations  # noqa: F401


class UserId(str):
    """Unique ID of a user."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class UserTokenId(str):
    """Unique ID of a user token."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class UserToken(str):
    """User token."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class UserSessionId(str):
    """User session ID."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class UserSessionToken(str):
    """User session token."""

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: type, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return handler(str)


class QueryUsersAction(pydantic.BaseModel):
    """Query the users of the instance."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)


class QueryUsersOutput(pydantic.BaseModel):
    """Output of querying the users of the instance."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    users: list[QueryUsersItem] = pydantic.Field(description="List of users.")


class QueryUsersItem(pydantic.BaseModel):
    """User item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )
    email: str = pydantic.Field(description="Email of the user.")
    display_name: str | None = pydantic.Field(
        default=None,
        description="Name of the user.",
        validation_alias="displayName",
        serialization_alias="displayName",
    )
    is_admin: bool = pydantic.Field(
        description="Whether the user is an instance admin.",
        validation_alias="isAdmin",
        serialization_alias="isAdmin",
    )


class GetUserDetailsAction(pydantic.BaseModel):
    """Get information about a user."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )


class GetUserDetailsOutput(pydantic.BaseModel):
    """Information about the user."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )
    email: str = pydantic.Field(description="Email of the user.")
    display_name: str | None = pydantic.Field(
        default=None,
        description="Name of the user.",
        validation_alias="displayName",
        serialization_alias="displayName",
    )
    is_admin: bool = pydantic.Field(
        description="Whether the user is an instance admin.",
        validation_alias="isAdmin",
        serialization_alias="isAdmin",
    )


class CreateUserAction(pydantic.BaseModel):
    """Create a new user."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    email: str = pydantic.Field(description="Email of the user.")
    display_name: str | None = pydantic.Field(
        default=None,
        description="Name of the user.",
        validation_alias="displayName",
        serialization_alias="displayName",
    )
    password: str | None = pydantic.Field(
        default=None, description="Password of the user."
    )
    is_admin: bool | None = pydantic.Field(
        default=None,
        description="Whether the user is an instance admin.",
        validation_alias="isAdmin",
        serialization_alias="isAdmin",
    )


class CreateUserSuccess(pydantic.BaseModel):
    """User was created successfully."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )


class DeleteUserAction(pydantic.BaseModel):
    """Delete a user."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    user_id: UserId = pydantic.Field(
        description="ID of the user to delete.",
        validation_alias="userId",
        serialization_alias="userId",
    )


class SetUserDisplayNameAction(pydantic.BaseModel):
    """Set the display name of a user."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    user_id: UserId = pydantic.Field(
        description="ID of the user to update.",
        validation_alias="userId",
        serialization_alias="userId",
    )
    display_name: str = pydantic.Field(
        description="New name of the user.",
        validation_alias="displayName",
        serialization_alias="displayName",
    )


class SetUserPasswordAction(pydantic.BaseModel):
    """Set the password of a user."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )
    password: str = pydantic.Field(description="New password of the user.")


class SetUserIsAdminAction(pydantic.BaseModel):
    """Set whether the user is an instance administrator."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )
    is_admin: bool = pydantic.Field(
        description="Whether the user is an instance administrator.",
        validation_alias="isAdmin",
        serialization_alias="isAdmin",
    )


class ResetUserPasswordAction(pydantic.BaseModel):
    """Reset the password of a user.

    This will send an email to the user with a link to reset their password."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    email: str = pydantic.Field(description="Email of the user.")


class CompleteUserPasswordResetAction(pydantic.BaseModel):
    """Complete the password reset of a user."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    reset_token: jwt.Jwt = pydantic.Field(
        description="Token to use for password reset.",
        validation_alias="resetToken",
        serialization_alias="resetToken",
    )
    password: str = pydantic.Field(description="New password of the user.")


class QueryUserTokensAction(pydantic.BaseModel):
    """Query the tokens of a user."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )


class QueryUserTokensOutput(pydantic.BaseModel):
    """Output of querying the tokens of a user."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    tokens: list[QueryUserTokensItem] = pydantic.Field(
        description="List of user tokens."
    )


class QueryUserTokensItem(pydantic.BaseModel):
    """User token item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    token_id: UserTokenId = pydantic.Field(
        description="ID of the token.",
        validation_alias="tokenId",
        serialization_alias="tokenId",
    )
    created_at: datetime.Timestamp = pydantic.Field(
        description="Creation date of the token.",
        validation_alias="createdAt",
        serialization_alias="createdAt",
    )
    name: str | None = pydantic.Field(default=None, description="Name of the token.")


class QueryUserOrganizationsAction(pydantic.BaseModel):
    """Query the organizations of a user."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )


class QueryUserOrganizationsOutput(pydantic.BaseModel):
    """Output of querying the organizations of a user."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organizations: list[QueryUserOrganizationsItem] = pydantic.Field(
        description="List of organizations."
    )


class QueryUserOrganizationsItem(pydantic.BaseModel):
    """Organization item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: organizations.OrganizationId = pydantic.Field(
        description="ID of the organization.",
        validation_alias="organizationId",
        serialization_alias="organizationId",
    )
    name: str = pydantic.Field(description="Name of the organization.")
    requires_subscription: bool = pydantic.Field(
        description="Whether the organization requires a paid subscription.",
        validation_alias="requiresSubscription",
        serialization_alias="requiresSubscription",
    )
    subscription_plan_name: str | None = pydantic.Field(
        default=None,
        description="Name of the active subscription plan, if any.",
        validation_alias="subscriptionPlanName",
        serialization_alias="subscriptionPlanName",
    )


class QueryUserOrganizationInvitationsAction(pydantic.BaseModel):
    """Query the organization invitations of a user."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )


class QueryUserOrganizationInvitationsOutput(pydantic.BaseModel):
    """Output of querying the organization invitations of a user."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    invitations: list[QueryUserOrganizationInvitationsItem] = pydantic.Field(
        description="List of organization invitations."
    )


class QueryUserOrganizationInvitationsItem(pydantic.BaseModel):
    """Organization invitation item."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    invitation_id: organizations.OrganizationInvitationId = pydantic.Field(
        description="ID of the invitation.",
        validation_alias="invitationId",
        serialization_alias="invitationId",
    )
    organization: QueryUserOrganizationInvitationsItemOrganization = pydantic.Field(
        description="Information about the organization."
    )


class QueryUserOrganizationInvitationsItemOrganization(pydantic.BaseModel):
    """Organization invitation item organization."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    organization_id: organizations.OrganizationId = pydantic.Field(
        description="ID of the organization.",
        validation_alias="organizationId",
        serialization_alias="organizationId",
    )
    name: str = pydantic.Field(description="Name of the organization.")


class QueryUserSessionsAction(pydantic.BaseModel):
    """Query the sessions of a user."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )


class QueryUserSessionsOutput(pydantic.BaseModel):
    """Output of querying the sessions of a user."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    sessions: list[UserSession] = pydantic.Field(description="List of user sessions.")


class UserSession(pydantic.BaseModel):
    """User session."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    session_id: UserSessionId = pydantic.Field(
        description="ID of the session.",
        validation_alias="sessionId",
        serialization_alias="sessionId",
    )
    created_at: datetime.Timestamp = pydantic.Field(
        description="Creation date of the session.",
        validation_alias="createdAt",
        serialization_alias="createdAt",
    )
    expires_at: datetime.Timestamp = pydantic.Field(
        description="Expiration date of the session.",
        validation_alias="expiresAt",
        serialization_alias="expiresAt",
    )
    user_agent: str = pydantic.Field(
        description="User agent of the session.",
        validation_alias="userAgent",
        serialization_alias="userAgent",
    )


class AuthenticateWithUserTokenAction(pydantic.BaseModel):
    """Authenticate a user with a token."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    token: UserToken = pydantic.Field(description="Token.")


class AuthenticateWithUserTokenSuccess(pydantic.BaseModel):
    """Authentication with user token has been successful."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )
    actor: actor.Actor = pydantic.Field(
        description="Resulting actor to use for further actions."
    )


class AuthenticateWithSessionTokenAction(pydantic.BaseModel):
    """Authenticate a user with a session token."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    token: UserSessionToken = pydantic.Field(description="Session token.")


class AuthenticateWithSessionTokenSuccess(pydantic.BaseModel):
    """Authentication with session token has been successful."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )
    session_id: UserSessionId = pydantic.Field(
        description="ID of the session.",
        validation_alias="sessionId",
        serialization_alias="sessionId",
    )
    actor: actor.Actor = pydantic.Field(
        description="Resulting actor to use for further actions."
    )


class GetDevicePermissionsAction(pydantic.BaseModel):
    """Check the permissions of a user for a given device."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )
    device_id: devices.DeviceId = pydantic.Field(
        description="ID of the device.",
        validation_alias="deviceId",
        serialization_alias="deviceId",
    )


class GetDevicePermissionsOutput(pydantic.BaseModel):
    """Output of checking the permissions of a user for a given device."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    has_access: bool = pydantic.Field(
        description="Whether the user has access to the device.",
        validation_alias="hasAccess",
        serialization_alias="hasAccess",
    )


class CreateUserTokenAction(pydantic.BaseModel):
    """Create a user token."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )
    name: str | None = pydantic.Field(default=None, description="Name of the token.")


class CreateUserTokenOutput(pydantic.BaseModel):
    """Output of creating a user token."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    token_id: UserTokenId = pydantic.Field(
        description="ID of the token.",
        validation_alias="tokenId",
        serialization_alias="tokenId",
    )
    token: UserToken = pydantic.Field(description="Token.")


class DeleteUserTokenAction(pydantic.BaseModel):
    """Delete a user token."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    token_id: UserTokenId = pydantic.Field(
        description="ID of the token.",
        validation_alias="tokenId",
        serialization_alias="tokenId",
    )


class InitiateUserSessionAction(pydantic.BaseModel):
    """Initiate a user session."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    email: str = pydantic.Field(description="Email address of the user.")
    password: str = pydantic.Field(description="Password of the user.")
    user_agent: str = pydantic.Field(
        description="User agent of the session.",
        validation_alias="userAgent",
        serialization_alias="userAgent",
    )
    valid_for_secs: int | None = pydantic.Field(
        default=None,
        description="Number of seconds the session should be valid for.\n\nDefaults to 86400 (1 day).",
        validation_alias="validForSecs",
        serialization_alias="validForSecs",
    )


class InitiateUserSessionSuccess(pydantic.BaseModel):
    """Session was created successfully."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    user_id: UserId = pydantic.Field(
        description="ID of the user.",
        validation_alias="userId",
        serialization_alias="userId",
    )
    session_id: UserSessionId = pydantic.Field(
        description="ID of the session.",
        validation_alias="sessionId",
        serialization_alias="sessionId",
    )
    session_token: UserSessionToken = pydantic.Field(
        description="Session token.",
        validation_alias="sessionToken",
        serialization_alias="sessionToken",
    )


class TerminateUserSessionAction(pydantic.BaseModel):
    """Terminate a user session."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    session_id: UserSessionId = pydantic.Field(
        description="ID of the session.",
        validation_alias="sessionId",
        serialization_alias="sessionId",
    )


class CleanupExpiredUserSessionsAction(pydantic.BaseModel):
    """Cleanup expired user sessions."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)


class RegisterUserAction(pydantic.BaseModel):
    """Register a new user with an email and password."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    display_name: str | None = pydantic.Field(
        default=None,
        description="Name of the user.",
        validation_alias="displayName",
        serialization_alias="displayName",
    )
    email: str = pydantic.Field(description="Email address of the user.")
    password: str = pydantic.Field(description="Password of the user.")
    consented_to_terms: bool = pydantic.Field(
        description="Indicates whether the user has consented to the terms and conditions.\n\nThis must be `true` to register a user.",
        validation_alias="consentedToTerms",
        serialization_alias="consentedToTerms",
    )
    consented_to_marketing: bool | None = pydantic.Field(
        default=None,
        description="Indicates whether the user has consented to marketing communications.",
        validation_alias="consentedToMarketing",
        serialization_alias="consentedToMarketing",
    )


class UserRegistration(pydantic.BaseModel):
    """User registration."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    status: UserRegistrationStatus = pydantic.Field(description="Registration status.")
    message: str | None = pydantic.Field(
        default=None, description="Optional message to show to the user."
    )
    created_at: datetime.Timestamp = pydantic.Field(
        description="Timestamp when the registration was created.",
        validation_alias="createdAt",
        serialization_alias="createdAt",
    )


class ResendRegistrationEmailAction(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    email: str = pydantic.Field(description="Email address of the user.")


class CompleteRegistrationAction(pydantic.BaseModel):
    """Complete the registration of a user."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    activation_token: jwt.Jwt = pydantic.Field(
        description="Token to use for account activation.",
        validation_alias="activationToken",
        serialization_alias="activationToken",
    )


class AcceptOrganizationInvitationAction(pydantic.BaseModel):
    """Accept a organization invitation."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    invitation_id: organizations.OrganizationInvitationId = pydantic.Field(
        description="ID of the invitation.",
        validation_alias="invitationId",
        serialization_alias="invitationId",
    )


class CreateUserOutput_Created(CreateUserSuccess):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Created"] = "Created"


class CreateUserOutput_EmailAlreadyExists(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["EmailAlreadyExists"] = "EmailAlreadyExists"


# Output of creating a user.
type CreateUserOutput = Annotated[
    CreateUserOutput_Created | CreateUserOutput_EmailAlreadyExists,
    pydantic.Discriminator("result"),
]


class CompleteUserPasswordResetOutput_Completed(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Completed"] = "Completed"


class CompleteUserPasswordResetOutput_InvalidToken(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["InvalidToken"] = "InvalidToken"


# Output of completing the password reset of a user.
type CompleteUserPasswordResetOutput = Annotated[
    CompleteUserPasswordResetOutput_Completed
    | CompleteUserPasswordResetOutput_InvalidToken,
    pydantic.Discriminator("result"),
]


class AuthenticateWithUserTokenOutput_Invalid(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Invalid"] = "Invalid"


class AuthenticateWithUserTokenOutput_Authenticated(AuthenticateWithUserTokenSuccess):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Authenticated"] = "Authenticated"


# Output of authenticating a user with a token.
type AuthenticateWithUserTokenOutput = Annotated[
    AuthenticateWithUserTokenOutput_Invalid
    | AuthenticateWithUserTokenOutput_Authenticated,
    pydantic.Discriminator("result"),
]


class AuthenticateWithSessionTokenOutput_Invalid(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Invalid"] = "Invalid"


class AuthenticateWithSessionTokenOutput_Authenticated(
    AuthenticateWithSessionTokenSuccess
):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Authenticated"] = "Authenticated"


# Output of authenticating a user with a session token.
type AuthenticateWithSessionTokenOutput = Annotated[
    AuthenticateWithSessionTokenOutput_Invalid
    | AuthenticateWithSessionTokenOutput_Authenticated,
    pydantic.Discriminator("result"),
]


class InitiateUserSessionOutput_InvalidCredentials(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["InvalidCredentials"] = "InvalidCredentials"


class InitiateUserSessionOutput_Created(InitiateUserSessionSuccess):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Created"] = "Created"


# Output of initiating a user session.
type InitiateUserSessionOutput = Annotated[
    InitiateUserSessionOutput_InvalidCredentials | InitiateUserSessionOutput_Created,
    pydantic.Discriminator("result"),
]


class RegisterUserOutput_Created(UserRegistration):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Created"] = "Created"


class RegisterUserOutput_Pending(UserRegistration):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Pending"] = "Pending"


class RegisterUserOutput_EmailAlreadyExists(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["EmailAlreadyExists"] = "EmailAlreadyExists"


# Output of registering a new user.
type RegisterUserOutput = Annotated[
    RegisterUserOutput_Created
    | RegisterUserOutput_Pending
    | RegisterUserOutput_EmailAlreadyExists,
    pydantic.Discriminator("result"),
]


class UserRegistrationStatus_Pending(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    tag: Literal["Pending"] = "Pending"


class UserRegistrationStatus_Waiting(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    tag: Literal["Waiting"] = "Waiting"


class UserRegistrationStatus_Completed(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    tag: Literal["Completed"] = "Completed"


class UserRegistrationStatus_Failed(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    tag: Literal["Failed"] = "Failed"


type UserRegistrationStatus = Annotated[
    UserRegistrationStatus_Pending
    | UserRegistrationStatus_Waiting
    | UserRegistrationStatus_Completed
    | UserRegistrationStatus_Failed,
    pydantic.Discriminator("tag"),
]


class CompleteRegistrationOutput_Completed(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Completed"] = "Completed"


class CompleteRegistrationOutput_Failed(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    result: Literal["Failed"] = "Failed"


# Output of completing the registration of a user.
type CompleteRegistrationOutput = Annotated[
    CompleteRegistrationOutput_Completed | CompleteRegistrationOutput_Failed,
    pydantic.Discriminator("result"),
]
