# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import Annotated, Literal, TYPE_CHECKING, Union  # noqa: F401

import pydantic  # noqa: F401
import pydantic_core  # noqa: F401

if TYPE_CHECKING:
    from . import repositories as _schema_repositories  # noqa: F401


class IndexVersionDocumentsAction(pydantic.BaseModel):
    """Trigger indexing of every CycloneDX document referenced by the
    version's artifact assets via `relations.{sbom,vdr,vex}`.

    The hub fetches the referenced documents from the repository's S3
    storage and rebuilds the index for this version. The repository
    must have S3 configured."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    version_id: _schema_repositories.PackageVersionId = pydantic.Field(
        validation_alias="versionId", serialization_alias="versionId"
    )


class IndexVersionDocumentsOutput(pydantic.BaseModel):
    """Output of `IndexVersionDocumentsAction`."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    indexed: bool = pydantic.Field(
        description="Whether indexing actually ran (false when the feature flag is off\nor the version has no artifacts with `relations.*` metadata)."
    )
    artifact_count: int = pydantic.Field(
        description="Number of artifact assets whose documents were indexed.",
        validation_alias="artifactCount",
        serialization_alias="artifactCount",
    )
    document_count: int = pydantic.Field(
        description="Total number of documents (SBOM + VDR + VEX) ingested.",
        validation_alias="documentCount",
        serialization_alias="documentCount",
    )


class IndexPackageDocumentsAction(pydantic.BaseModel):
    """Trigger indexing of every CycloneDX document referenced by the
    package's metadata via `relations.{vex}` (typically just VEX).

    Mirrors `IndexVersionDocumentsAction`. Used after attaching a new
    package-level VEX asset and pointing the package's metadata at it."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    package_id: _schema_repositories.PackageId = pydantic.Field(
        validation_alias="packageId", serialization_alias="packageId"
    )


class IndexPackageDocumentsOutput(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    indexed: bool
    document_count: int = pydantic.Field(
        validation_alias="documentCount", serialization_alias="documentCount"
    )


class GetVersionVulnerabilityOverviewAction(pydantic.BaseModel):
    """Get the vulnerability overview for a package version: artifact list,
    SBOM/VDR/VEX descriptors per artifact, package-level VEX, and
    (when indexing is enabled) the rolled-up severity summary."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    version_id: _schema_repositories.PackageVersionId = pydantic.Field(
        validation_alias="versionId", serialization_alias="versionId"
    )


class GetVersionVulnerabilityOverviewOutput(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    version_id: _schema_repositories.PackageVersionId = pydantic.Field(
        validation_alias="versionId", serialization_alias="versionId"
    )
    indexing_enabled: bool = pydantic.Field(
        description="Whether the indexing feature is enabled for this organization.",
        validation_alias="indexingEnabled",
        serialization_alias="indexingEnabled",
    )
    artifacts: list[ArtifactDescriptor] = pydantic.Field(
        description="Per-artifact descriptors. Populated by walking each artifact's\n`relations.{sbom,vdr,vex}` metadata."
    )
    package_vex: list[AttachedVexDocument] = pydantic.Field(
        description="VEX documents inherited from the parent package's `relations.vex`.",
        validation_alias="packageVex",
        serialization_alias="packageVex",
    )
    severity_summary: SeveritySummary | None = pydantic.Field(
        default=None,
        description="Severity counts across the union of all artifact VDRs after VEX\nis applied. Not set when indexing is disabled.",
        validation_alias="severitySummary",
        serialization_alias="severitySummary",
    )
    component_count: int | None = pydantic.Field(
        default=None,
        description="Total component count across all artifact SBOMs (including\nduplicates if the same component is referenced from several\nartifacts). Not set when indexing is disabled.",
        validation_alias="componentCount",
        serialization_alias="componentCount",
    )


class ArtifactDescriptor(pydantic.BaseModel):
    """Per-artifact view of attached vulnerability documents."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    asset_id: _schema_repositories.RepositoryAssetId = pydantic.Field(
        validation_alias="assetId", serialization_alias="assetId"
    )
    filename: str
    sbom: AttachedDocument | None = pydantic.Field(
        default=None,
        description="SBOM document (the first valid `relations.sbom` entry).",
    )
    vdrs: list[AttachedVdrDocument] = pydantic.Field(
        description="All VDR documents referenced from `relations.vdr`."
    )
    vex: list[AttachedVexDocument] = pydantic.Field(
        description="All VEX documents referenced from `relations.vex`."
    )
    severity_summary: SeveritySummary | None = pydantic.Field(
        default=None,
        description="Severity rollup from this artifact's VDRs after VEX is applied.",
        validation_alias="severitySummary",
        serialization_alias="severitySummary",
    )
    component_count: int | None = pydantic.Field(
        default=None,
        description="Number of components extracted from this artifact's SBOM.",
        validation_alias="componentCount",
        serialization_alias="componentCount",
    )


class AttachedDocument(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    asset_id: _schema_repositories.RepositoryAssetId = pydantic.Field(
        validation_alias="assetId", serialization_alias="assetId"
    )
    repository_id: _schema_repositories.RepositoryId = pydantic.Field(
        validation_alias="repositoryId", serialization_alias="repositoryId"
    )
    filename: str
    size: int


class AttachedVdrDocument(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    document: AttachedDocument
    source_tool: str | None = pydantic.Field(
        default=None, validation_alias="sourceTool", serialization_alias="sourceTool"
    )
    severity_summary: SeveritySummary | None = pydantic.Field(
        default=None,
        validation_alias="severitySummary",
        serialization_alias="severitySummary",
    )


class AttachedVexDocument(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    document: AttachedDocument
    origin: VexStatementOrigin
    statement_count: int | None = pydantic.Field(
        default=None,
        validation_alias="statementCount",
        serialization_alias="statementCount",
    )


class SeveritySummary(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    critical: int
    high: int
    medium: int
    low: int
    info: int
    unknown: int


class QueryPackageVersionComponentsAction(pydantic.BaseModel):
    """Query the components extracted from a package version's SBOMs."""

    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    version_id: _schema_repositories.PackageVersionId = pydantic.Field(
        validation_alias="versionId", serialization_alias="versionId"
    )
    artifact_filename: str | None = pydantic.Field(
        default=None,
        description="Optional filter: only include components from this artifact's SBOM.",
        validation_alias="artifactFilename",
        serialization_alias="artifactFilename",
    )
    search: str | None = pydantic.Field(
        default=None,
        description="Optional case-insensitive substring filter over name / purl / license.",
    )
    component_type: str | None = pydantic.Field(
        default=None,
        description="Optional component-type filter (e.g. `library`, `application`).",
        validation_alias="componentType",
        serialization_alias="componentType",
    )


class QueryPackageVersionComponentsOutput(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    indexing_enabled: bool = pydantic.Field(
        validation_alias="indexingEnabled", serialization_alias="indexingEnabled"
    )
    components: list[PackageVersionComponent]


class PackageVersionComponent(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    artifact_filename: str = pydantic.Field(
        description="Filename of the artifact asset whose SBOM this component came from.",
        validation_alias="artifactFilename",
        serialization_alias="artifactFilename",
    )
    bom_ref: str = pydantic.Field(
        validation_alias="bomRef", serialization_alias="bomRef"
    )
    purl: str | None = pydantic.Field(default=None)
    name: str
    version: str | None = pydantic.Field(default=None)
    kind: str = pydantic.Field(validation_alias="type", serialization_alias="type")
    licenses: list[str]
    supplier: str | None = pydantic.Field(default=None)
    description: str | None = pydantic.Field(default=None)
    vuln_summary: SeveritySummary | None = pydantic.Field(
        default=None,
        description="Vulnerability counts after VEX application.",
        validation_alias="vulnSummary",
        serialization_alias="vulnSummary",
    )


class QueryPackageVersionFindingsAction(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    version_id: _schema_repositories.PackageVersionId = pydantic.Field(
        validation_alias="versionId", serialization_alias="versionId"
    )
    artifact_filename: str | None = pydantic.Field(
        default=None,
        description="Optional artifact-filename filter.",
        validation_alias="artifactFilename",
        serialization_alias="artifactFilename",
    )
    min_severity: str | None = pydantic.Field(
        default=None,
        description="Optional severity floor.",
        validation_alias="minSeverity",
        serialization_alias="minSeverity",
    )


class QueryPackageVersionFindingsOutput(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    indexing_enabled: bool = pydantic.Field(
        validation_alias="indexingEnabled", serialization_alias="indexingEnabled"
    )
    findings: list[PackageVersionFinding]


class PackageVersionFinding(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True, serialize_by_alias=True)

    artifact_filename: str = pydantic.Field(
        validation_alias="artifactFilename", serialization_alias="artifactFilename"
    )
    component_purl: str = pydantic.Field(
        validation_alias="componentPurl", serialization_alias="componentPurl"
    )
    component_name: str = pydantic.Field(
        validation_alias="componentName", serialization_alias="componentName"
    )
    component_version: str | None = pydantic.Field(
        default=None,
        validation_alias="componentVersion",
        serialization_alias="componentVersion",
    )
    vulnerability_id: str = pydantic.Field(
        validation_alias="vulnerabilityId", serialization_alias="vulnerabilityId"
    )
    severity: str
    cvss_score: float | None = pydantic.Field(
        default=None, validation_alias="cvssScore", serialization_alias="cvssScore"
    )
    description: str | None = pydantic.Field(default=None)
    source_tool: str | None = pydantic.Field(
        default=None, validation_alias="sourceTool", serialization_alias="sourceTool"
    )
    effective_state: str = pydantic.Field(
        description="Effective VEX state. Defaults to `in_triage` when no statement applies.",
        validation_alias="effectiveState",
        serialization_alias="effectiveState",
    )
    justification: str | None = pydantic.Field(default=None)
    detail: str | None = pydantic.Field(default=None)
    state_origin: VexStatementOrigin | None = pydantic.Field(
        default=None, validation_alias="stateOrigin", serialization_alias="stateOrigin"
    )


class VexStatementOrigin_Operator(pydantic.RootModel[Literal["Operator"]]):
    pass


class VexStatementOrigin_Vendor(pydantic.RootModel[Literal["Vendor"]]):
    pass


class VexStatementOrigin_Scanner(pydantic.RootModel[Literal["Scanner"]]):
    pass


# Origin of a VEX statement, used by the effective-state precedence
# rule (operator > vendor > scanner).
type VexStatementOrigin = (
    VexStatementOrigin_Operator | VexStatementOrigin_Vendor | VexStatementOrigin_Scanner
)
