# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import overload

import pydantic

from .api_types import actor
from .api_types import audit
from .api_types import cluster
from .api_types import devices
from .api_types import fleet
from .api_types import instance
from .api_types import jobs
from .api_types import organizations
from .api_types import outputs
from .api_types import projects
from .api_types import repositories
from .api_types import users


_ACTION_REGISTRY: dict[type, tuple[str, pydantic.TypeAdapter]] = {  # type: ignore[type-arg]
    users.QueryUsersAction: (
        "users_Query",
        pydantic.TypeAdapter(users.QueryUsersOutput),
    ),
    users.GetUserDetailsAction: (
        "users_GetDetails",
        pydantic.TypeAdapter(users.GetUserDetailsOutput),
    ),
    users.CreateUserAction: (
        "users_Create",
        pydantic.TypeAdapter(users.CreateUserOutput),
    ),
    users.DeleteUserAction: ("users_Delete", pydantic.TypeAdapter(outputs.Empty)),
    users.SetUserDisplayNameAction: (
        "users_SetDisplayName",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    users.SetUserPasswordAction: (
        "users_SetPassword",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    users.SetUserIsAdminAction: (
        "users_SetIsAdmin",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    users.ResetUserPasswordAction: (
        "users_ResetPassword",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    users.CompleteUserPasswordResetAction: (
        "users_CompletePasswordReset",
        pydantic.TypeAdapter(users.CompleteUserPasswordResetOutput),
    ),
    users.QueryUserTokensAction: (
        "users_QueryTokens",
        pydantic.TypeAdapter(users.QueryUserTokensOutput),
    ),
    users.QueryUserOrganizationsAction: (
        "users_QueryOrganizations",
        pydantic.TypeAdapter(users.QueryUserOrganizationsOutput),
    ),
    users.QueryUserOrganizationInvitationsAction: (
        "users_QueryOrganizationInvitations",
        pydantic.TypeAdapter(users.QueryUserOrganizationInvitationsOutput),
    ),
    users.QueryUserSessionsAction: (
        "users_QuerySessions",
        pydantic.TypeAdapter(users.QueryUserSessionsOutput),
    ),
    users.AuthenticateWithUserTokenAction: (
        "users_AuthenticateWithToken",
        pydantic.TypeAdapter(users.AuthenticateWithUserTokenOutput),
    ),
    users.AuthenticateWithSessionTokenAction: (
        "users_AuthenticateWithSessionToken",
        pydantic.TypeAdapter(users.AuthenticateWithSessionTokenOutput),
    ),
    users.GetDevicePermissionsAction: (
        "users_GetDevicePermissions",
        pydantic.TypeAdapter(users.GetDevicePermissionsOutput),
    ),
    users.CreateUserTokenAction: (
        "users_CreateToken",
        pydantic.TypeAdapter(users.CreateUserTokenOutput),
    ),
    users.DeleteUserTokenAction: (
        "users_DeleteToken",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    users.InitiateUserSessionAction: (
        "users_InitiateSession",
        pydantic.TypeAdapter(users.InitiateUserSessionOutput),
    ),
    users.TerminateUserSessionAction: (
        "users_TerminateSession",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    users.CleanupExpiredUserSessionsAction: (
        "users_CleanupExpiredSessions",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    users.RegisterUserAction: (
        "users_Register",
        pydantic.TypeAdapter(users.RegisterUserOutput),
    ),
    users.ResendRegistrationEmailAction: (
        "users_ResendRegistrationEmail",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    users.CompleteRegistrationAction: (
        "users_CompleteRegistration",
        pydantic.TypeAdapter(users.CompleteRegistrationOutput),
    ),
    users.AcceptOrganizationInvitationAction: (
        "users_AcceptOrganizationInvitation",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    organizations.QueryOrganizationsAction: (
        "organizations_Query",
        pydantic.TypeAdapter(organizations.QueryOrganizationsOutput),
    ),
    organizations.QueryOrganizationMembersAction: (
        "organizations_QueryMembers",
        pydantic.TypeAdapter(organizations.QueryOrganizationMembersOutput),
    ),
    organizations.QueryOrganizationProjectsAction: (
        "organizations_QueryProjects",
        pydantic.TypeAdapter(organizations.QueryOrganizationProjectsOutput),
    ),
    organizations.QueryOrganizationRepositoriesAction: (
        "organizations_QueryRepositories",
        pydantic.TypeAdapter(organizations.QueryOrganizationRepositoriesOutput),
    ),
    organizations.QueryOrganizationInvitationsAction: (
        "organizations_QueryInvitations",
        pydantic.TypeAdapter(organizations.QueryOrganizationInvitationsOutput),
    ),
    organizations.CreateOrganizationAction: (
        "organizations_Create",
        pydantic.TypeAdapter(organizations.CreateOrganizationOutput),
    ),
    organizations.DeleteOrganizationAction: (
        "organizations_Delete",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    organizations.AddOrganizationMemberAction: (
        "organizations_AddMember",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    organizations.RemoveOrganizationMemberAction: (
        "organizations_RemoveMember",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    organizations.SetOrganizationMemberIsAdminAction: (
        "organizations_SetMemberIsAdmin",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    organizations.InviteOrganizationMemberAction: (
        "organizations_InviteMember",
        pydantic.TypeAdapter(organizations.InviteOrganizationMemberOutput),
    ),
    organizations.DeleteOrganizationInvitationAction: (
        "organizations_DeleteInvitation",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    organizations.QueryOrganizationAuditLogAction: (
        "organizations_QueryAuditLog",
        pydantic.TypeAdapter(organizations.QueryOrganizationAuditLogOutput),
    ),
    projects.QueryProjectsAction: (
        "projects_Query",
        pydantic.TypeAdapter(projects.QueryProjectsOutput),
    ),
    projects.GetProjectDetailsAction: (
        "projects_GetDetails",
        pydantic.TypeAdapter(projects.GetProjectDetailsOutput),
    ),
    projects.CreateProjectAction: (
        "projects_Create",
        pydantic.TypeAdapter(projects.CreateProjectOutput),
    ),
    projects.DeleteProjectAction: (
        "projects_Delete",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    projects.QueryProjectDevicesAction: (
        "projects_QueryDevices",
        pydantic.TypeAdapter(projects.QueryProjectDevicesOutput),
    ),
    projects.QueryProjectDeploymentTokensAction: (
        "projects_QueryDeploymentTokens",
        pydantic.TypeAdapter(projects.QueryProjectDeploymentTokensOutput),
    ),
    projects.QueryProjectRepositoriesAction: (
        "projects_QueryLinkedRepositories",
        pydantic.TypeAdapter(projects.QueryProjectRepositoriesOutput),
    ),
    projects.SetProjectNameAction: (
        "projects_SetName",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    projects.CreateDeploymentTokenAction: (
        "projects_CreateDeploymentToken",
        pydantic.TypeAdapter(projects.CreateDeploymentTokenOutput),
    ),
    projects.DeleteDeploymentTokenAction: (
        "projects_DeleteDeploymentToken",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    projects.SetDeploymentTokenFlagsAction: (
        "projects_SetDeploymentTokenFlags",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    projects.QueryAuditLogEventsAction: (
        "projects_QueryAuditLog",
        pydantic.TypeAdapter(projects.QueryAuditLogEventsOutput),
    ),
    projects.AddProjectRepositoryAction: (
        "projects_LinkRepository",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    projects.RemoveProjectRepositoryAction: (
        "projects_UnlinkRepository",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    projects.GetProjectOtlpConfigAction: (
        "projects_GetOtlpConfig",
        pydantic.TypeAdapter(projects.GetProjectOtlpConfigOutput),
    ),
    projects.SetProjectOtlpConfigAction: (
        "projects_SetOtlpConfig",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    devices.QueryDevicesAction: (
        "devices_Query",
        pydantic.TypeAdapter(devices.QueryDevicesOutput),
    ),
    devices.GetDeviceDetailsAction: (
        "devices_GetDetails",
        pydantic.TypeAdapter(devices.GetDeviceDetailsOutput),
    ),
    devices.CreateDeviceAction: (
        "devices_Create",
        pydantic.TypeAdapter(devices.CreateDeviceOutput),
    ),
    devices.DeleteDeviceAction: ("devices_Delete", pydantic.TypeAdapter(outputs.Empty)),
    devices.SetDeviceNameAction: (
        "devices_SetName",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    devices.IssueDeviceTokenAction: (
        "devices_IssueDeviceToken",
        pydantic.TypeAdapter(devices.IssueDeviceTokenOutput),
    ),
    devices.ValidateDeviceTokenAction: (
        "devices_ValidateDeviceToken",
        pydantic.TypeAdapter(devices.ValidateDeviceTokenOutput),
    ),
    devices.AuthenticateDeviceAction: (
        "devices_Authenticate",
        pydantic.TypeAdapter(devices.AuthenticateDeviceOutput),
    ),
    devices.AddDeviceCertificateAction: (
        "devices_AddCertificate",
        pydantic.TypeAdapter(devices.AddDeviceCertificateOutput),
    ),
    devices.DeleteDeviceCertificateAction: (
        "devices_DeleteCertificate",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    devices.SetDeviceCertificateStatusAction: (
        "devices_SetCertificateStatus",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    devices.RegisterDeviceConnectionAction: (
        "devices_RegisterConnection",
        pydantic.TypeAdapter(devices.RegisterDeviceConnectionOutput),
    ),
    devices.UnregisterDeviceConnectionAction: (
        "devices_UnregisterConnection",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    devices.QueryDeviceConnectionsAction: (
        "devices_QueryConnections",
        pydantic.TypeAdapter(devices.QueryDeviceConnectionsOutput),
    ),
    devices.IssueDeviceHttpProxyTokenAction: (
        "devices_IssueHttpProxyToken",
        pydantic.TypeAdapter(devices.IssueDeviceHttpProxyTokenOutput),
    ),
    devices.ValidateDeviceHttpProxyTokenAction: (
        "devices_ValidateHttpProxyToken",
        pydantic.TypeAdapter(devices.ValidateDeviceHttpProxyTokenOutput),
    ),
    devices.PublishDeviceEventsAction: (
        "devices_PublishEvents",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    devices.QueryDeviceEventsAction: (
        "devices_QueryEvents",
        pydantic.TypeAdapter(devices.QueryDeviceEventsOutput),
    ),
    devices.SetDevicePropertyAction: (
        "devices_SetProperty",
        pydantic.TypeAdapter(devices.SetDevicePropertyOutput),
    ),
    devices.GetDevicePropertyAction: (
        "devices_GetProperty",
        pydantic.TypeAdapter(devices.GetDevicePropertyOutput),
    ),
    devices.RemoveDevicePropertyAction: (
        "devices_RemoveProperty",
        pydantic.TypeAdapter(devices.RemoveDevicePropertyOutput),
    ),
    devices.QueryDevicePropertiesAction: (
        "devices_QueryProperties",
        pydantic.TypeAdapter(devices.QueryDevicePropertiesOutput),
    ),
    devices.QueryDeviceAuditLogAction: (
        "devices_QueryAuditLog",
        pydantic.TypeAdapter(devices.QueryDeviceAuditLogOutput),
    ),
    devices.QueryDeviceCommandsAction: (
        "devices_QueryCommands",
        pydantic.TypeAdapter(devices.QueryDeviceCommandsOutput),
    ),
    fleet.SetFleetPropertyAction: (
        "fleet_SetProperty",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    fleet.GetFleetPropertyAction: (
        "fleet_GetProperty",
        pydantic.TypeAdapter(fleet.GetFleetPropertyOutput),
    ),
    fleet.RemoveFleetPropertyAction: (
        "fleet_RemoveProperty",
        pydantic.TypeAdapter(fleet.RemoveFleetPropertyOutput),
    ),
    fleet.QueryFleetPropertiesAction: (
        "fleet_QueryProperties",
        pydantic.TypeAdapter(fleet.QueryFleetPropertiesOutput),
    ),
    fleet.DefineComputedFleetPropertyAction: (
        "fleet_DefineComputedProperty",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    fleet.QueryComputedFleetPropertyDefinitionsAction: (
        "fleet_QueryComputedPropertyDefinitions",
        pydantic.TypeAdapter(fleet.QueryComputedFleetPropertyDefinitionsOutput),
    ),
    repositories.ResolveRepositoryNameAction: (
        "repositories_ResolveName",
        pydantic.TypeAdapter(repositories.ResolveRepositoryNameOutput),
    ),
    repositories.GetRepositoryDetailsAction: (
        "repositories_GetDetails",
        pydantic.TypeAdapter(repositories.GetRepositoryDetailsOutput),
    ),
    repositories.CreateRepositoryAction: (
        "repositories_Create",
        pydantic.TypeAdapter(repositories.CreateRepositoryOutput),
    ),
    repositories.DeleteRepositoryAction: (
        "repositories_Delete",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.SetRepositoryVisibilityAction: (
        "repositories_SetVisibility",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.SetRepositoryDisplayNameAction: (
        "repositories_SetDisplayName",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.SetRepositoryPublicNameAction: (
        "repositories_SetPublicName",
        pydantic.TypeAdapter(repositories.SetRepositoryPublicNameOutput),
    ),
    repositories.QueryRepositoryPackagesAction: (
        "repositories_QueryPackages",
        pydantic.TypeAdapter(repositories.QueryRepositoryPackagesOutput),
    ),
    repositories.QueryRepositoryAssetsAction: (
        "repositories_QueryAssets",
        pydantic.TypeAdapter(repositories.QueryRepositoryAssetsOutput),
    ),
    repositories.QueryRepositoryProjectsAction: (
        "repositories_QueryLinkedProjects",
        pydantic.TypeAdapter(repositories.QueryRepositoryProjectsOutput),
    ),
    repositories.ResolvePackageByPathAction: (
        "repositories_ResolvePackageByPath",
        pydantic.TypeAdapter(repositories.ResolvePackageByPathOutput),
    ),
    repositories.GetPackageDetailsAction: (
        "repositories_GetPackageDetails",
        pydantic.TypeAdapter(repositories.GetPackageDetailsOutput),
    ),
    repositories.CreatePackageAction: (
        "repositories_CreatePackage",
        pydantic.TypeAdapter(repositories.CreatePackageOutput),
    ),
    repositories.DeletePackageAction: (
        "repositories_DeletePackage",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.SetPackageNameAction: (
        "repositories_SetPackageName",
        pydantic.TypeAdapter(repositories.SetPackageNameOutput),
    ),
    repositories.SetPackageKindAction: (
        "repositories_SetPackageKind",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.SetPackageMetadataAction: (
        "repositories_SetPackageMetadata",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.QueryPackageVersionsAction: (
        "repositories_QueryPackageVersions",
        pydantic.TypeAdapter(repositories.QueryPackageVersionsOutput),
    ),
    repositories.ResolvePackageVersionByPathAction: (
        "repositories_ResolveVersionByPath",
        pydantic.TypeAdapter(repositories.ResolvePackageVersionByPathOutput),
    ),
    repositories.GetPackageVersionDetailsAction: (
        "repositories_GetVersionDetails",
        pydantic.TypeAdapter(repositories.GetPackageVersionDetailsOutput),
    ),
    repositories.CreatePackageVersionAction: (
        "repositories_CreateVersion",
        pydantic.TypeAdapter(repositories.CreatePackageVersionOutput),
    ),
    repositories.DeletePackageVersionAction: (
        "repositories_DeleteVersion",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.SetPackageVersionNameAction: (
        "repositories_SetVersionName",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.SetPackageVersionMetadataAction: (
        "repositories_SetVersionMetadata",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.AddPackageVersionAssetAction: (
        "repositories_AddVersionAsset",
        pydantic.TypeAdapter(repositories.AddPackageVersionAssetOutput),
    ),
    repositories.RemovePackageVersionAssetAction: (
        "repositories_RemoveVersionAsset",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.SetPackageVersionAssetMetadataAction: (
        "repositories_SetVersionAssetMetadata",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.TagPackageVersionAction: (
        "repositories_TagVersion",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.UntagPackageVersionAction: (
        "repositories_UntagVersion",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.ResolvePackageVersionAssetByPathAction: (
        "repositories_ResolveVersionAssetByPath",
        pydantic.TypeAdapter(repositories.ResolvePackageVersionAssetByPathOutput),
    ),
    repositories.SetRepositoryS3ConfigAction: (
        "repositories_SetS3Config",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.GetRepositoryS3ConfigAction: (
        "repositories_GetS3Config",
        pydantic.TypeAdapter(repositories.GetRepositoryS3ConfigOutput),
    ),
    repositories.GetAssetDetailsAction: (
        "repositories_GetAssetDetails",
        pydantic.TypeAdapter(repositories.GetAssetDetailsOutput),
    ),
    repositories.CreateAssetAction: (
        "repositories_CreateAsset",
        pydantic.TypeAdapter(repositories.CreateAssetOutput),
    ),
    repositories.DeleteAssetAction: (
        "repositories_DeleteAsset",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.IssueAssetDownloadUrlAction: (
        "repositories_IssueAssetDownloadUrl",
        pydantic.TypeAdapter(repositories.IssueAssetDownloadUrlOutput),
    ),
    repositories.IssueAssetUploadUrlAction: (
        "repositories_IssueAssetUploadUrl",
        pydantic.TypeAdapter(repositories.IssueAssetUploadUrlOutput),
    ),
    repositories.QueryAuditLogEventsAction: (
        "repositories_QueryAuditLog",
        pydantic.TypeAdapter(repositories.QueryAuditLogEventsOutput),
    ),
    audit.QueryAuditLogEventsAction: (
        "audit_QueryAuditLogEvents",
        pydantic.TypeAdapter(audit.QueryAuditLogEventsOutput),
    ),
    audit.QueryAuditLogActionsAction: (
        "audit_QueryAuditLogActions",
        pydantic.TypeAdapter(audit.QueryAuditLogActionsOutput),
    ),
    jobs.QueryJobsAction: ("jobs_Query", pydantic.TypeAdapter(jobs.QueryJobsOutput)),
    instance.GetInstanceStatisticsAction: (
        "instance_GetStatistics",
        pydantic.TypeAdapter(instance.GetInstanceStatisticsOutput),
    ),
    instance.GetInstanceSettingsRawAction: (
        "instance_GetSettingsRaw",
        pydantic.TypeAdapter(instance.GetInstanceSettingsRawOutput),
    ),
    instance.SetInstanceSettingRawAction: (
        "instance_SetSettingRaw",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    cluster.GetClusterDetailsAction: (
        "cluster_GetDetails",
        pydantic.TypeAdapter(cluster.GetClusterDetailsOutput),
    ),
    cluster.RegisterClusterNodeAction: (
        "cluster_RegisterNode",
        pydantic.TypeAdapter(cluster.RegisterClusterNodeOutput),
    ),
    cluster.ReportClusterNodeHeartbeatAction: (
        "cluster_ReportNodeHeartbeat",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    cluster.CleanupInactiveClusterNodesAction: (
        "cluster_CleanupInactiveNodes",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    actor.GetActorAction: (
        "actor_GetActor",
        pydantic.TypeAdapter(actor.GetActorOutput),
    ),
}


class _SyncExecuteMixin:
    """Type overloads for the synchronous client."""

    @overload
    def execute(self, action: users.QueryUsersAction) -> users.QueryUsersOutput:
        """Query the users of the instance."""
        ...

    @overload
    def execute(self, action: users.GetUserDetailsAction) -> users.GetUserDetailsOutput:
        """Get information about a user."""
        ...

    @overload
    def execute(self, action: users.CreateUserAction) -> users.CreateUserOutput:
        """Create a new user."""
        ...

    @overload
    def execute(self, action: users.DeleteUserAction) -> outputs.Empty:
        """Delete a user."""
        ...

    @overload
    def execute(self, action: users.SetUserDisplayNameAction) -> outputs.Empty:
        """Set the display name of a user."""
        ...

    @overload
    def execute(self, action: users.SetUserPasswordAction) -> outputs.Empty:
        """Set the password of a user."""
        ...

    @overload
    def execute(self, action: users.SetUserIsAdminAction) -> outputs.Empty:
        """Set whether the user is an instance administrator."""
        ...

    @overload
    def execute(self, action: users.ResetUserPasswordAction) -> outputs.Empty:
        """Reset the password of a user.

        This will send an email to the user with a link to reset their password."""
        ...

    @overload
    def execute(
        self, action: users.CompleteUserPasswordResetAction
    ) -> users.CompleteUserPasswordResetOutput:
        """Complete the password reset of a user."""
        ...

    @overload
    def execute(
        self, action: users.QueryUserTokensAction
    ) -> users.QueryUserTokensOutput:
        """Query the tokens of a user."""
        ...

    @overload
    def execute(
        self, action: users.QueryUserOrganizationsAction
    ) -> users.QueryUserOrganizationsOutput:
        """Query the organizations of a user."""
        ...

    @overload
    def execute(
        self, action: users.QueryUserOrganizationInvitationsAction
    ) -> users.QueryUserOrganizationInvitationsOutput:
        """Query the organization invitations of a user."""
        ...

    @overload
    def execute(
        self, action: users.QueryUserSessionsAction
    ) -> users.QueryUserSessionsOutput:
        """Query the sessions of a user."""
        ...

    @overload
    def execute(
        self, action: users.AuthenticateWithUserTokenAction
    ) -> users.AuthenticateWithUserTokenOutput:
        """Authenticate a user with a token."""
        ...

    @overload
    def execute(
        self, action: users.AuthenticateWithSessionTokenAction
    ) -> users.AuthenticateWithSessionTokenOutput:
        """Authenticate a user with a session token."""
        ...

    @overload
    def execute(
        self, action: users.GetDevicePermissionsAction
    ) -> users.GetDevicePermissionsOutput:
        """Check the permissions of a user for a given device."""
        ...

    @overload
    def execute(
        self, action: users.CreateUserTokenAction
    ) -> users.CreateUserTokenOutput:
        """Create a user token."""
        ...

    @overload
    def execute(self, action: users.DeleteUserTokenAction) -> outputs.Empty:
        """Delete a user token."""
        ...

    @overload
    def execute(
        self, action: users.InitiateUserSessionAction
    ) -> users.InitiateUserSessionOutput:
        """Initiate a user session."""
        ...

    @overload
    def execute(self, action: users.TerminateUserSessionAction) -> outputs.Empty:
        """Terminate a user session."""
        ...

    @overload
    def execute(self, action: users.CleanupExpiredUserSessionsAction) -> outputs.Empty:
        """Cleanup expired user sessions."""
        ...

    @overload
    def execute(self, action: users.RegisterUserAction) -> users.RegisterUserOutput:
        """Register a new user with an email and password."""
        ...

    @overload
    def execute(self, action: users.ResendRegistrationEmailAction) -> outputs.Empty:
        """"""
        ...

    @overload
    def execute(
        self, action: users.CompleteRegistrationAction
    ) -> users.CompleteRegistrationOutput:
        """Complete the registration of a user."""
        ...

    @overload
    def execute(
        self, action: users.AcceptOrganizationInvitationAction
    ) -> outputs.Empty:
        """Accept a organization invitation."""
        ...

    @overload
    def execute(
        self, action: organizations.QueryOrganizationsAction
    ) -> organizations.QueryOrganizationsOutput:
        """Query the organizations of the instance."""
        ...

    @overload
    def execute(
        self, action: organizations.QueryOrganizationMembersAction
    ) -> organizations.QueryOrganizationMembersOutput:
        """Query the members of an organization."""
        ...

    @overload
    def execute(
        self, action: organizations.QueryOrganizationProjectsAction
    ) -> organizations.QueryOrganizationProjectsOutput:
        """Query the projects of an organization."""
        ...

    @overload
    def execute(
        self, action: organizations.QueryOrganizationRepositoriesAction
    ) -> organizations.QueryOrganizationRepositoriesOutput:
        """Query the repositories of an organization."""
        ...

    @overload
    def execute(
        self, action: organizations.QueryOrganizationInvitationsAction
    ) -> organizations.QueryOrganizationInvitationsOutput:
        """Query the invitations of an organization."""
        ...

    @overload
    def execute(
        self, action: organizations.CreateOrganizationAction
    ) -> organizations.CreateOrganizationOutput:
        """Create an organization."""
        ...

    @overload
    def execute(self, action: organizations.DeleteOrganizationAction) -> outputs.Empty:
        """Delete an organization."""
        ...

    @overload
    def execute(
        self, action: organizations.AddOrganizationMemberAction
    ) -> outputs.Empty:
        """Add a user to an organization."""
        ...

    @overload
    def execute(
        self, action: organizations.RemoveOrganizationMemberAction
    ) -> outputs.Empty:
        """Remove a user from an organization."""
        ...

    @overload
    def execute(
        self, action: organizations.SetOrganizationMemberIsAdminAction
    ) -> outputs.Empty:
        """Set whether the user is an administrator of the organization."""
        ...

    @overload
    def execute(
        self, action: organizations.InviteOrganizationMemberAction
    ) -> organizations.InviteOrganizationMemberOutput:
        """Invite a user to an organization."""
        ...

    @overload
    def execute(
        self, action: organizations.DeleteOrganizationInvitationAction
    ) -> outputs.Empty:
        """Delete an invitation to an organization."""
        ...

    @overload
    def execute(
        self, action: organizations.QueryOrganizationAuditLogAction
    ) -> organizations.QueryOrganizationAuditLogOutput:
        """Query the audit log of an organization."""
        ...

    @overload
    def execute(
        self, action: projects.QueryProjectsAction
    ) -> projects.QueryProjectsOutput:
        """Query the projects of the instance."""
        ...

    @overload
    def execute(
        self, action: projects.GetProjectDetailsAction
    ) -> projects.GetProjectDetailsOutput:
        """Get information about a project."""
        ...

    @overload
    def execute(
        self, action: projects.CreateProjectAction
    ) -> projects.CreateProjectOutput:
        """Create a new project."""
        ...

    @overload
    def execute(self, action: projects.DeleteProjectAction) -> outputs.Empty:
        """Delete a project."""
        ...

    @overload
    def execute(
        self, action: projects.QueryProjectDevicesAction
    ) -> projects.QueryProjectDevicesOutput:
        """Query the devices of a project."""
        ...

    @overload
    def execute(
        self, action: projects.QueryProjectDeploymentTokensAction
    ) -> projects.QueryProjectDeploymentTokensOutput:
        """Query the deployment tokens of a project."""
        ...

    @overload
    def execute(
        self, action: projects.QueryProjectRepositoriesAction
    ) -> projects.QueryProjectRepositoriesOutput:
        """Query repositories of a project."""
        ...

    @overload
    def execute(self, action: projects.SetProjectNameAction) -> outputs.Empty:
        """Set the name of a project."""
        ...

    @overload
    def execute(
        self, action: projects.CreateDeploymentTokenAction
    ) -> projects.CreateDeploymentTokenOutput:
        """Create a deployment token."""
        ...

    @overload
    def execute(self, action: projects.DeleteDeploymentTokenAction) -> outputs.Empty:
        """Delete a deployment token."""
        ...

    @overload
    def execute(self, action: projects.SetDeploymentTokenFlagsAction) -> outputs.Empty:
        """Set the flags of a deployment token."""
        ...

    @overload
    def execute(
        self, action: projects.QueryAuditLogEventsAction
    ) -> projects.QueryAuditLogEventsOutput:
        """Query the audit log of the project."""
        ...

    @overload
    def execute(self, action: projects.AddProjectRepositoryAction) -> outputs.Empty:
        """Add a repository to the project."""
        ...

    @overload
    def execute(self, action: projects.RemoveProjectRepositoryAction) -> outputs.Empty:
        """Remove a repository from the project."""
        ...

    @overload
    def execute(
        self, action: projects.GetProjectOtlpConfigAction
    ) -> projects.GetProjectOtlpConfigOutput:
        """Get the OTLP event forwarding configuration for a project."""
        ...

    @overload
    def execute(self, action: projects.SetProjectOtlpConfigAction) -> outputs.Empty:
        """Set the OTLP event forwarding configuration for a project."""
        ...

    @overload
    def execute(self, action: devices.QueryDevicesAction) -> devices.QueryDevicesOutput:
        """Query the devices of the instance."""
        ...

    @overload
    def execute(
        self, action: devices.GetDeviceDetailsAction
    ) -> devices.GetDeviceDetailsOutput:
        """Get information about a device."""
        ...

    @overload
    def execute(self, action: devices.CreateDeviceAction) -> devices.CreateDeviceOutput:
        """Create a new device."""
        ...

    @overload
    def execute(self, action: devices.DeleteDeviceAction) -> outputs.Empty:
        """Delete a device."""
        ...

    @overload
    def execute(self, action: devices.SetDeviceNameAction) -> outputs.Empty:
        """Set the name of a device."""
        ...

    @overload
    def execute(
        self, action: devices.IssueDeviceTokenAction
    ) -> devices.IssueDeviceTokenOutput:
        """Issue a JWT for a device with user-defined claims.

        **Note: Only use this action for integration with external systems.**"""
        ...

    @overload
    def execute(
        self, action: devices.ValidateDeviceTokenAction
    ) -> devices.ValidateDeviceTokenOutput:
        """Validate a device JWT.

        **Note: Only use this action for integration with external systems.**"""
        ...

    @overload
    def execute(
        self, action: devices.AuthenticateDeviceAction
    ) -> devices.AuthenticateDeviceOutput:
        """Authenticate a device.

        **Note: The certificate fingerprint must be externally verified (mutual TLS).**"""
        ...

    @overload
    def execute(
        self, action: devices.AddDeviceCertificateAction
    ) -> devices.AddDeviceCertificateOutput:
        """Add a device certificate."""
        ...

    @overload
    def execute(self, action: devices.DeleteDeviceCertificateAction) -> outputs.Empty:
        """Delete a device certificate."""
        ...

    @overload
    def execute(
        self, action: devices.SetDeviceCertificateStatusAction
    ) -> outputs.Empty:
        """Set the status of a device certificate."""
        ...

    @overload
    def execute(
        self, action: devices.RegisterDeviceConnectionAction
    ) -> devices.RegisterDeviceConnectionOutput:
        """Register a connection of a device to a cluster node."""
        ...

    @overload
    def execute(
        self, action: devices.UnregisterDeviceConnectionAction
    ) -> outputs.Empty:
        """Unregister a connection of a device to a cluster node."""
        ...

    @overload
    def execute(
        self, action: devices.QueryDeviceConnectionsAction
    ) -> devices.QueryDeviceConnectionsOutput:
        """Query the connection history of a device."""
        ...

    @overload
    def execute(
        self, action: devices.IssueDeviceHttpProxyTokenAction
    ) -> devices.IssueDeviceHttpProxyTokenOutput:
        """Issue a HTTP proxy JWT."""
        ...

    @overload
    def execute(
        self, action: devices.ValidateDeviceHttpProxyTokenAction
    ) -> devices.ValidateDeviceHttpProxyTokenOutput:
        """Validate a HTTP proxy JWT."""
        ...

    @overload
    def execute(self, action: devices.PublishDeviceEventsAction) -> outputs.Empty:
        """Publish device events."""
        ...

    @overload
    def execute(
        self, action: devices.QueryDeviceEventsAction
    ) -> devices.QueryDeviceEventsOutput:
        """Query device events."""
        ...

    @overload
    def execute(
        self, action: devices.SetDevicePropertyAction
    ) -> devices.SetDevicePropertyOutput:
        """Set a property of a device."""
        ...

    @overload
    def execute(
        self, action: devices.GetDevicePropertyAction
    ) -> devices.GetDevicePropertyOutput:
        """Get a property of a device."""
        ...

    @overload
    def execute(
        self, action: devices.RemoveDevicePropertyAction
    ) -> devices.RemoveDevicePropertyOutput:
        """Remove a property from a device."""
        ...

    @overload
    def execute(
        self, action: devices.QueryDevicePropertiesAction
    ) -> devices.QueryDevicePropertiesOutput:
        """Query the properties of a device."""
        ...

    @overload
    def execute(
        self, action: devices.QueryDeviceAuditLogAction
    ) -> devices.QueryDeviceAuditLogOutput:
        """Query the audit log of a device."""
        ...

    @overload
    def execute(
        self, action: devices.QueryDeviceCommandsAction
    ) -> devices.QueryDeviceCommandsOutput:
        """Query the on-demand commands supported by a device."""
        ...

    @overload
    def execute(self, action: fleet.SetFleetPropertyAction) -> outputs.Empty:
        """Set a fleet property manually."""
        ...

    @overload
    def execute(
        self, action: fleet.GetFleetPropertyAction
    ) -> fleet.GetFleetPropertyOutput:
        """Get a fleet property by name."""
        ...

    @overload
    def execute(
        self, action: fleet.RemoveFleetPropertyAction
    ) -> fleet.RemoveFleetPropertyOutput:
        """Remove a fleet property.

        Handles both manual and computed properties. For computed properties, the
        associated definition is removed as well."""
        ...

    @overload
    def execute(
        self, action: fleet.QueryFleetPropertiesAction
    ) -> fleet.QueryFleetPropertiesOutput:
        """Query all fleet properties of a project."""
        ...

    @overload
    def execute(self, action: fleet.DefineComputedFleetPropertyAction) -> outputs.Empty:
        """Define a computed fleet property."""
        ...

    @overload
    def execute(
        self, action: fleet.QueryComputedFleetPropertyDefinitionsAction
    ) -> fleet.QueryComputedFleetPropertyDefinitionsOutput:
        """Query computed fleet property definitions for a project."""
        ...

    @overload
    def execute(
        self, action: repositories.ResolveRepositoryNameAction
    ) -> repositories.ResolveRepositoryNameOutput:
        """Resolve a repository by its name."""
        ...

    @overload
    def execute(
        self, action: repositories.GetRepositoryDetailsAction
    ) -> repositories.GetRepositoryDetailsOutput:
        """Get information about a repository."""
        ...

    @overload
    def execute(
        self, action: repositories.CreateRepositoryAction
    ) -> repositories.CreateRepositoryOutput:
        """Create a new repository."""
        ...

    @overload
    def execute(self, action: repositories.DeleteRepositoryAction) -> outputs.Empty:
        """Delete a repository."""
        ...

    @overload
    def execute(
        self, action: repositories.SetRepositoryVisibilityAction
    ) -> outputs.Empty:
        """Set the visibility of a repository."""
        ...

    @overload
    def execute(
        self, action: repositories.SetRepositoryDisplayNameAction
    ) -> outputs.Empty:
        """Set the display name of a repository."""
        ...

    @overload
    def execute(
        self, action: repositories.SetRepositoryPublicNameAction
    ) -> repositories.SetRepositoryPublicNameOutput:
        """Set the public name of a repository.

        Note: Setting the public name requires the `public_repositories` subscription feature."""
        ...

    @overload
    def execute(
        self, action: repositories.QueryRepositoryPackagesAction
    ) -> repositories.QueryRepositoryPackagesOutput:
        """Query the packages of a repository."""
        ...

    @overload
    def execute(
        self, action: repositories.QueryRepositoryAssetsAction
    ) -> repositories.QueryRepositoryAssetsOutput:
        """Query the assets of a repository."""
        ...

    @overload
    def execute(
        self, action: repositories.QueryRepositoryProjectsAction
    ) -> repositories.QueryRepositoryProjectsOutput:
        """Query repository projects."""
        ...

    @overload
    def execute(
        self, action: repositories.ResolvePackageByPathAction
    ) -> repositories.ResolvePackageByPathOutput:
        """Resolve a package by its path."""
        ...

    @overload
    def execute(
        self, action: repositories.GetPackageDetailsAction
    ) -> repositories.GetPackageDetailsOutput:
        """Get information about a package."""
        ...

    @overload
    def execute(
        self, action: repositories.CreatePackageAction
    ) -> repositories.CreatePackageOutput:
        """Create a new package."""
        ...

    @overload
    def execute(self, action: repositories.DeletePackageAction) -> outputs.Empty:
        """Delete a package."""
        ...

    @overload
    def execute(
        self, action: repositories.SetPackageNameAction
    ) -> repositories.SetPackageNameOutput:
        """Set the name of a package."""
        ...

    @overload
    def execute(self, action: repositories.SetPackageKindAction) -> outputs.Empty:
        """Set the kind of a package."""
        ...

    @overload
    def execute(self, action: repositories.SetPackageMetadataAction) -> outputs.Empty:
        """Set metadata on a package."""
        ...

    @overload
    def execute(
        self, action: repositories.QueryPackageVersionsAction
    ) -> repositories.QueryPackageVersionsOutput:
        """Query the versions of a package."""
        ...

    @overload
    def execute(
        self, action: repositories.ResolvePackageVersionByPathAction
    ) -> repositories.ResolvePackageVersionByPathOutput:
        """Resolve a package version by its path."""
        ...

    @overload
    def execute(
        self, action: repositories.GetPackageVersionDetailsAction
    ) -> repositories.GetPackageVersionDetailsOutput:
        """Get information about a package version."""
        ...

    @overload
    def execute(
        self, action: repositories.CreatePackageVersionAction
    ) -> repositories.CreatePackageVersionOutput:
        """Create a new package version."""
        ...

    @overload
    def execute(self, action: repositories.DeletePackageVersionAction) -> outputs.Empty:
        """Delete a package version."""
        ...

    @overload
    def execute(
        self, action: repositories.SetPackageVersionNameAction
    ) -> outputs.Empty:
        """Set the name of a package version."""
        ...

    @overload
    def execute(
        self, action: repositories.SetPackageVersionMetadataAction
    ) -> outputs.Empty:
        """Set metadata on a package version."""
        ...

    @overload
    def execute(
        self, action: repositories.AddPackageVersionAssetAction
    ) -> repositories.AddPackageVersionAssetOutput:
        """Add an asset to a package version."""
        ...

    @overload
    def execute(
        self, action: repositories.RemovePackageVersionAssetAction
    ) -> outputs.Empty:
        """Remove an asset from a package version."""
        ...

    @overload
    def execute(
        self, action: repositories.SetPackageVersionAssetMetadataAction
    ) -> outputs.Empty:
        """Set metadata on a package version asset."""
        ...

    @overload
    def execute(self, action: repositories.TagPackageVersionAction) -> outputs.Empty:
        """Add tags to a version."""
        ...

    @overload
    def execute(self, action: repositories.UntagPackageVersionAction) -> outputs.Empty:
        """Remove tags from a version."""
        ...

    @overload
    def execute(
        self, action: repositories.ResolvePackageVersionAssetByPathAction
    ) -> repositories.ResolvePackageVersionAssetByPathOutput:
        """Resolve a version asset by its path."""
        ...

    @overload
    def execute(
        self, action: repositories.SetRepositoryS3ConfigAction
    ) -> outputs.Empty:
        """Set the S3 configuration for the repository."""
        ...

    @overload
    def execute(
        self, action: repositories.GetRepositoryS3ConfigAction
    ) -> repositories.GetRepositoryS3ConfigOutput:
        """Get the S3 configuration for the repository."""
        ...

    @overload
    def execute(
        self, action: repositories.GetAssetDetailsAction
    ) -> repositories.GetAssetDetailsOutput:
        """Get information about an asset."""
        ...

    @overload
    def execute(
        self, action: repositories.CreateAssetAction
    ) -> repositories.CreateAssetOutput:
        """Create an asset."""
        ...

    @overload
    def execute(self, action: repositories.DeleteAssetAction) -> outputs.Empty:
        """Delete an asset."""
        ...

    @overload
    def execute(
        self, action: repositories.IssueAssetDownloadUrlAction
    ) -> repositories.IssueAssetDownloadUrlOutput:
        """Issue a URL for downloading an asset."""
        ...

    @overload
    def execute(
        self, action: repositories.IssueAssetUploadUrlAction
    ) -> repositories.IssueAssetUploadUrlOutput:
        """Issue a URL for uploading an asset."""
        ...

    @overload
    def execute(
        self, action: repositories.QueryAuditLogEventsAction
    ) -> repositories.QueryAuditLogEventsOutput:
        """Query the audit log of the repository."""
        ...

    @overload
    def execute(
        self, action: audit.QueryAuditLogEventsAction
    ) -> audit.QueryAuditLogEventsOutput:
        """Query the events recorded in the audit log.

        Requires administrator permissions."""
        ...

    @overload
    def execute(
        self, action: audit.QueryAuditLogActionsAction
    ) -> audit.QueryAuditLogActionsOutput:
        """Query the actions recorded in the audit log.

        Requires administrator permissions."""
        ...

    @overload
    def execute(self, action: jobs.QueryJobsAction) -> jobs.QueryJobsOutput:
        """Query the jobs of the instance."""
        ...

    @overload
    def execute(
        self, action: instance.GetInstanceStatisticsAction
    ) -> instance.GetInstanceStatisticsOutput:
        """Get instance statistics."""
        ...

    @overload
    def execute(
        self, action: instance.GetInstanceSettingsRawAction
    ) -> instance.GetInstanceSettingsRawOutput:
        """Get the settings of the instance."""
        ...

    @overload
    def execute(self, action: instance.SetInstanceSettingRawAction) -> outputs.Empty:
        """Set a setting of the instance."""
        ...

    @overload
    def execute(
        self, action: cluster.GetClusterDetailsAction
    ) -> cluster.GetClusterDetailsOutput:
        """Get information about the cluster."""
        ...

    @overload
    def execute(
        self, action: cluster.RegisterClusterNodeAction
    ) -> cluster.RegisterClusterNodeOutput:
        """Register a new cluster node."""
        ...

    @overload
    def execute(
        self, action: cluster.ReportClusterNodeHeartbeatAction
    ) -> outputs.Empty:
        """Report the heartbeat of a cluster node."""
        ...

    @overload
    def execute(
        self, action: cluster.CleanupInactiveClusterNodesAction
    ) -> outputs.Empty:
        """Cleanup inactive cluster nodes."""
        ...

    @overload
    def execute(self, action: actor.GetActorAction) -> actor.GetActorOutput:
        """Get the actor.

        This action is used to get the actor that is used to invoke the action."""
        ...

    def execute(self, action: pydantic.BaseModel) -> pydantic.BaseModel:
        return self._execute_action(action)

    def _execute_action(self, action: pydantic.BaseModel) -> pydantic.BaseModel:
        raise NotImplementedError


class _AsyncExecuteMixin:
    """Type overloads for the asynchronous client."""

    @overload
    async def execute(self, action: users.QueryUsersAction) -> users.QueryUsersOutput:
        """Query the users of the instance."""
        ...

    @overload
    async def execute(
        self, action: users.GetUserDetailsAction
    ) -> users.GetUserDetailsOutput:
        """Get information about a user."""
        ...

    @overload
    async def execute(self, action: users.CreateUserAction) -> users.CreateUserOutput:
        """Create a new user."""
        ...

    @overload
    async def execute(self, action: users.DeleteUserAction) -> outputs.Empty:
        """Delete a user."""
        ...

    @overload
    async def execute(self, action: users.SetUserDisplayNameAction) -> outputs.Empty:
        """Set the display name of a user."""
        ...

    @overload
    async def execute(self, action: users.SetUserPasswordAction) -> outputs.Empty:
        """Set the password of a user."""
        ...

    @overload
    async def execute(self, action: users.SetUserIsAdminAction) -> outputs.Empty:
        """Set whether the user is an instance administrator."""
        ...

    @overload
    async def execute(self, action: users.ResetUserPasswordAction) -> outputs.Empty:
        """Reset the password of a user.

        This will send an email to the user with a link to reset their password."""
        ...

    @overload
    async def execute(
        self, action: users.CompleteUserPasswordResetAction
    ) -> users.CompleteUserPasswordResetOutput:
        """Complete the password reset of a user."""
        ...

    @overload
    async def execute(
        self, action: users.QueryUserTokensAction
    ) -> users.QueryUserTokensOutput:
        """Query the tokens of a user."""
        ...

    @overload
    async def execute(
        self, action: users.QueryUserOrganizationsAction
    ) -> users.QueryUserOrganizationsOutput:
        """Query the organizations of a user."""
        ...

    @overload
    async def execute(
        self, action: users.QueryUserOrganizationInvitationsAction
    ) -> users.QueryUserOrganizationInvitationsOutput:
        """Query the organization invitations of a user."""
        ...

    @overload
    async def execute(
        self, action: users.QueryUserSessionsAction
    ) -> users.QueryUserSessionsOutput:
        """Query the sessions of a user."""
        ...

    @overload
    async def execute(
        self, action: users.AuthenticateWithUserTokenAction
    ) -> users.AuthenticateWithUserTokenOutput:
        """Authenticate a user with a token."""
        ...

    @overload
    async def execute(
        self, action: users.AuthenticateWithSessionTokenAction
    ) -> users.AuthenticateWithSessionTokenOutput:
        """Authenticate a user with a session token."""
        ...

    @overload
    async def execute(
        self, action: users.GetDevicePermissionsAction
    ) -> users.GetDevicePermissionsOutput:
        """Check the permissions of a user for a given device."""
        ...

    @overload
    async def execute(
        self, action: users.CreateUserTokenAction
    ) -> users.CreateUserTokenOutput:
        """Create a user token."""
        ...

    @overload
    async def execute(self, action: users.DeleteUserTokenAction) -> outputs.Empty:
        """Delete a user token."""
        ...

    @overload
    async def execute(
        self, action: users.InitiateUserSessionAction
    ) -> users.InitiateUserSessionOutput:
        """Initiate a user session."""
        ...

    @overload
    async def execute(self, action: users.TerminateUserSessionAction) -> outputs.Empty:
        """Terminate a user session."""
        ...

    @overload
    async def execute(
        self, action: users.CleanupExpiredUserSessionsAction
    ) -> outputs.Empty:
        """Cleanup expired user sessions."""
        ...

    @overload
    async def execute(
        self, action: users.RegisterUserAction
    ) -> users.RegisterUserOutput:
        """Register a new user with an email and password."""
        ...

    @overload
    async def execute(
        self, action: users.ResendRegistrationEmailAction
    ) -> outputs.Empty:
        """"""
        ...

    @overload
    async def execute(
        self, action: users.CompleteRegistrationAction
    ) -> users.CompleteRegistrationOutput:
        """Complete the registration of a user."""
        ...

    @overload
    async def execute(
        self, action: users.AcceptOrganizationInvitationAction
    ) -> outputs.Empty:
        """Accept a organization invitation."""
        ...

    @overload
    async def execute(
        self, action: organizations.QueryOrganizationsAction
    ) -> organizations.QueryOrganizationsOutput:
        """Query the organizations of the instance."""
        ...

    @overload
    async def execute(
        self, action: organizations.QueryOrganizationMembersAction
    ) -> organizations.QueryOrganizationMembersOutput:
        """Query the members of an organization."""
        ...

    @overload
    async def execute(
        self, action: organizations.QueryOrganizationProjectsAction
    ) -> organizations.QueryOrganizationProjectsOutput:
        """Query the projects of an organization."""
        ...

    @overload
    async def execute(
        self, action: organizations.QueryOrganizationRepositoriesAction
    ) -> organizations.QueryOrganizationRepositoriesOutput:
        """Query the repositories of an organization."""
        ...

    @overload
    async def execute(
        self, action: organizations.QueryOrganizationInvitationsAction
    ) -> organizations.QueryOrganizationInvitationsOutput:
        """Query the invitations of an organization."""
        ...

    @overload
    async def execute(
        self, action: organizations.CreateOrganizationAction
    ) -> organizations.CreateOrganizationOutput:
        """Create an organization."""
        ...

    @overload
    async def execute(
        self, action: organizations.DeleteOrganizationAction
    ) -> outputs.Empty:
        """Delete an organization."""
        ...

    @overload
    async def execute(
        self, action: organizations.AddOrganizationMemberAction
    ) -> outputs.Empty:
        """Add a user to an organization."""
        ...

    @overload
    async def execute(
        self, action: organizations.RemoveOrganizationMemberAction
    ) -> outputs.Empty:
        """Remove a user from an organization."""
        ...

    @overload
    async def execute(
        self, action: organizations.SetOrganizationMemberIsAdminAction
    ) -> outputs.Empty:
        """Set whether the user is an administrator of the organization."""
        ...

    @overload
    async def execute(
        self, action: organizations.InviteOrganizationMemberAction
    ) -> organizations.InviteOrganizationMemberOutput:
        """Invite a user to an organization."""
        ...

    @overload
    async def execute(
        self, action: organizations.DeleteOrganizationInvitationAction
    ) -> outputs.Empty:
        """Delete an invitation to an organization."""
        ...

    @overload
    async def execute(
        self, action: organizations.QueryOrganizationAuditLogAction
    ) -> organizations.QueryOrganizationAuditLogOutput:
        """Query the audit log of an organization."""
        ...

    @overload
    async def execute(
        self, action: projects.QueryProjectsAction
    ) -> projects.QueryProjectsOutput:
        """Query the projects of the instance."""
        ...

    @overload
    async def execute(
        self, action: projects.GetProjectDetailsAction
    ) -> projects.GetProjectDetailsOutput:
        """Get information about a project."""
        ...

    @overload
    async def execute(
        self, action: projects.CreateProjectAction
    ) -> projects.CreateProjectOutput:
        """Create a new project."""
        ...

    @overload
    async def execute(self, action: projects.DeleteProjectAction) -> outputs.Empty:
        """Delete a project."""
        ...

    @overload
    async def execute(
        self, action: projects.QueryProjectDevicesAction
    ) -> projects.QueryProjectDevicesOutput:
        """Query the devices of a project."""
        ...

    @overload
    async def execute(
        self, action: projects.QueryProjectDeploymentTokensAction
    ) -> projects.QueryProjectDeploymentTokensOutput:
        """Query the deployment tokens of a project."""
        ...

    @overload
    async def execute(
        self, action: projects.QueryProjectRepositoriesAction
    ) -> projects.QueryProjectRepositoriesOutput:
        """Query repositories of a project."""
        ...

    @overload
    async def execute(self, action: projects.SetProjectNameAction) -> outputs.Empty:
        """Set the name of a project."""
        ...

    @overload
    async def execute(
        self, action: projects.CreateDeploymentTokenAction
    ) -> projects.CreateDeploymentTokenOutput:
        """Create a deployment token."""
        ...

    @overload
    async def execute(
        self, action: projects.DeleteDeploymentTokenAction
    ) -> outputs.Empty:
        """Delete a deployment token."""
        ...

    @overload
    async def execute(
        self, action: projects.SetDeploymentTokenFlagsAction
    ) -> outputs.Empty:
        """Set the flags of a deployment token."""
        ...

    @overload
    async def execute(
        self, action: projects.QueryAuditLogEventsAction
    ) -> projects.QueryAuditLogEventsOutput:
        """Query the audit log of the project."""
        ...

    @overload
    async def execute(
        self, action: projects.AddProjectRepositoryAction
    ) -> outputs.Empty:
        """Add a repository to the project."""
        ...

    @overload
    async def execute(
        self, action: projects.RemoveProjectRepositoryAction
    ) -> outputs.Empty:
        """Remove a repository from the project."""
        ...

    @overload
    async def execute(
        self, action: projects.GetProjectOtlpConfigAction
    ) -> projects.GetProjectOtlpConfigOutput:
        """Get the OTLP event forwarding configuration for a project."""
        ...

    @overload
    async def execute(
        self, action: projects.SetProjectOtlpConfigAction
    ) -> outputs.Empty:
        """Set the OTLP event forwarding configuration for a project."""
        ...

    @overload
    async def execute(
        self, action: devices.QueryDevicesAction
    ) -> devices.QueryDevicesOutput:
        """Query the devices of the instance."""
        ...

    @overload
    async def execute(
        self, action: devices.GetDeviceDetailsAction
    ) -> devices.GetDeviceDetailsOutput:
        """Get information about a device."""
        ...

    @overload
    async def execute(
        self, action: devices.CreateDeviceAction
    ) -> devices.CreateDeviceOutput:
        """Create a new device."""
        ...

    @overload
    async def execute(self, action: devices.DeleteDeviceAction) -> outputs.Empty:
        """Delete a device."""
        ...

    @overload
    async def execute(self, action: devices.SetDeviceNameAction) -> outputs.Empty:
        """Set the name of a device."""
        ...

    @overload
    async def execute(
        self, action: devices.IssueDeviceTokenAction
    ) -> devices.IssueDeviceTokenOutput:
        """Issue a JWT for a device with user-defined claims.

        **Note: Only use this action for integration with external systems.**"""
        ...

    @overload
    async def execute(
        self, action: devices.ValidateDeviceTokenAction
    ) -> devices.ValidateDeviceTokenOutput:
        """Validate a device JWT.

        **Note: Only use this action for integration with external systems.**"""
        ...

    @overload
    async def execute(
        self, action: devices.AuthenticateDeviceAction
    ) -> devices.AuthenticateDeviceOutput:
        """Authenticate a device.

        **Note: The certificate fingerprint must be externally verified (mutual TLS).**"""
        ...

    @overload
    async def execute(
        self, action: devices.AddDeviceCertificateAction
    ) -> devices.AddDeviceCertificateOutput:
        """Add a device certificate."""
        ...

    @overload
    async def execute(
        self, action: devices.DeleteDeviceCertificateAction
    ) -> outputs.Empty:
        """Delete a device certificate."""
        ...

    @overload
    async def execute(
        self, action: devices.SetDeviceCertificateStatusAction
    ) -> outputs.Empty:
        """Set the status of a device certificate."""
        ...

    @overload
    async def execute(
        self, action: devices.RegisterDeviceConnectionAction
    ) -> devices.RegisterDeviceConnectionOutput:
        """Register a connection of a device to a cluster node."""
        ...

    @overload
    async def execute(
        self, action: devices.UnregisterDeviceConnectionAction
    ) -> outputs.Empty:
        """Unregister a connection of a device to a cluster node."""
        ...

    @overload
    async def execute(
        self, action: devices.QueryDeviceConnectionsAction
    ) -> devices.QueryDeviceConnectionsOutput:
        """Query the connection history of a device."""
        ...

    @overload
    async def execute(
        self, action: devices.IssueDeviceHttpProxyTokenAction
    ) -> devices.IssueDeviceHttpProxyTokenOutput:
        """Issue a HTTP proxy JWT."""
        ...

    @overload
    async def execute(
        self, action: devices.ValidateDeviceHttpProxyTokenAction
    ) -> devices.ValidateDeviceHttpProxyTokenOutput:
        """Validate a HTTP proxy JWT."""
        ...

    @overload
    async def execute(self, action: devices.PublishDeviceEventsAction) -> outputs.Empty:
        """Publish device events."""
        ...

    @overload
    async def execute(
        self, action: devices.QueryDeviceEventsAction
    ) -> devices.QueryDeviceEventsOutput:
        """Query device events."""
        ...

    @overload
    async def execute(
        self, action: devices.SetDevicePropertyAction
    ) -> devices.SetDevicePropertyOutput:
        """Set a property of a device."""
        ...

    @overload
    async def execute(
        self, action: devices.GetDevicePropertyAction
    ) -> devices.GetDevicePropertyOutput:
        """Get a property of a device."""
        ...

    @overload
    async def execute(
        self, action: devices.RemoveDevicePropertyAction
    ) -> devices.RemoveDevicePropertyOutput:
        """Remove a property from a device."""
        ...

    @overload
    async def execute(
        self, action: devices.QueryDevicePropertiesAction
    ) -> devices.QueryDevicePropertiesOutput:
        """Query the properties of a device."""
        ...

    @overload
    async def execute(
        self, action: devices.QueryDeviceAuditLogAction
    ) -> devices.QueryDeviceAuditLogOutput:
        """Query the audit log of a device."""
        ...

    @overload
    async def execute(
        self, action: devices.QueryDeviceCommandsAction
    ) -> devices.QueryDeviceCommandsOutput:
        """Query the on-demand commands supported by a device."""
        ...

    @overload
    async def execute(self, action: fleet.SetFleetPropertyAction) -> outputs.Empty:
        """Set a fleet property manually."""
        ...

    @overload
    async def execute(
        self, action: fleet.GetFleetPropertyAction
    ) -> fleet.GetFleetPropertyOutput:
        """Get a fleet property by name."""
        ...

    @overload
    async def execute(
        self, action: fleet.RemoveFleetPropertyAction
    ) -> fleet.RemoveFleetPropertyOutput:
        """Remove a fleet property.

        Handles both manual and computed properties. For computed properties, the
        associated definition is removed as well."""
        ...

    @overload
    async def execute(
        self, action: fleet.QueryFleetPropertiesAction
    ) -> fleet.QueryFleetPropertiesOutput:
        """Query all fleet properties of a project."""
        ...

    @overload
    async def execute(
        self, action: fleet.DefineComputedFleetPropertyAction
    ) -> outputs.Empty:
        """Define a computed fleet property."""
        ...

    @overload
    async def execute(
        self, action: fleet.QueryComputedFleetPropertyDefinitionsAction
    ) -> fleet.QueryComputedFleetPropertyDefinitionsOutput:
        """Query computed fleet property definitions for a project."""
        ...

    @overload
    async def execute(
        self, action: repositories.ResolveRepositoryNameAction
    ) -> repositories.ResolveRepositoryNameOutput:
        """Resolve a repository by its name."""
        ...

    @overload
    async def execute(
        self, action: repositories.GetRepositoryDetailsAction
    ) -> repositories.GetRepositoryDetailsOutput:
        """Get information about a repository."""
        ...

    @overload
    async def execute(
        self, action: repositories.CreateRepositoryAction
    ) -> repositories.CreateRepositoryOutput:
        """Create a new repository."""
        ...

    @overload
    async def execute(
        self, action: repositories.DeleteRepositoryAction
    ) -> outputs.Empty:
        """Delete a repository."""
        ...

    @overload
    async def execute(
        self, action: repositories.SetRepositoryVisibilityAction
    ) -> outputs.Empty:
        """Set the visibility of a repository."""
        ...

    @overload
    async def execute(
        self, action: repositories.SetRepositoryDisplayNameAction
    ) -> outputs.Empty:
        """Set the display name of a repository."""
        ...

    @overload
    async def execute(
        self, action: repositories.SetRepositoryPublicNameAction
    ) -> repositories.SetRepositoryPublicNameOutput:
        """Set the public name of a repository.

        Note: Setting the public name requires the `public_repositories` subscription feature."""
        ...

    @overload
    async def execute(
        self, action: repositories.QueryRepositoryPackagesAction
    ) -> repositories.QueryRepositoryPackagesOutput:
        """Query the packages of a repository."""
        ...

    @overload
    async def execute(
        self, action: repositories.QueryRepositoryAssetsAction
    ) -> repositories.QueryRepositoryAssetsOutput:
        """Query the assets of a repository."""
        ...

    @overload
    async def execute(
        self, action: repositories.QueryRepositoryProjectsAction
    ) -> repositories.QueryRepositoryProjectsOutput:
        """Query repository projects."""
        ...

    @overload
    async def execute(
        self, action: repositories.ResolvePackageByPathAction
    ) -> repositories.ResolvePackageByPathOutput:
        """Resolve a package by its path."""
        ...

    @overload
    async def execute(
        self, action: repositories.GetPackageDetailsAction
    ) -> repositories.GetPackageDetailsOutput:
        """Get information about a package."""
        ...

    @overload
    async def execute(
        self, action: repositories.CreatePackageAction
    ) -> repositories.CreatePackageOutput:
        """Create a new package."""
        ...

    @overload
    async def execute(self, action: repositories.DeletePackageAction) -> outputs.Empty:
        """Delete a package."""
        ...

    @overload
    async def execute(
        self, action: repositories.SetPackageNameAction
    ) -> repositories.SetPackageNameOutput:
        """Set the name of a package."""
        ...

    @overload
    async def execute(self, action: repositories.SetPackageKindAction) -> outputs.Empty:
        """Set the kind of a package."""
        ...

    @overload
    async def execute(
        self, action: repositories.SetPackageMetadataAction
    ) -> outputs.Empty:
        """Set metadata on a package."""
        ...

    @overload
    async def execute(
        self, action: repositories.QueryPackageVersionsAction
    ) -> repositories.QueryPackageVersionsOutput:
        """Query the versions of a package."""
        ...

    @overload
    async def execute(
        self, action: repositories.ResolvePackageVersionByPathAction
    ) -> repositories.ResolvePackageVersionByPathOutput:
        """Resolve a package version by its path."""
        ...

    @overload
    async def execute(
        self, action: repositories.GetPackageVersionDetailsAction
    ) -> repositories.GetPackageVersionDetailsOutput:
        """Get information about a package version."""
        ...

    @overload
    async def execute(
        self, action: repositories.CreatePackageVersionAction
    ) -> repositories.CreatePackageVersionOutput:
        """Create a new package version."""
        ...

    @overload
    async def execute(
        self, action: repositories.DeletePackageVersionAction
    ) -> outputs.Empty:
        """Delete a package version."""
        ...

    @overload
    async def execute(
        self, action: repositories.SetPackageVersionNameAction
    ) -> outputs.Empty:
        """Set the name of a package version."""
        ...

    @overload
    async def execute(
        self, action: repositories.SetPackageVersionMetadataAction
    ) -> outputs.Empty:
        """Set metadata on a package version."""
        ...

    @overload
    async def execute(
        self, action: repositories.AddPackageVersionAssetAction
    ) -> repositories.AddPackageVersionAssetOutput:
        """Add an asset to a package version."""
        ...

    @overload
    async def execute(
        self, action: repositories.RemovePackageVersionAssetAction
    ) -> outputs.Empty:
        """Remove an asset from a package version."""
        ...

    @overload
    async def execute(
        self, action: repositories.SetPackageVersionAssetMetadataAction
    ) -> outputs.Empty:
        """Set metadata on a package version asset."""
        ...

    @overload
    async def execute(
        self, action: repositories.TagPackageVersionAction
    ) -> outputs.Empty:
        """Add tags to a version."""
        ...

    @overload
    async def execute(
        self, action: repositories.UntagPackageVersionAction
    ) -> outputs.Empty:
        """Remove tags from a version."""
        ...

    @overload
    async def execute(
        self, action: repositories.ResolvePackageVersionAssetByPathAction
    ) -> repositories.ResolvePackageVersionAssetByPathOutput:
        """Resolve a version asset by its path."""
        ...

    @overload
    async def execute(
        self, action: repositories.SetRepositoryS3ConfigAction
    ) -> outputs.Empty:
        """Set the S3 configuration for the repository."""
        ...

    @overload
    async def execute(
        self, action: repositories.GetRepositoryS3ConfigAction
    ) -> repositories.GetRepositoryS3ConfigOutput:
        """Get the S3 configuration for the repository."""
        ...

    @overload
    async def execute(
        self, action: repositories.GetAssetDetailsAction
    ) -> repositories.GetAssetDetailsOutput:
        """Get information about an asset."""
        ...

    @overload
    async def execute(
        self, action: repositories.CreateAssetAction
    ) -> repositories.CreateAssetOutput:
        """Create an asset."""
        ...

    @overload
    async def execute(self, action: repositories.DeleteAssetAction) -> outputs.Empty:
        """Delete an asset."""
        ...

    @overload
    async def execute(
        self, action: repositories.IssueAssetDownloadUrlAction
    ) -> repositories.IssueAssetDownloadUrlOutput:
        """Issue a URL for downloading an asset."""
        ...

    @overload
    async def execute(
        self, action: repositories.IssueAssetUploadUrlAction
    ) -> repositories.IssueAssetUploadUrlOutput:
        """Issue a URL for uploading an asset."""
        ...

    @overload
    async def execute(
        self, action: repositories.QueryAuditLogEventsAction
    ) -> repositories.QueryAuditLogEventsOutput:
        """Query the audit log of the repository."""
        ...

    @overload
    async def execute(
        self, action: audit.QueryAuditLogEventsAction
    ) -> audit.QueryAuditLogEventsOutput:
        """Query the events recorded in the audit log.

        Requires administrator permissions."""
        ...

    @overload
    async def execute(
        self, action: audit.QueryAuditLogActionsAction
    ) -> audit.QueryAuditLogActionsOutput:
        """Query the actions recorded in the audit log.

        Requires administrator permissions."""
        ...

    @overload
    async def execute(self, action: jobs.QueryJobsAction) -> jobs.QueryJobsOutput:
        """Query the jobs of the instance."""
        ...

    @overload
    async def execute(
        self, action: instance.GetInstanceStatisticsAction
    ) -> instance.GetInstanceStatisticsOutput:
        """Get instance statistics."""
        ...

    @overload
    async def execute(
        self, action: instance.GetInstanceSettingsRawAction
    ) -> instance.GetInstanceSettingsRawOutput:
        """Get the settings of the instance."""
        ...

    @overload
    async def execute(
        self, action: instance.SetInstanceSettingRawAction
    ) -> outputs.Empty:
        """Set a setting of the instance."""
        ...

    @overload
    async def execute(
        self, action: cluster.GetClusterDetailsAction
    ) -> cluster.GetClusterDetailsOutput:
        """Get information about the cluster."""
        ...

    @overload
    async def execute(
        self, action: cluster.RegisterClusterNodeAction
    ) -> cluster.RegisterClusterNodeOutput:
        """Register a new cluster node."""
        ...

    @overload
    async def execute(
        self, action: cluster.ReportClusterNodeHeartbeatAction
    ) -> outputs.Empty:
        """Report the heartbeat of a cluster node."""
        ...

    @overload
    async def execute(
        self, action: cluster.CleanupInactiveClusterNodesAction
    ) -> outputs.Empty:
        """Cleanup inactive cluster nodes."""
        ...

    @overload
    async def execute(self, action: actor.GetActorAction) -> actor.GetActorOutput:
        """Get the actor.

        This action is used to get the actor that is used to invoke the action."""
        ...

    async def execute(self, action: pydantic.BaseModel) -> pydantic.BaseModel:
        return await self._execute_action(action)

    async def _execute_action(self, action: pydantic.BaseModel) -> pydantic.BaseModel:
        raise NotImplementedError
