# DO NOT EDIT! This file is autogenerated.

from __future__ import annotations

from typing import overload

import pydantic

from .api_types import actor
from .api_types import audit
from .api_types import cluster
from .api_types import devices
from .api_types import fleet
from .api_types import instance
from .api_types import jobs
from .api_types import organizations
from .api_types import outputs
from .api_types import projects
from .api_types import repositories
from .api_types import users


_ACTION_REGISTRY: dict[type, tuple[str, pydantic.TypeAdapter]] = {  # type: ignore[type-arg]
    users.QueryUsersAction: (
        "users_Query",
        pydantic.TypeAdapter(users.QueryUsersOutput),
    ),
    users.GetUserDetailsAction: (
        "users_GetDetails",
        pydantic.TypeAdapter(users.GetUserDetailsOutput),
    ),
    users.CreateUserAction: (
        "users_Create",
        pydantic.TypeAdapter(users.CreateUserOutput),
    ),
    users.DeleteUserAction: ("users_Delete", pydantic.TypeAdapter(outputs.Empty)),
    users.SetUserDisplayNameAction: (
        "users_SetDisplayName",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    users.SetUserPasswordAction: (
        "users_SetPassword",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    users.SetUserIsAdminAction: (
        "users_SetIsAdmin",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    users.ResetUserPasswordAction: (
        "users_ResetPassword",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    users.CompleteUserPasswordResetAction: (
        "users_CompletePasswordReset",
        pydantic.TypeAdapter(users.CompleteUserPasswordResetOutput),
    ),
    users.QueryUserTokensAction: (
        "users_QueryTokens",
        pydantic.TypeAdapter(users.QueryUserTokensOutput),
    ),
    users.QueryUserOrganizationsAction: (
        "users_QueryOrganizations",
        pydantic.TypeAdapter(users.QueryUserOrganizationsOutput),
    ),
    users.QueryUserOrganizationInvitationsAction: (
        "users_QueryOrganizationInvitations",
        pydantic.TypeAdapter(users.QueryUserOrganizationInvitationsOutput),
    ),
    users.QueryUserSessionsAction: (
        "users_QuerySessions",
        pydantic.TypeAdapter(users.QueryUserSessionsOutput),
    ),
    users.AuthenticateWithUserTokenAction: (
        "users_AuthenticateWithToken",
        pydantic.TypeAdapter(users.AuthenticateWithUserTokenOutput),
    ),
    users.AuthenticateWithSessionTokenAction: (
        "users_AuthenticateWithSessionToken",
        pydantic.TypeAdapter(users.AuthenticateWithSessionTokenOutput),
    ),
    users.GetDevicePermissionsAction: (
        "users_GetDevicePermissions",
        pydantic.TypeAdapter(users.GetDevicePermissionsOutput),
    ),
    users.CreateUserTokenAction: (
        "users_CreateToken",
        pydantic.TypeAdapter(users.CreateUserTokenOutput),
    ),
    users.DeleteUserTokenAction: (
        "users_DeleteToken",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    users.InitiateUserSessionAction: (
        "users_InitiateSession",
        pydantic.TypeAdapter(users.InitiateUserSessionOutput),
    ),
    users.TerminateUserSessionAction: (
        "users_TerminateSession",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    users.CleanupExpiredUserSessionsAction: (
        "users_CleanupExpiredSessions",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    users.RegisterUserAction: (
        "users_Register",
        pydantic.TypeAdapter(users.RegisterUserOutput),
    ),
    users.ResendRegistrationEmailAction: (
        "users_ResendRegistrationEmail",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    users.CompleteRegistrationAction: (
        "users_CompleteRegistration",
        pydantic.TypeAdapter(users.CompleteRegistrationOutput),
    ),
    users.AcceptOrganizationInvitationAction: (
        "users_AcceptOrganizationInvitation",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    organizations.QueryOrganizationsAction: (
        "organizations_Query",
        pydantic.TypeAdapter(organizations.QueryOrganizationsOutput),
    ),
    organizations.QueryOrganizationMembersAction: (
        "organizations_QueryMembers",
        pydantic.TypeAdapter(organizations.QueryOrganizationMembersOutput),
    ),
    organizations.QueryOrganizationProjectsAction: (
        "organizations_QueryProjects",
        pydantic.TypeAdapter(organizations.QueryOrganizationProjectsOutput),
    ),
    organizations.QueryOrganizationRepositoriesAction: (
        "organizations_QueryRepositories",
        pydantic.TypeAdapter(organizations.QueryOrganizationRepositoriesOutput),
    ),
    organizations.QueryOrganizationInvitationsAction: (
        "organizations_QueryInvitations",
        pydantic.TypeAdapter(organizations.QueryOrganizationInvitationsOutput),
    ),
    organizations.CreateOrganizationAction: (
        "organizations_Create",
        pydantic.TypeAdapter(organizations.CreateOrganizationOutput),
    ),
    organizations.DeleteOrganizationAction: (
        "organizations_Delete",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    organizations.AddOrganizationMemberAction: (
        "organizations_AddMember",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    organizations.RemoveOrganizationMemberAction: (
        "organizations_RemoveMember",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    organizations.SetOrganizationMemberIsAdminAction: (
        "organizations_SetMemberIsAdmin",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    organizations.InviteOrganizationMemberAction: (
        "organizations_InviteMember",
        pydantic.TypeAdapter(organizations.InviteOrganizationMemberOutput),
    ),
    organizations.DeleteOrganizationInvitationAction: (
        "organizations_DeleteInvitation",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    organizations.QueryOrganizationAuditLogAction: (
        "organizations_QueryAuditLog",
        pydantic.TypeAdapter(organizations.QueryOrganizationAuditLogOutput),
    ),
    projects.QueryProjectsAction: (
        "projects_Query",
        pydantic.TypeAdapter(projects.QueryProjectsOutput),
    ),
    projects.GetProjectDetailsAction: (
        "projects_GetDetails",
        pydantic.TypeAdapter(projects.GetProjectDetailsOutput),
    ),
    projects.CreateProjectAction: (
        "projects_Create",
        pydantic.TypeAdapter(projects.CreateProjectOutput),
    ),
    projects.DeleteProjectAction: (
        "projects_Delete",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    projects.QueryProjectDevicesAction: (
        "projects_QueryDevices",
        pydantic.TypeAdapter(projects.QueryProjectDevicesOutput),
    ),
    projects.QueryProjectDeploymentTokensAction: (
        "projects_QueryDeploymentTokens",
        pydantic.TypeAdapter(projects.QueryProjectDeploymentTokensOutput),
    ),
    projects.QueryProjectRepositoriesAction: (
        "projects_QueryLinkedRepositories",
        pydantic.TypeAdapter(projects.QueryProjectRepositoriesOutput),
    ),
    projects.SetProjectNameAction: (
        "projects_SetName",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    projects.CreateDeploymentTokenAction: (
        "projects_CreateDeploymentToken",
        pydantic.TypeAdapter(projects.CreateDeploymentTokenOutput),
    ),
    projects.DeleteDeploymentTokenAction: (
        "projects_DeleteDeploymentToken",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    projects.SetDeploymentTokenFlagsAction: (
        "projects_SetDeploymentTokenFlags",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    projects.QueryAuditLogEventsAction: (
        "projects_QueryAuditLog",
        pydantic.TypeAdapter(projects.QueryAuditLogEventsOutput),
    ),
    projects.AddProjectRepositoryAction: (
        "projects_LinkRepository",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    projects.RemoveProjectRepositoryAction: (
        "projects_UnlinkRepository",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    projects.GetProjectOtlpConfigAction: (
        "projects_GetOtlpConfig",
        pydantic.TypeAdapter(projects.GetProjectOtlpConfigOutput),
    ),
    projects.SetProjectOtlpConfigAction: (
        "projects_SetOtlpConfig",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    devices.QueryDevicesAction: (
        "devices_Query",
        pydantic.TypeAdapter(devices.QueryDevicesOutput),
    ),
    devices.GetDeviceDetailsAction: (
        "devices_GetDetails",
        pydantic.TypeAdapter(devices.GetDeviceDetailsOutput),
    ),
    devices.CreateDeviceAction: (
        "devices_Create",
        pydantic.TypeAdapter(devices.CreateDeviceOutput),
    ),
    devices.DeleteDeviceAction: ("devices_Delete", pydantic.TypeAdapter(outputs.Empty)),
    devices.SetDeviceNameAction: (
        "devices_SetName",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    devices.IssueDeviceTokenAction: (
        "devices_IssueDeviceToken",
        pydantic.TypeAdapter(devices.IssueDeviceTokenOutput),
    ),
    devices.ValidateDeviceTokenAction: (
        "devices_ValidateDeviceToken",
        pydantic.TypeAdapter(devices.ValidateDeviceTokenOutput),
    ),
    devices.AuthenticateDeviceAction: (
        "devices_Authenticate",
        pydantic.TypeAdapter(devices.AuthenticateDeviceOutput),
    ),
    devices.AddDeviceCertificateAction: (
        "devices_AddCertificate",
        pydantic.TypeAdapter(devices.AddDeviceCertificateOutput),
    ),
    devices.DeleteDeviceCertificateAction: (
        "devices_DeleteCertificate",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    devices.SetDeviceCertificateStatusAction: (
        "devices_SetCertificateStatus",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    devices.RegisterDeviceConnectionAction: (
        "devices_RegisterConnection",
        pydantic.TypeAdapter(devices.RegisterDeviceConnectionOutput),
    ),
    devices.UnregisterDeviceConnectionAction: (
        "devices_UnregisterConnection",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    devices.QueryDeviceConnectionsAction: (
        "devices_QueryConnections",
        pydantic.TypeAdapter(devices.QueryDeviceConnectionsOutput),
    ),
    devices.IssueDeviceHttpProxyTokenAction: (
        "devices_IssueHttpProxyToken",
        pydantic.TypeAdapter(devices.IssueDeviceHttpProxyTokenOutput),
    ),
    devices.ValidateDeviceHttpProxyTokenAction: (
        "devices_ValidateHttpProxyToken",
        pydantic.TypeAdapter(devices.ValidateDeviceHttpProxyTokenOutput),
    ),
    devices.PublishDeviceEventsAction: (
        "devices_PublishEvents",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    devices.QueryDeviceEventsAction: (
        "devices_QueryEvents",
        pydantic.TypeAdapter(devices.QueryDeviceEventsOutput),
    ),
    devices.SetDevicePropertyAction: (
        "devices_SetProperty",
        pydantic.TypeAdapter(devices.SetDevicePropertyOutput),
    ),
    devices.GetDevicePropertyAction: (
        "devices_GetProperty",
        pydantic.TypeAdapter(devices.GetDevicePropertyOutput),
    ),
    devices.RemoveDevicePropertyAction: (
        "devices_RemoveProperty",
        pydantic.TypeAdapter(devices.RemoveDevicePropertyOutput),
    ),
    devices.QueryDevicePropertiesAction: (
        "devices_QueryProperties",
        pydantic.TypeAdapter(devices.QueryDevicePropertiesOutput),
    ),
    devices.QueryDeviceAuditLogAction: (
        "devices_QueryAuditLog",
        pydantic.TypeAdapter(devices.QueryDeviceAuditLogOutput),
    ),
    devices.QueryDeviceCommandsAction: (
        "devices_QueryCommands",
        pydantic.TypeAdapter(devices.QueryDeviceCommandsOutput),
    ),
    fleet.SetFleetPropertyAction: (
        "fleet_SetProperty",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    fleet.GetFleetPropertyAction: (
        "fleet_GetProperty",
        pydantic.TypeAdapter(fleet.GetFleetPropertyOutput),
    ),
    fleet.RemoveFleetPropertyAction: (
        "fleet_RemoveProperty",
        pydantic.TypeAdapter(fleet.RemoveFleetPropertyOutput),
    ),
    fleet.QueryFleetPropertiesAction: (
        "fleet_QueryProperties",
        pydantic.TypeAdapter(fleet.QueryFleetPropertiesOutput),
    ),
    fleet.DefineComputedFleetPropertyAction: (
        "fleet_DefineComputedProperty",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    fleet.QueryComputedFleetPropertyDefinitionsAction: (
        "fleet_QueryComputedPropertyDefinitions",
        pydantic.TypeAdapter(fleet.QueryComputedFleetPropertyDefinitionsOutput),
    ),
    repositories.ResolveRepositoryNameAction: (
        "repositories_ResolveName",
        pydantic.TypeAdapter(repositories.ResolveRepositoryNameOutput),
    ),
    repositories.GetRepositoryDetailsAction: (
        "repositories_GetDetails",
        pydantic.TypeAdapter(repositories.GetRepositoryDetailsOutput),
    ),
    repositories.CreateRepositoryAction: (
        "repositories_Create",
        pydantic.TypeAdapter(repositories.CreateRepositoryOutput),
    ),
    repositories.DeleteRepositoryAction: (
        "repositories_Delete",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.SetRepositoryVisibilityAction: (
        "repositories_SetVisibility",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.SetRepositoryDisplayNameAction: (
        "repositories_SetDisplayName",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.SetRepositoryPublicNameAction: (
        "repositories_SetPublicName",
        pydantic.TypeAdapter(repositories.SetRepositoryPublicNameOutput),
    ),
    repositories.QueryRepositoryPackagesAction: (
        "repositories_QueryPackages",
        pydantic.TypeAdapter(repositories.QueryRepositoryPackagesOutput),
    ),
    repositories.QueryRepositoryAssetsAction: (
        "repositories_QueryAssets",
        pydantic.TypeAdapter(repositories.QueryRepositoryAssetsOutput),
    ),
    repositories.QueryRepositoryProjectsAction: (
        "repositories_QueryLinkedProjects",
        pydantic.TypeAdapter(repositories.QueryRepositoryProjectsOutput),
    ),
    repositories.ResolvePackageByPathAction: (
        "repositories_ResolvePackageByPath",
        pydantic.TypeAdapter(repositories.ResolvePackageByPathOutput),
    ),
    repositories.GetPackageDetailsAction: (
        "repositories_GetPackageDetails",
        pydantic.TypeAdapter(repositories.GetPackageDetailsOutput),
    ),
    repositories.CreatePackageAction: (
        "repositories_CreatePackage",
        pydantic.TypeAdapter(repositories.CreatePackageOutput),
    ),
    repositories.DeletePackageAction: (
        "repositories_DeletePackage",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.SetPackageNameAction: (
        "repositories_SetPackageName",
        pydantic.TypeAdapter(repositories.SetPackageNameOutput),
    ),
    repositories.SetPackageKindAction: (
        "repositories_SetPackageKind",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.SetPackageMetadataAction: (
        "repositories_SetPackageMetadata",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.QueryPackageVersionsAction: (
        "repositories_QueryPackageVersions",
        pydantic.TypeAdapter(repositories.QueryPackageVersionsOutput),
    ),
    repositories.ResolvePackageVersionByPathAction: (
        "repositories_ResolveVersionByPath",
        pydantic.TypeAdapter(repositories.ResolvePackageVersionByPathOutput),
    ),
    repositories.GetPackageVersionDetailsAction: (
        "repositories_GetVersionDetails",
        pydantic.TypeAdapter(repositories.GetPackageVersionDetailsOutput),
    ),
    repositories.CreatePackageVersionAction: (
        "repositories_CreateVersion",
        pydantic.TypeAdapter(repositories.CreatePackageVersionOutput),
    ),
    repositories.DeletePackageVersionAction: (
        "repositories_DeleteVersion",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.SetPackageVersionNameAction: (
        "repositories_SetVersionName",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.SetPackageVersionMetadataAction: (
        "repositories_SetVersionMetadata",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.AddPackageVersionAssetAction: (
        "repositories_AddVersionAsset",
        pydantic.TypeAdapter(repositories.AddPackageVersionAssetOutput),
    ),
    repositories.RemovePackageVersionAssetAction: (
        "repositories_RemoveVersionAsset",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.SetPackageVersionAssetMetadataAction: (
        "repositories_SetVersionAssetMetadata",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.TagPackageVersionAction: (
        "repositories_TagVersion",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.UntagPackageVersionAction: (
        "repositories_UntagVersion",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.ResolvePackageVersionAssetByPathAction: (
        "repositories_ResolveVersionAssetByPath",
        pydantic.TypeAdapter(repositories.ResolvePackageVersionAssetByPathOutput),
    ),
    repositories.SetRepositoryS3ConfigAction: (
        "repositories_SetS3Config",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.GetRepositoryS3ConfigAction: (
        "repositories_GetS3Config",
        pydantic.TypeAdapter(repositories.GetRepositoryS3ConfigOutput),
    ),
    repositories.GetAssetDetailsAction: (
        "repositories_GetAssetDetails",
        pydantic.TypeAdapter(repositories.GetAssetDetailsOutput),
    ),
    repositories.CreateAssetAction: (
        "repositories_CreateAsset",
        pydantic.TypeAdapter(repositories.CreateAssetOutput),
    ),
    repositories.DeleteAssetAction: (
        "repositories_DeleteAsset",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    repositories.IssueAssetDownloadUrlAction: (
        "repositories_IssueAssetDownloadUrl",
        pydantic.TypeAdapter(repositories.IssueAssetDownloadUrlOutput),
    ),
    repositories.IssueAssetUploadUrlAction: (
        "repositories_IssueAssetUploadUrl",
        pydantic.TypeAdapter(repositories.IssueAssetUploadUrlOutput),
    ),
    repositories.QueryAuditLogEventsAction: (
        "repositories_QueryAuditLog",
        pydantic.TypeAdapter(repositories.QueryAuditLogEventsOutput),
    ),
    audit.QueryAuditLogEventsAction: (
        "audit_QueryAuditLogEvents",
        pydantic.TypeAdapter(audit.QueryAuditLogEventsOutput),
    ),
    audit.QueryAuditLogActionsAction: (
        "audit_QueryAuditLogActions",
        pydantic.TypeAdapter(audit.QueryAuditLogActionsOutput),
    ),
    jobs.QueryJobsAction: ("jobs_Query", pydantic.TypeAdapter(jobs.QueryJobsOutput)),
    instance.GetInstanceStatisticsAction: (
        "instance_GetStatistics",
        pydantic.TypeAdapter(instance.GetInstanceStatisticsOutput),
    ),
    instance.GetInstanceSettingsRawAction: (
        "instance_GetSettingsRaw",
        pydantic.TypeAdapter(instance.GetInstanceSettingsRawOutput),
    ),
    instance.SetInstanceSettingRawAction: (
        "instance_SetSettingRaw",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    cluster.GetClusterDetailsAction: (
        "cluster_GetDetails",
        pydantic.TypeAdapter(cluster.GetClusterDetailsOutput),
    ),
    cluster.RegisterClusterNodeAction: (
        "cluster_RegisterNode",
        pydantic.TypeAdapter(cluster.RegisterClusterNodeOutput),
    ),
    cluster.ReportClusterNodeHeartbeatAction: (
        "cluster_ReportNodeHeartbeat",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    cluster.CleanupInactiveClusterNodesAction: (
        "cluster_CleanupInactiveNodes",
        pydantic.TypeAdapter(outputs.Empty),
    ),
    actor.GetActorAction: (
        "actor_GetActor",
        pydantic.TypeAdapter(actor.GetActorOutput),
    ),
}


class _SyncExecuteMixin:
    """Type overloads for the synchronous client."""

    @overload
    def execute(self, action: users.QueryUsersAction) -> users.QueryUsersOutput: ...

    @overload
    def execute(
        self, action: users.GetUserDetailsAction
    ) -> users.GetUserDetailsOutput: ...

    @overload
    def execute(self, action: users.CreateUserAction) -> users.CreateUserOutput: ...

    @overload
    def execute(self, action: users.DeleteUserAction) -> outputs.Empty: ...

    @overload
    def execute(self, action: users.SetUserDisplayNameAction) -> outputs.Empty: ...

    @overload
    def execute(self, action: users.SetUserPasswordAction) -> outputs.Empty: ...

    @overload
    def execute(self, action: users.SetUserIsAdminAction) -> outputs.Empty: ...

    @overload
    def execute(self, action: users.ResetUserPasswordAction) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: users.CompleteUserPasswordResetAction
    ) -> users.CompleteUserPasswordResetOutput: ...

    @overload
    def execute(
        self, action: users.QueryUserTokensAction
    ) -> users.QueryUserTokensOutput: ...

    @overload
    def execute(
        self, action: users.QueryUserOrganizationsAction
    ) -> users.QueryUserOrganizationsOutput: ...

    @overload
    def execute(
        self, action: users.QueryUserOrganizationInvitationsAction
    ) -> users.QueryUserOrganizationInvitationsOutput: ...

    @overload
    def execute(
        self, action: users.QueryUserSessionsAction
    ) -> users.QueryUserSessionsOutput: ...

    @overload
    def execute(
        self, action: users.AuthenticateWithUserTokenAction
    ) -> users.AuthenticateWithUserTokenOutput: ...

    @overload
    def execute(
        self, action: users.AuthenticateWithSessionTokenAction
    ) -> users.AuthenticateWithSessionTokenOutput: ...

    @overload
    def execute(
        self, action: users.GetDevicePermissionsAction
    ) -> users.GetDevicePermissionsOutput: ...

    @overload
    def execute(
        self, action: users.CreateUserTokenAction
    ) -> users.CreateUserTokenOutput: ...

    @overload
    def execute(self, action: users.DeleteUserTokenAction) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: users.InitiateUserSessionAction
    ) -> users.InitiateUserSessionOutput: ...

    @overload
    def execute(self, action: users.TerminateUserSessionAction) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: users.CleanupExpiredUserSessionsAction
    ) -> outputs.Empty: ...

    @overload
    def execute(self, action: users.RegisterUserAction) -> users.RegisterUserOutput: ...

    @overload
    def execute(self, action: users.ResendRegistrationEmailAction) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: users.CompleteRegistrationAction
    ) -> users.CompleteRegistrationOutput: ...

    @overload
    def execute(
        self, action: users.AcceptOrganizationInvitationAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: organizations.QueryOrganizationsAction
    ) -> organizations.QueryOrganizationsOutput: ...

    @overload
    def execute(
        self, action: organizations.QueryOrganizationMembersAction
    ) -> organizations.QueryOrganizationMembersOutput: ...

    @overload
    def execute(
        self, action: organizations.QueryOrganizationProjectsAction
    ) -> organizations.QueryOrganizationProjectsOutput: ...

    @overload
    def execute(
        self, action: organizations.QueryOrganizationRepositoriesAction
    ) -> organizations.QueryOrganizationRepositoriesOutput: ...

    @overload
    def execute(
        self, action: organizations.QueryOrganizationInvitationsAction
    ) -> organizations.QueryOrganizationInvitationsOutput: ...

    @overload
    def execute(
        self, action: organizations.CreateOrganizationAction
    ) -> organizations.CreateOrganizationOutput: ...

    @overload
    def execute(
        self, action: organizations.DeleteOrganizationAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: organizations.AddOrganizationMemberAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: organizations.RemoveOrganizationMemberAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: organizations.SetOrganizationMemberIsAdminAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: organizations.InviteOrganizationMemberAction
    ) -> organizations.InviteOrganizationMemberOutput: ...

    @overload
    def execute(
        self, action: organizations.DeleteOrganizationInvitationAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: organizations.QueryOrganizationAuditLogAction
    ) -> organizations.QueryOrganizationAuditLogOutput: ...

    @overload
    def execute(
        self, action: projects.QueryProjectsAction
    ) -> projects.QueryProjectsOutput: ...

    @overload
    def execute(
        self, action: projects.GetProjectDetailsAction
    ) -> projects.GetProjectDetailsOutput: ...

    @overload
    def execute(
        self, action: projects.CreateProjectAction
    ) -> projects.CreateProjectOutput: ...

    @overload
    def execute(self, action: projects.DeleteProjectAction) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: projects.QueryProjectDevicesAction
    ) -> projects.QueryProjectDevicesOutput: ...

    @overload
    def execute(
        self, action: projects.QueryProjectDeploymentTokensAction
    ) -> projects.QueryProjectDeploymentTokensOutput: ...

    @overload
    def execute(
        self, action: projects.QueryProjectRepositoriesAction
    ) -> projects.QueryProjectRepositoriesOutput: ...

    @overload
    def execute(self, action: projects.SetProjectNameAction) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: projects.CreateDeploymentTokenAction
    ) -> projects.CreateDeploymentTokenOutput: ...

    @overload
    def execute(
        self, action: projects.DeleteDeploymentTokenAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: projects.SetDeploymentTokenFlagsAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: projects.QueryAuditLogEventsAction
    ) -> projects.QueryAuditLogEventsOutput: ...

    @overload
    def execute(self, action: projects.AddProjectRepositoryAction) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: projects.RemoveProjectRepositoryAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: projects.GetProjectOtlpConfigAction
    ) -> projects.GetProjectOtlpConfigOutput: ...

    @overload
    def execute(self, action: projects.SetProjectOtlpConfigAction) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: devices.QueryDevicesAction
    ) -> devices.QueryDevicesOutput: ...

    @overload
    def execute(
        self, action: devices.GetDeviceDetailsAction
    ) -> devices.GetDeviceDetailsOutput: ...

    @overload
    def execute(
        self, action: devices.CreateDeviceAction
    ) -> devices.CreateDeviceOutput: ...

    @overload
    def execute(self, action: devices.DeleteDeviceAction) -> outputs.Empty: ...

    @overload
    def execute(self, action: devices.SetDeviceNameAction) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: devices.IssueDeviceTokenAction
    ) -> devices.IssueDeviceTokenOutput: ...

    @overload
    def execute(
        self, action: devices.ValidateDeviceTokenAction
    ) -> devices.ValidateDeviceTokenOutput: ...

    @overload
    def execute(
        self, action: devices.AuthenticateDeviceAction
    ) -> devices.AuthenticateDeviceOutput: ...

    @overload
    def execute(
        self, action: devices.AddDeviceCertificateAction
    ) -> devices.AddDeviceCertificateOutput: ...

    @overload
    def execute(
        self, action: devices.DeleteDeviceCertificateAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: devices.SetDeviceCertificateStatusAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: devices.RegisterDeviceConnectionAction
    ) -> devices.RegisterDeviceConnectionOutput: ...

    @overload
    def execute(
        self, action: devices.UnregisterDeviceConnectionAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: devices.QueryDeviceConnectionsAction
    ) -> devices.QueryDeviceConnectionsOutput: ...

    @overload
    def execute(
        self, action: devices.IssueDeviceHttpProxyTokenAction
    ) -> devices.IssueDeviceHttpProxyTokenOutput: ...

    @overload
    def execute(
        self, action: devices.ValidateDeviceHttpProxyTokenAction
    ) -> devices.ValidateDeviceHttpProxyTokenOutput: ...

    @overload
    def execute(self, action: devices.PublishDeviceEventsAction) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: devices.QueryDeviceEventsAction
    ) -> devices.QueryDeviceEventsOutput: ...

    @overload
    def execute(
        self, action: devices.SetDevicePropertyAction
    ) -> devices.SetDevicePropertyOutput: ...

    @overload
    def execute(
        self, action: devices.GetDevicePropertyAction
    ) -> devices.GetDevicePropertyOutput: ...

    @overload
    def execute(
        self, action: devices.RemoveDevicePropertyAction
    ) -> devices.RemoveDevicePropertyOutput: ...

    @overload
    def execute(
        self, action: devices.QueryDevicePropertiesAction
    ) -> devices.QueryDevicePropertiesOutput: ...

    @overload
    def execute(
        self, action: devices.QueryDeviceAuditLogAction
    ) -> devices.QueryDeviceAuditLogOutput: ...

    @overload
    def execute(
        self, action: devices.QueryDeviceCommandsAction
    ) -> devices.QueryDeviceCommandsOutput: ...

    @overload
    def execute(self, action: fleet.SetFleetPropertyAction) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: fleet.GetFleetPropertyAction
    ) -> fleet.GetFleetPropertyOutput: ...

    @overload
    def execute(
        self, action: fleet.RemoveFleetPropertyAction
    ) -> fleet.RemoveFleetPropertyOutput: ...

    @overload
    def execute(
        self, action: fleet.QueryFleetPropertiesAction
    ) -> fleet.QueryFleetPropertiesOutput: ...

    @overload
    def execute(
        self, action: fleet.DefineComputedFleetPropertyAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: fleet.QueryComputedFleetPropertyDefinitionsAction
    ) -> fleet.QueryComputedFleetPropertyDefinitionsOutput: ...

    @overload
    def execute(
        self, action: repositories.ResolveRepositoryNameAction
    ) -> repositories.ResolveRepositoryNameOutput: ...

    @overload
    def execute(
        self, action: repositories.GetRepositoryDetailsAction
    ) -> repositories.GetRepositoryDetailsOutput: ...

    @overload
    def execute(
        self, action: repositories.CreateRepositoryAction
    ) -> repositories.CreateRepositoryOutput: ...

    @overload
    def execute(self, action: repositories.DeleteRepositoryAction) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: repositories.SetRepositoryVisibilityAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: repositories.SetRepositoryDisplayNameAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: repositories.SetRepositoryPublicNameAction
    ) -> repositories.SetRepositoryPublicNameOutput: ...

    @overload
    def execute(
        self, action: repositories.QueryRepositoryPackagesAction
    ) -> repositories.QueryRepositoryPackagesOutput: ...

    @overload
    def execute(
        self, action: repositories.QueryRepositoryAssetsAction
    ) -> repositories.QueryRepositoryAssetsOutput: ...

    @overload
    def execute(
        self, action: repositories.QueryRepositoryProjectsAction
    ) -> repositories.QueryRepositoryProjectsOutput: ...

    @overload
    def execute(
        self, action: repositories.ResolvePackageByPathAction
    ) -> repositories.ResolvePackageByPathOutput: ...

    @overload
    def execute(
        self, action: repositories.GetPackageDetailsAction
    ) -> repositories.GetPackageDetailsOutput: ...

    @overload
    def execute(
        self, action: repositories.CreatePackageAction
    ) -> repositories.CreatePackageOutput: ...

    @overload
    def execute(self, action: repositories.DeletePackageAction) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: repositories.SetPackageNameAction
    ) -> repositories.SetPackageNameOutput: ...

    @overload
    def execute(self, action: repositories.SetPackageKindAction) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: repositories.SetPackageMetadataAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: repositories.QueryPackageVersionsAction
    ) -> repositories.QueryPackageVersionsOutput: ...

    @overload
    def execute(
        self, action: repositories.ResolvePackageVersionByPathAction
    ) -> repositories.ResolvePackageVersionByPathOutput: ...

    @overload
    def execute(
        self, action: repositories.GetPackageVersionDetailsAction
    ) -> repositories.GetPackageVersionDetailsOutput: ...

    @overload
    def execute(
        self, action: repositories.CreatePackageVersionAction
    ) -> repositories.CreatePackageVersionOutput: ...

    @overload
    def execute(
        self, action: repositories.DeletePackageVersionAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: repositories.SetPackageVersionNameAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: repositories.SetPackageVersionMetadataAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: repositories.AddPackageVersionAssetAction
    ) -> repositories.AddPackageVersionAssetOutput: ...

    @overload
    def execute(
        self, action: repositories.RemovePackageVersionAssetAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: repositories.SetPackageVersionAssetMetadataAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: repositories.TagPackageVersionAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: repositories.UntagPackageVersionAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: repositories.ResolvePackageVersionAssetByPathAction
    ) -> repositories.ResolvePackageVersionAssetByPathOutput: ...

    @overload
    def execute(
        self, action: repositories.SetRepositoryS3ConfigAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: repositories.GetRepositoryS3ConfigAction
    ) -> repositories.GetRepositoryS3ConfigOutput: ...

    @overload
    def execute(
        self, action: repositories.GetAssetDetailsAction
    ) -> repositories.GetAssetDetailsOutput: ...

    @overload
    def execute(
        self, action: repositories.CreateAssetAction
    ) -> repositories.CreateAssetOutput: ...

    @overload
    def execute(self, action: repositories.DeleteAssetAction) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: repositories.IssueAssetDownloadUrlAction
    ) -> repositories.IssueAssetDownloadUrlOutput: ...

    @overload
    def execute(
        self, action: repositories.IssueAssetUploadUrlAction
    ) -> repositories.IssueAssetUploadUrlOutput: ...

    @overload
    def execute(
        self, action: repositories.QueryAuditLogEventsAction
    ) -> repositories.QueryAuditLogEventsOutput: ...

    @overload
    def execute(
        self, action: audit.QueryAuditLogEventsAction
    ) -> audit.QueryAuditLogEventsOutput: ...

    @overload
    def execute(
        self, action: audit.QueryAuditLogActionsAction
    ) -> audit.QueryAuditLogActionsOutput: ...

    @overload
    def execute(self, action: jobs.QueryJobsAction) -> jobs.QueryJobsOutput: ...

    @overload
    def execute(
        self, action: instance.GetInstanceStatisticsAction
    ) -> instance.GetInstanceStatisticsOutput: ...

    @overload
    def execute(
        self, action: instance.GetInstanceSettingsRawAction
    ) -> instance.GetInstanceSettingsRawOutput: ...

    @overload
    def execute(
        self, action: instance.SetInstanceSettingRawAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: cluster.GetClusterDetailsAction
    ) -> cluster.GetClusterDetailsOutput: ...

    @overload
    def execute(
        self, action: cluster.RegisterClusterNodeAction
    ) -> cluster.RegisterClusterNodeOutput: ...

    @overload
    def execute(
        self, action: cluster.ReportClusterNodeHeartbeatAction
    ) -> outputs.Empty: ...

    @overload
    def execute(
        self, action: cluster.CleanupInactiveClusterNodesAction
    ) -> outputs.Empty: ...

    @overload
    def execute(self, action: actor.GetActorAction) -> actor.GetActorOutput: ...

    def execute(self, action: pydantic.BaseModel) -> pydantic.BaseModel:
        return self._execute_action(action)

    def _execute_action(self, action: pydantic.BaseModel) -> pydantic.BaseModel:
        raise NotImplementedError


class _AsyncExecuteMixin:
    """Type overloads for the asynchronous client."""

    @overload
    async def execute(
        self, action: users.QueryUsersAction
    ) -> users.QueryUsersOutput: ...

    @overload
    async def execute(
        self, action: users.GetUserDetailsAction
    ) -> users.GetUserDetailsOutput: ...

    @overload
    async def execute(
        self, action: users.CreateUserAction
    ) -> users.CreateUserOutput: ...

    @overload
    async def execute(self, action: users.DeleteUserAction) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: users.SetUserDisplayNameAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(self, action: users.SetUserPasswordAction) -> outputs.Empty: ...

    @overload
    async def execute(self, action: users.SetUserIsAdminAction) -> outputs.Empty: ...

    @overload
    async def execute(self, action: users.ResetUserPasswordAction) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: users.CompleteUserPasswordResetAction
    ) -> users.CompleteUserPasswordResetOutput: ...

    @overload
    async def execute(
        self, action: users.QueryUserTokensAction
    ) -> users.QueryUserTokensOutput: ...

    @overload
    async def execute(
        self, action: users.QueryUserOrganizationsAction
    ) -> users.QueryUserOrganizationsOutput: ...

    @overload
    async def execute(
        self, action: users.QueryUserOrganizationInvitationsAction
    ) -> users.QueryUserOrganizationInvitationsOutput: ...

    @overload
    async def execute(
        self, action: users.QueryUserSessionsAction
    ) -> users.QueryUserSessionsOutput: ...

    @overload
    async def execute(
        self, action: users.AuthenticateWithUserTokenAction
    ) -> users.AuthenticateWithUserTokenOutput: ...

    @overload
    async def execute(
        self, action: users.AuthenticateWithSessionTokenAction
    ) -> users.AuthenticateWithSessionTokenOutput: ...

    @overload
    async def execute(
        self, action: users.GetDevicePermissionsAction
    ) -> users.GetDevicePermissionsOutput: ...

    @overload
    async def execute(
        self, action: users.CreateUserTokenAction
    ) -> users.CreateUserTokenOutput: ...

    @overload
    async def execute(self, action: users.DeleteUserTokenAction) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: users.InitiateUserSessionAction
    ) -> users.InitiateUserSessionOutput: ...

    @overload
    async def execute(
        self, action: users.TerminateUserSessionAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: users.CleanupExpiredUserSessionsAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: users.RegisterUserAction
    ) -> users.RegisterUserOutput: ...

    @overload
    async def execute(
        self, action: users.ResendRegistrationEmailAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: users.CompleteRegistrationAction
    ) -> users.CompleteRegistrationOutput: ...

    @overload
    async def execute(
        self, action: users.AcceptOrganizationInvitationAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: organizations.QueryOrganizationsAction
    ) -> organizations.QueryOrganizationsOutput: ...

    @overload
    async def execute(
        self, action: organizations.QueryOrganizationMembersAction
    ) -> organizations.QueryOrganizationMembersOutput: ...

    @overload
    async def execute(
        self, action: organizations.QueryOrganizationProjectsAction
    ) -> organizations.QueryOrganizationProjectsOutput: ...

    @overload
    async def execute(
        self, action: organizations.QueryOrganizationRepositoriesAction
    ) -> organizations.QueryOrganizationRepositoriesOutput: ...

    @overload
    async def execute(
        self, action: organizations.QueryOrganizationInvitationsAction
    ) -> organizations.QueryOrganizationInvitationsOutput: ...

    @overload
    async def execute(
        self, action: organizations.CreateOrganizationAction
    ) -> organizations.CreateOrganizationOutput: ...

    @overload
    async def execute(
        self, action: organizations.DeleteOrganizationAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: organizations.AddOrganizationMemberAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: organizations.RemoveOrganizationMemberAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: organizations.SetOrganizationMemberIsAdminAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: organizations.InviteOrganizationMemberAction
    ) -> organizations.InviteOrganizationMemberOutput: ...

    @overload
    async def execute(
        self, action: organizations.DeleteOrganizationInvitationAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: organizations.QueryOrganizationAuditLogAction
    ) -> organizations.QueryOrganizationAuditLogOutput: ...

    @overload
    async def execute(
        self, action: projects.QueryProjectsAction
    ) -> projects.QueryProjectsOutput: ...

    @overload
    async def execute(
        self, action: projects.GetProjectDetailsAction
    ) -> projects.GetProjectDetailsOutput: ...

    @overload
    async def execute(
        self, action: projects.CreateProjectAction
    ) -> projects.CreateProjectOutput: ...

    @overload
    async def execute(self, action: projects.DeleteProjectAction) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: projects.QueryProjectDevicesAction
    ) -> projects.QueryProjectDevicesOutput: ...

    @overload
    async def execute(
        self, action: projects.QueryProjectDeploymentTokensAction
    ) -> projects.QueryProjectDeploymentTokensOutput: ...

    @overload
    async def execute(
        self, action: projects.QueryProjectRepositoriesAction
    ) -> projects.QueryProjectRepositoriesOutput: ...

    @overload
    async def execute(self, action: projects.SetProjectNameAction) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: projects.CreateDeploymentTokenAction
    ) -> projects.CreateDeploymentTokenOutput: ...

    @overload
    async def execute(
        self, action: projects.DeleteDeploymentTokenAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: projects.SetDeploymentTokenFlagsAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: projects.QueryAuditLogEventsAction
    ) -> projects.QueryAuditLogEventsOutput: ...

    @overload
    async def execute(
        self, action: projects.AddProjectRepositoryAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: projects.RemoveProjectRepositoryAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: projects.GetProjectOtlpConfigAction
    ) -> projects.GetProjectOtlpConfigOutput: ...

    @overload
    async def execute(
        self, action: projects.SetProjectOtlpConfigAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: devices.QueryDevicesAction
    ) -> devices.QueryDevicesOutput: ...

    @overload
    async def execute(
        self, action: devices.GetDeviceDetailsAction
    ) -> devices.GetDeviceDetailsOutput: ...

    @overload
    async def execute(
        self, action: devices.CreateDeviceAction
    ) -> devices.CreateDeviceOutput: ...

    @overload
    async def execute(self, action: devices.DeleteDeviceAction) -> outputs.Empty: ...

    @overload
    async def execute(self, action: devices.SetDeviceNameAction) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: devices.IssueDeviceTokenAction
    ) -> devices.IssueDeviceTokenOutput: ...

    @overload
    async def execute(
        self, action: devices.ValidateDeviceTokenAction
    ) -> devices.ValidateDeviceTokenOutput: ...

    @overload
    async def execute(
        self, action: devices.AuthenticateDeviceAction
    ) -> devices.AuthenticateDeviceOutput: ...

    @overload
    async def execute(
        self, action: devices.AddDeviceCertificateAction
    ) -> devices.AddDeviceCertificateOutput: ...

    @overload
    async def execute(
        self, action: devices.DeleteDeviceCertificateAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: devices.SetDeviceCertificateStatusAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: devices.RegisterDeviceConnectionAction
    ) -> devices.RegisterDeviceConnectionOutput: ...

    @overload
    async def execute(
        self, action: devices.UnregisterDeviceConnectionAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: devices.QueryDeviceConnectionsAction
    ) -> devices.QueryDeviceConnectionsOutput: ...

    @overload
    async def execute(
        self, action: devices.IssueDeviceHttpProxyTokenAction
    ) -> devices.IssueDeviceHttpProxyTokenOutput: ...

    @overload
    async def execute(
        self, action: devices.ValidateDeviceHttpProxyTokenAction
    ) -> devices.ValidateDeviceHttpProxyTokenOutput: ...

    @overload
    async def execute(
        self, action: devices.PublishDeviceEventsAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: devices.QueryDeviceEventsAction
    ) -> devices.QueryDeviceEventsOutput: ...

    @overload
    async def execute(
        self, action: devices.SetDevicePropertyAction
    ) -> devices.SetDevicePropertyOutput: ...

    @overload
    async def execute(
        self, action: devices.GetDevicePropertyAction
    ) -> devices.GetDevicePropertyOutput: ...

    @overload
    async def execute(
        self, action: devices.RemoveDevicePropertyAction
    ) -> devices.RemoveDevicePropertyOutput: ...

    @overload
    async def execute(
        self, action: devices.QueryDevicePropertiesAction
    ) -> devices.QueryDevicePropertiesOutput: ...

    @overload
    async def execute(
        self, action: devices.QueryDeviceAuditLogAction
    ) -> devices.QueryDeviceAuditLogOutput: ...

    @overload
    async def execute(
        self, action: devices.QueryDeviceCommandsAction
    ) -> devices.QueryDeviceCommandsOutput: ...

    @overload
    async def execute(self, action: fleet.SetFleetPropertyAction) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: fleet.GetFleetPropertyAction
    ) -> fleet.GetFleetPropertyOutput: ...

    @overload
    async def execute(
        self, action: fleet.RemoveFleetPropertyAction
    ) -> fleet.RemoveFleetPropertyOutput: ...

    @overload
    async def execute(
        self, action: fleet.QueryFleetPropertiesAction
    ) -> fleet.QueryFleetPropertiesOutput: ...

    @overload
    async def execute(
        self, action: fleet.DefineComputedFleetPropertyAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: fleet.QueryComputedFleetPropertyDefinitionsAction
    ) -> fleet.QueryComputedFleetPropertyDefinitionsOutput: ...

    @overload
    async def execute(
        self, action: repositories.ResolveRepositoryNameAction
    ) -> repositories.ResolveRepositoryNameOutput: ...

    @overload
    async def execute(
        self, action: repositories.GetRepositoryDetailsAction
    ) -> repositories.GetRepositoryDetailsOutput: ...

    @overload
    async def execute(
        self, action: repositories.CreateRepositoryAction
    ) -> repositories.CreateRepositoryOutput: ...

    @overload
    async def execute(
        self, action: repositories.DeleteRepositoryAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: repositories.SetRepositoryVisibilityAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: repositories.SetRepositoryDisplayNameAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: repositories.SetRepositoryPublicNameAction
    ) -> repositories.SetRepositoryPublicNameOutput: ...

    @overload
    async def execute(
        self, action: repositories.QueryRepositoryPackagesAction
    ) -> repositories.QueryRepositoryPackagesOutput: ...

    @overload
    async def execute(
        self, action: repositories.QueryRepositoryAssetsAction
    ) -> repositories.QueryRepositoryAssetsOutput: ...

    @overload
    async def execute(
        self, action: repositories.QueryRepositoryProjectsAction
    ) -> repositories.QueryRepositoryProjectsOutput: ...

    @overload
    async def execute(
        self, action: repositories.ResolvePackageByPathAction
    ) -> repositories.ResolvePackageByPathOutput: ...

    @overload
    async def execute(
        self, action: repositories.GetPackageDetailsAction
    ) -> repositories.GetPackageDetailsOutput: ...

    @overload
    async def execute(
        self, action: repositories.CreatePackageAction
    ) -> repositories.CreatePackageOutput: ...

    @overload
    async def execute(
        self, action: repositories.DeletePackageAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: repositories.SetPackageNameAction
    ) -> repositories.SetPackageNameOutput: ...

    @overload
    async def execute(
        self, action: repositories.SetPackageKindAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: repositories.SetPackageMetadataAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: repositories.QueryPackageVersionsAction
    ) -> repositories.QueryPackageVersionsOutput: ...

    @overload
    async def execute(
        self, action: repositories.ResolvePackageVersionByPathAction
    ) -> repositories.ResolvePackageVersionByPathOutput: ...

    @overload
    async def execute(
        self, action: repositories.GetPackageVersionDetailsAction
    ) -> repositories.GetPackageVersionDetailsOutput: ...

    @overload
    async def execute(
        self, action: repositories.CreatePackageVersionAction
    ) -> repositories.CreatePackageVersionOutput: ...

    @overload
    async def execute(
        self, action: repositories.DeletePackageVersionAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: repositories.SetPackageVersionNameAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: repositories.SetPackageVersionMetadataAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: repositories.AddPackageVersionAssetAction
    ) -> repositories.AddPackageVersionAssetOutput: ...

    @overload
    async def execute(
        self, action: repositories.RemovePackageVersionAssetAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: repositories.SetPackageVersionAssetMetadataAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: repositories.TagPackageVersionAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: repositories.UntagPackageVersionAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: repositories.ResolvePackageVersionAssetByPathAction
    ) -> repositories.ResolvePackageVersionAssetByPathOutput: ...

    @overload
    async def execute(
        self, action: repositories.SetRepositoryS3ConfigAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: repositories.GetRepositoryS3ConfigAction
    ) -> repositories.GetRepositoryS3ConfigOutput: ...

    @overload
    async def execute(
        self, action: repositories.GetAssetDetailsAction
    ) -> repositories.GetAssetDetailsOutput: ...

    @overload
    async def execute(
        self, action: repositories.CreateAssetAction
    ) -> repositories.CreateAssetOutput: ...

    @overload
    async def execute(
        self, action: repositories.DeleteAssetAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: repositories.IssueAssetDownloadUrlAction
    ) -> repositories.IssueAssetDownloadUrlOutput: ...

    @overload
    async def execute(
        self, action: repositories.IssueAssetUploadUrlAction
    ) -> repositories.IssueAssetUploadUrlOutput: ...

    @overload
    async def execute(
        self, action: repositories.QueryAuditLogEventsAction
    ) -> repositories.QueryAuditLogEventsOutput: ...

    @overload
    async def execute(
        self, action: audit.QueryAuditLogEventsAction
    ) -> audit.QueryAuditLogEventsOutput: ...

    @overload
    async def execute(
        self, action: audit.QueryAuditLogActionsAction
    ) -> audit.QueryAuditLogActionsOutput: ...

    @overload
    async def execute(self, action: jobs.QueryJobsAction) -> jobs.QueryJobsOutput: ...

    @overload
    async def execute(
        self, action: instance.GetInstanceStatisticsAction
    ) -> instance.GetInstanceStatisticsOutput: ...

    @overload
    async def execute(
        self, action: instance.GetInstanceSettingsRawAction
    ) -> instance.GetInstanceSettingsRawOutput: ...

    @overload
    async def execute(
        self, action: instance.SetInstanceSettingRawAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: cluster.GetClusterDetailsAction
    ) -> cluster.GetClusterDetailsOutput: ...

    @overload
    async def execute(
        self, action: cluster.RegisterClusterNodeAction
    ) -> cluster.RegisterClusterNodeOutput: ...

    @overload
    async def execute(
        self, action: cluster.ReportClusterNodeHeartbeatAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(
        self, action: cluster.CleanupInactiveClusterNodesAction
    ) -> outputs.Empty: ...

    @overload
    async def execute(self, action: actor.GetActorAction) -> actor.GetActorOutput: ...

    async def execute(self, action: pydantic.BaseModel) -> pydantic.BaseModel:
        return await self._execute_action(action)

    async def _execute_action(self, action: pydantic.BaseModel) -> pydantic.BaseModel:
        raise NotImplementedError
